nkms/client.py, nkms/crypto/kmac.py, nkms/crypto/pre/bbs98.py, tests/test_client.py, tests/test_kmac.py
This fills out the contents of the API commented in `client.py`.
This is a work-in-progress and all code is subject to change before final merge.
=> [WIP] Add cryptographic code to client.py

nkms/client.py, setup.py, tests/test_client.py
1. Some minor bug fixes
2. Adds methods for creating headers to attach to files for storage.
2a. Defines what a basic header should/will look like.
3. Adds high level Encryption and Decryption methods (`encrypt` and `decrypt`) that should "just work".
3a. This does not contain tests yet. Tests will use the `tempfile` module.
4. Adds a high level `open` method that opens and decrypts an encrypted file.
4a. Test not built yet, will also use the `tempfile` module.
5. Adds a minimal version numbering system for the prealpha API.
Tests will be added in a future PR/commit in `tests/test_client_crypto.py`.
=> Handle high level encryption/decryption

Pipfile, nkms/keystore/db/__init__.py, nkms/keystore/db/models.py, nkms/keystore/keystore.py, tests/keystore/test_keystore.py
=> Implement SQLite for KeyStore

nkms/characters.py, nkms/network/node.py, nkms/policy/models.py, tests/characters/test_alice_can_grant_and_revoke.py, tests/characters/test_bob_handles_frags.py, tests/utilities.py
=> Bob no longer needs to store a PolicyGroup to generate WorkOrders.

nkms/blockchain/eth/chains.py, nkms/blockchain/eth/deployers.py, nkms/blockchain/eth/interfaces.py, tests/blockchain/eth/contracts/test_miners_escrow.py, tests/blockchain/eth/entities/test_actors.py, tests/blockchain/eth/entities/test_agents.py, tests/blockchain/eth/test_api.py, tests/eth_fixtures.py
Cleanup some loose names in the blockchain modules.
=> Post-update naming cleanup (blockchain)

examples/alicebob-grant-and-line-by-line-PRE.py, nkms/characters.py, nkms/crypto/powers.py, nkms/data_sources.py, nkms/keystore/keypairs.py, nkms/policy/models.py, tests/characters/test_alice_can_grant_and_revoke.py, tests/characters/test_bob_handles_frags.py, tests/fixtures.py, tests/network/test_network_actors.py
* Further simplifies the Finnegan's Wake demo and adds quite a bit of commentary.
* Allows `DataSource` to be reconstructed by Bob for the purpose of `retrieving` content.
* Rewrite of `DelegatingPower` - it now derives its keypair from its `label`.
=> Using new label derivation and evolving Finnegan's Wake demo.

nucypher/blockchain/eth/sol/source/contracts/Issuer.sol, nucypher/blockchain/eth/sol/source/contracts/MinersEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, tests/blockchain/eth/contracts/contracts/IssuerMock.sol, tests/blockchain/eth/contracts/contracts/MinersEscrowForPolicyMock.sol, tests/blockchain/eth/contracts/contracts/PolicyManagerForMinersEscrowMock.sol, tests/blockchain/eth/contracts/contracts/proxy/ContractV1.sol, tests/blockchain/eth/contracts/contracts/proxy/ContractV2.sol, tests/blockchain/eth/contracts/test_dispatcher.py, tests/blockchain/eth/contracts/test_issuer.py, tests/blockchain/eth/contracts/test_miners_escrow.py, tests/blockchain/eth/contracts/test_policy_manager.py, tests/blockchain/eth/entities/test_actors.py, tests/blockchain/eth/entities/test_agents.py
* Size and storage optimization
* `createPolicy` optimization
* Fixes `divideStake`
* Adds methods to check refund
=> Contracts optimization

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/constants.py, nucypher/blockchain/eth/sol/source/contracts/MinersEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/UserEscrow.sol, tests/blockchain/eth/contracts/contracts/MinersEscrowForUserEscrowMock.sol, tests/blockchain/eth/contracts/test_integration.py, tests/blockchain/eth/contracts/test_miners_escrow.py, tests/blockchain/eth/contracts/test_user_escrow.py, tests/blockchain/eth/entities/test_actors.py
Refs #302
* Changes `divideStake` method in the `MinersEscrow` contract to use index to determine stake
* Adds method to obtain all stakes for actors
* Implementation of `divideStake` for actors
=> Actors stake division

.circleci/config.yml
=> [WIP] Add CircleCI

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/constants.py, nucypher/blockchain/eth/scripts/estimate_gas_tester.py, nucypher/blockchain/eth/sol/source/contracts/Issuer.sol, nucypher/blockchain/eth/sol/source/contracts/MinersEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/NuCypherToken.sol, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, nucypher/blockchain/eth/sol/source/contracts/UserEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/lib/AdditionalMath.sol, tests/blockchain/eth/contracts/contracts/GovernmentForUserEscrowMock.sol, tests/blockchain/eth/contracts/contracts/IssuerBad.sol, tests/blockchain/eth/contracts/contracts/IssuerMock.sol, tests/blockchain/eth/contracts/contracts/IssuerV2Mock.sol, tests/blockchain/eth/contracts/contracts/MinersEscrowBad.sol, tests/blockchain/eth/contracts/contracts/MinersEscrowForPolicyMock.sol, tests/blockchain/eth/contracts/contracts/MinersEscrowForUserEscrowMock.sol, tests/blockchain/eth/contracts/contracts/MinersEscrowV2Mock.sol, tests/blockchain/eth/contracts/contracts/PolicyManagerBad.sol, tests/blockchain/eth/contracts/contracts/PolicyManagerForMinersEscrowMock.sol, tests/blockchain/eth/contracts/contracts/PolicyManagerForUserEscrowMock.sol, tests/blockchain/eth/contracts/contracts/PolicyMangerV2Mock.sol, tests/blockchain/eth/contracts/contracts/ReceiveApprovalMethodMock.sol, tests/blockchain/eth/contracts/integration/test_integration.py, tests/blockchain/eth/contracts/unit/test_issuer.py, tests/blockchain/eth/contracts/unit/test_miners_escrow.py, tests/blockchain/eth/contracts/unit/test_policy_manager.py, tests/blockchain/eth/entities/test_actors.py, tests/blockchain/eth/entities/test_agents.py, tests/blockchain/eth/test_deployers.py
=> Removes `minerId`, fixes script for gas estimation, improves sample method 

nucypher/blockchain/economics.py, tests/blockchain/test_economics.py
Converting parameters from the token economics paper into what smart contract can consume
=> High level ecomomic parameters

.circleci/config.yml, Pipfile, nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/policies.py, nucypher/characters.py, nucypher/network/middleware.py, nucypher/network/protocols.py, nucypher/network/server.py, nucypher/policy/models.py, tests/blockchain/eth/entities/test_actors.py, tests/characters/test_alice_can_grant_and_revoke.py, tests/characters/test_bob_handles_frags.py, tests/characters/test_character_serialization.py, tests/characters/test_crypto_characters_and_their_powers.py, tests/characters/test_ursula_prepares_to_act_as_mining_node.py, tests/fixtures.py, tests/network/test_network_actors.py, tests/network/test_node_storage.py, tests/utilities.py
* Bob is working again.
* Ursula is now fully serializable and splittable.
* `TreasureMap` serialization, splitting, and verification is all handled internally.
* Bob now follows TreasureMaps asynchronously
* Ursula now propagates TreasureMaps received via REST
* Can't specify a teacher node as method params anymore.  Just set it as the next teacher.
* Removed some deprecated fixtures
Fixes #172 
Fixes #227
Fixes #235
Fixes #238
Fixes #326 
Depends on bytestringSplitter 9: https://github.com/nucypher/bytestringSplitter/pull/9
=> Learning Loop Part III

nucypher/characters.py, nucypher/keystore/db/models.py, nucypher/keystore/keystore.py, nucypher/network/protocols.py, nucypher/network/server.py, nucypher/policy/models.py, tests/characters/test_alice_can_grant_and_revoke.py, tests/characters/test_bob_handles_frags.py, tests/keystore/test_keystore.py, tests/network/test_network_actors.py, tests/network/test_network_upgrade.py, tests/utilities.py
Arrangement IDs no longer rely on HRAC; they are random and different for each Ursula.
Small optimizations on Learning Loop.
Fixes #136
Fixes #180
=> New Arrangement ID

nucypher/blockchain/eth/sol/compile.py, nucypher/config/utils.py, tests/fixtures.py
Helps with developing smart contracts (not full compatibility)
=> Minor improvements for Windows compatibility

.gitignore, examples/finnegans-wake-federated.py, examples/run_ursula_with_rest_and_dht_but_no_mining.py, nucypher/characters.py, nucypher/crypto/api.py, nucypher/crypto/powers.py, nucypher/keystore/keypairs.py, nucypher/network/middleware.py, nucypher/network/nodes.py, nucypher/network/protocols.py, nucypher/network/server.py, nucypher/policy/models.py, tests/characters/test_bob_handles_frags.py, tests/characters/test_crypto_characters_and_their_powers.py, tests/characters/test_ursula_prepares_to_act_as_mining_node.py, tests/fixtures.py, tests/keystore/test_keypairs.py, tests/network/test_network_actors.py, tests/utilities.py
Freshens up federated logic to be totally up to speed with all learning loop changes and n>1 states.
Federated demo is now `n==3`, `m==2`.  Thus, to run it, you need to run `run_ursula_with_rest_and_dht_but_no_mining.py` three times.
Also:
* Introducing `TLSHostingPower`, which does exactly what it sounds like.
* Nodes now announce themselves when learning
* Nodes continue to learn even if something goes wrong with one teacher. 
Fixes #311
Fixes #332
Fixes #339
Partial #347 
Partial #363
=> Learning Loop Part IV and Working n==3 Federated Demo.

.circleci/config.yml, mypy.ini, nucypher/blockchain/economics.py, nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/chains.py, nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/policies.py, nucypher/blockchain/eth/registry.py, nucypher/blockchain/eth/sol/compile.py, nucypher/characters/lawful.py, nucypher/config/keyring.py, nucypher/crypto/kits.py, nucypher/crypto/powers.py, nucypher/crypto/signing.py, nucypher/data_sources.py, nucypher/keystore/db/models.py, nucypher/keystore/keypairs.py, nucypher/keystore/keystore.py, nucypher/keystore/threading.py, nucypher/network/protocols.py, nucypher/network/server.py, nucypher/policy/models.py
=> #420 but rebased over kokonusswasser

cli/main.py, nucypher/characters/lawful.py, nucypher/config/characters.py, nucypher/config/node.py, nucypher/crypto/api.py, nucypher/network/server.py, tests/cli/test_config.py, tests/cli/test_run_ursula.py, tests/conftest.py, tests/fixtures.py, tests/network/test_network_upgrade.py
Uses the new UrsulaConfiguration API to integrate the temporary storage area and in-memory database with the `run_ursula` command, switched on /off with the `--dev`.
=> --dev flag for `run_ursula` 

cli/main.py, mypy.ini, nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/policies.py, nucypher/blockchain/eth/registry.py, nucypher/blockchain/eth/sol/compile.py, nucypher/characters/lawful.py, nucypher/config/characters.py, nucypher/config/keyring.py, nucypher/config/node.py, nucypher/config/parsers.py, nucypher/crypto/api.py, nucypher/crypto/powers.py, nucypher/network/protocols.py, nucypher/network/server.py, nucypher/policy/models.py, nucypher/utilities/sandbox/policy.py, tests/cli/test_config.py, tests/cli/test_run_ursula.py, tests/conftest.py, tests/fixtures.py, tests/network/test_network_actors.py, tests/network/test_network_upgrade.py
This PR does *not* resolve all the mypy output, but it *does*:
- Add a ton of new type hints and annotations (a bucket-full)
- Reduces `mypy` output noise to help identity legitimate bugs faster
- Fixes NameError, ValueError, and AttributeErrors scattered throughout the code base
- Fix an Inheritance bug with `EthereumContractAgent.__init__`
- Tweak `mypy.ini` options
current output:
https://circleci.com/gh/nucypher/nucypher/2541?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> A bucket of type hints and bug fixes

nucypher/characters/lawful.py, nucypher/network/nodes.py, tests/characters/test_character_serialization.py
=> Add timestamp on Ursula

Pipfile, nucypher/crypto/powers.py, nucypher/keystore/db/models.py, nucypher/keystore/keypairs.py, nucypher/keystore/keystore.py, nucypher/network/server.py, nucypher/policy/models.py, tests/characters/test_alice_can_grant_and_revoke.py, tests/characters/test_bob_handles_frags.py
- Solves #475 
- Solves #167 
- Initial work towards #259 
Depends on https://github.com/nucypher/pyUmbral/pull/220 (_done_)
=> Putting nucypher up-to-date wrt to pyumbral

cli/main.py, nucypher/characters/base.py, nucypher/characters/lawful.py, nucypher/config/characters.py, nucypher/config/constants.py, nucypher/config/keyring.py, nucypher/config/node.py, nucypher/network/server.py, tests/fixtures.py
Restore TLS certificates saved to the disk, deriving them from a `NucypherKeyring` via the `CryptoPower`a API; Removes the handling of private keys within the scope of a `Character`
=> Keyring Derived TLSHostingPower

cli/main.py, nucypher/characters/base.py, nucypher/config/node.py, nucypher/network/middleware.py, nucypher/utilities/sandbox/middleware.py, nucypher/utilities/sandbox/ursula.py, tests/config/test_firstula_circumstances.py, tests/config/test_storages.py, tests/network/test_network_upgrade.py, tests/network/test_node_storage.py
* Seed node learning now occurs primarily in middleware.
* Seed node learning happens in (a)sync with the Learning Loop (ie, starts automatically when the Leaning Loop starts).
* Seed nodes are now verified as soon as they are first contacted.
=> Seed node learning

.circleci/config.yml
CircleCI YML Configuration for automated test-build-deploy workflow; Publishing to PyPI
=> Publication Automation

cli/main.py, examples/finnegans_wake_demo/finnegans-wake-federated.py, nucypher/__init__.py, nucypher/config/constants.py, nucypher/utilities/logging.py, tests/conftest.py
* Use CLI as Primary Sentry Entrypoint
* Better Breadcrumbs
* Pretty Logging
* CLI API Cleanup (Remove Stale, Unused, Crufty)
=> Sentry for CLI Only (#526)

nucypher/network/protocols.py
Full description of the problem here https://github.com/nucypher/nucypher/issues/536
=> Solves issue #536 - Deserialization of port number from raw bytes

tests/cli/test_accounts.py, tests/cli/test_main.py, tests/config/test_storages.py, tests/network/test_node_storage.py
=> Refactor node storages backend tests; Accomodate pytest>4

Pipfile
Co-Authored-By: KPrasch <kieranprasch@gmail.com>
=> [Federated] Pin Umbral 0.1.1.a3 

.circleci/config.yml, .circleci/validate-hook.sh, Pipfile, deploy/docker/Dockerfile, deploy/docker/docker-compose.yml, nucypher/config/node.py, pytest.ini, setup.py
- `Dockerfile` & `dockerfile-compose.yml`
- PyPI publication via circleCI
- Docker Image build and publication via circleCI
`docker-compose build`
`docker-compose run --rm nucypher`
`nucypher ursula init --federated-only --config-root /nucypher`
=> Initial Packaging and Publication Automation 

examples/run_demo_ursulas.py, examples/run_single_demo_ursula.py, nucypher/characters/lawful.py, nucypher/cli/main.py, nucypher/network/nodes.py, nucypher/network/server.py, nucypher/utilities/logging.py, tests/learning/test_fleet_state.py
=> Run Demo Ursulas Script (Local Testing Fleet)

nucypher/cli/main.py, nucypher/config/characters.py, nucypher/config/node.py
=> Domain management via CLI and configurations

examples/run_demo_ursula_fleet.py, examples/run_lonely_demo_ursula.py, nucypher/characters/lawful.py, nucypher/cli/main.py, nucypher/config/characters.py, nucypher/config/keyring.py, nucypher/config/node.py, nucypher/config/storages.py, nucypher/network/nodes.py, nucypher/network/server.py, tests/config/test_keyring.py, tests/network/test_network_actors.py
=> Temp Certificate Bug Fixes; --lonely Ursula

examples/heartbeat_demo/alicia.py, examples/heartbeat_demo/doctor.py, nucypher/characters/lawful.py, nucypher/cli/main.py, nucypher/config/characters.py, nucypher/config/node.py, nucypher/network/nodes.py, nucypher/network/server.py, tests/cli/commands/test_run_ursula.py, tests/config/test_ursula_config.py
=> Heartbeat Demo Compatibility: Storage Defaults, File-based Temp DB

deploy/ansible/run_seednodes.yml, deploy/ansible/update.yml, examples/run_demo_ursula_fleet.py
=> Use en_US.UTF-8 instead of Debian specific C.UTF-8

.circleci/config.yml, .circleci/trigger_job.sh
Fixes #628 (Docker) and multiple bug fixes in `.cirelce/config.yml`
=> Separate automated docker build from upload steps

README.md, docs/source/index.rst, docs/source/release_notes/genesis_release.md
Adds discord badges and cleans up some straggler rendering defects from recent contributions
=> [Docs] Discord Badges -  Documentation Formatting Adjustments

docs/source/architecture/contracts.md, docs/source/architecture/upgradeable_proxy_contracts.md, docs/source/demos/finnegans_wake_demo.rst, docs/source/index.rst
see <https://readthedocs.org/projects/nucypher/builds/8463052/>
=> Resolve sphinx build failures

.bumpversion.cfg, .circleci/config.yml, README.md, docs/source/conf.py, docs/source/guides/contribution_guide.rst, nucypher/__about__.py, setup.py
Continuous automated builds for:
- Test PyPI - <https://test.pypi.org/search/?q=nucypher>
- PyPI - <https://pypi.org/manage/project/nucypher/release/0.1.0a4/>
- ReadTheDocs - <https://nucypher.readthedocs.io/en/latest/>
- Docker - <https://cloud.docker.com/u/nucypher/repository/docker/nucypher/nucypher>
Alpha-4 Workflow: <https://circleci.com/workflow-run/a9c43ebd-68db-4c7c-80bd-e81802f2cdc0>
**Note: These tags have already been pushed and published to distributors, and this PR is a follow-up to synchronise with upstream tags.**
=> [Release] Alpha Distribution

.circleci/config.yml, docs/Makefile, nucypher/cli/processes.py
- Fixes #657 
- Adds `make html` job to CI
=> Ursula Command Help & Docs Build Check

.circleci/config.yml, nucypher/blockchain/eth/sol/compile.py, nucypher/cli/main.py
Temporary Fixes for Issues #755 and #756
=> [Hotfix] Check Standard Installation Entry Points

docs/source/demos/finnegans_wake_demo.rst, docs/source/guides/character_control_guide.rst, examples/finnegans_wake_demo/finnegans-wake-demo.py, examples/heartbeat_demo/doctor.py, nucypher/characters/lawful.py, tests/characters/test_alice_can_grant_and_revoke.py
- Fixes the failing heartbeat demo.
- Removes last remnants of the DataSource in documentation and other places.
=> Bye bye, DataSource.

nucypher/characters/lawful.py, nucypher/cli/alice.py, nucypher/cli/bob.py, nucypher/cli/enrico.py, nucypher/cli/moe.py, nucypher/config/node.py, nucypher/network/middleware.py, nucypher/utilities/logging.py, nucypher/utilities/sandbox/middleware.py, nucypher/utilities/sandbox/policy.py, tests/characters/test_character_control.py, tests/crypto/test_bytestring_types.py, tests/fixtures.py
Motivation:
```
dnunez Today at 9:10 PM
How did you get Bob keys?
Signing and encrypting keys
Mallek561 Today at 9:11 PM
it spit them out in console when i started bob
```
Based on #775
=> An entrypoint to get Bob's public keys in Character Control

nucypher/blockchain/eth/sol/source/contracts/MultiSig.sol, tests/blockchain/eth/contracts/base/test_multisig.py, tests/blockchain/eth/contracts/integration/test_intercontract_integration.py
Multi-signature contract for the upgrading management:
* Contract checks pre-signed transactions
* Allows to remove and add owners and change required number of signed transactions
=> Multi-signature contract with off-chain signing

nucypher/network/nodes.py, nucypher/network/server.py
Following up PR #915 - Opens #917
=> Two bandaids.

nucypher/cli/actions.py, nucypher/cli/characters/alice.py, nucypher/cli/characters/felix.py, nucypher/cli/characters/ursula.py, tests/cli/test_deploy.py, tests/cli/ursula/test_run_ursula.py
=> Automatically determine IPv4 address 

nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/registry.py, nucypher/cli/characters/alice.py, nucypher/cli/characters/bob.py, nucypher/cli/types.py
You need to run parity with geth compatibility enabled:
```
parity --chain goerli --jsonrpc-apis 'eth,web3,personal' --geth
```
and Ursula talking to the JSON RPC (see the provider-uri):
```
nucypher --debug ursula stake --list --poa --provider-uri http://127.0.0.1:8545
```
=> Parity compatibility

nucypher/blockchain/eth/token.py, nucypher/cli/types.py, tests/cli/test_mixed_configurations.py
=> Remove maximum stake duration validation

docs/source/architecture/contracts.md, docs/source/architecture/upgradeable_proxy_contracts.rst, nucypher/blockchain/eth/sol/source/contracts/Adjudicator.sol, nucypher/blockchain/eth/sol/source/contracts/Issuer.sol, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/UserEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/UserEscrowProxy.sol, tests/blockchain/eth/contracts/base/test_issuer.py, tests/blockchain/eth/contracts/contracts/AdjudicatorTestSet.sol, tests/blockchain/eth/contracts/contracts/PolicyManagerTestSet.sol, tests/blockchain/eth/contracts/contracts/StakingEscrowTestSet.sol, tests/blockchain/eth/contracts/contracts/UserEscrowTestSet.sol, tests/blockchain/eth/contracts/integration/test_intercontract_integration.py, tests/blockchain/eth/contracts/main/adjudicator/conftest.py, tests/blockchain/eth/contracts/main/adjudicator/test_adjudicator.py, tests/blockchain/eth/contracts/main/policy_manager/conftest.py, tests/blockchain/eth/contracts/main/policy_manager/test_policy_manager.py, tests/blockchain/eth/contracts/main/staking_escrow/conftest.py, tests/blockchain/eth/contracts/main/staking_escrow/test_mining.py, tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow.py, tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow_additional.py, tests/blockchain/eth/contracts/main/staking_escrow/test_tracking.py, tests/blockchain/eth/contracts/main/user_escrow/conftest.py, tests/blockchain/eth/contracts/main/user_escrow/test_user_escrow.py
Based on #949 
Renames miner to staker in solidity contracts and in tests for them.
Refs #800
=> Miner -> staker in contracts

nucypher/cli/characters/ursula.py
Also make the messages and conditions for this case uniform. Fixes #1025
=> Don't use paint_stakes() for a NO_STAKES value or an empty list

nucypher/characters/lawful.py, nucypher/cli/characters/felix.py, nucypher/cli/characters/ursula.py, nucypher/config/node.py, nucypher/utilities/sandbox/constants.py, tests/cli/ursula/test_blockchain_ursula.py, tests/learning/test_domains.py
=> Make domain names `str` instead of `bytes` throughout the code, and only convert to bytes on serialization

nucypher/characters/lawful.py, nucypher/cli/config.py, nucypher/config/keyring.py, nucypher/config/node.py, nucypher/crypto/api.py, nucypher/crypto/signing.py, nucypher/network/nodes.py, tests/characters/test_ursula_prepares_to_act_as_mining_node.py, tests/cli/test_felix.py, tests/learning/test_fault_tolerance.py
Adds some careful handling of node verification and staking checks during intermode learning.
=> Intermode node verification support

nucypher/characters/lawful.py, nucypher/characters/unlawful.py, nucypher/crypto/api.py, nucypher/network/nodes.py, tests/characters/test_crypto_characters_and_their_powers.py, tests/characters/test_ursula_prepares_to_act_as_mining_node.py, tests/learning/test_fault_tolerance.py, tests/network/test_network_actors.py
Fixes #1044, Needs follow up post #1029  as part of #1003
=> Decentralized Identity Verification Fixes and Naming

README.md, docs/source/guides/character_control_guide.rst, docs/source/guides/contribution_guide.rst, docs/source/guides/installation_guide.md, examples/finnegans_wake_demo/README.md, examples/heartbeat_demo/alicia.py, examples/heartbeat_demo/heartbeat_demo.md, examples/postman/README.md
Per title, fixes several broken links in the docs.
=> Fix broken documentation links

dev/docker/8-federated-ursulas.yml, examples/finnegans_wake_demo/finnegans-wake-demo.py, nucypher/characters/lawful.py, nucypher/cli/characters/ursula.py, nucypher/cli/main.py, nucypher/network/nodes.py, nucypher/network/server.py, tests/characters/control/conftest.py, tests/characters/control/test_web_control.py, tests/characters/test_bob_handles_frags.py, tests/characters/test_bob_joins_policy_and_retrieves.py, tests/cli/test_mixed_configurations.py, tests/cli/ursula/test_federated_ursula.py, tests/fixtures.py
* Chaperones: @jMyles 
---
*Named for **Günter Schabowski**, the somewhat hapless spokesperson for the Sozialistische Einheitspartei Deutschlands who announced on 9 Nov 1989 that travel restrictions from East to West Berlin had been lifted effective immediately - he was supposed to announce that they were going to be slowly lifted over several months.  His announcement led to a surge of many thousands of people to the wall - many with hammers and chisels - and, a few hours later, into West Berlin for the first time in decades.*
*Runner-up name: Ginger, based on what @jMyles was drinking when he opened it.*
=> [EPIC] Schabowski: Fixes for bugs revealed by Coinlist, EthCapeTown, and EthNY hackathons

.circleci/config.yml, scripts/circle/docker-compose.yml
prevents conflicts between dev/docker and circle/docker containers
=> Some CI updates/tweaks

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/token.py, nucypher/config/base.py, nucypher/config/node.py, nucypher/crypto/powers.py, tests/blockchain/eth/clients/test_geth_integration.py, tests/blockchain/eth/entities/actors/test_stakeholder.py, tests/config/test_character_configuration.py
PR goes into epic.  Introduces new Issue https://github.com/nucypher/nucypher/issues/1119
=> Introduce Stakeholder

nucypher/blockchain/eth/actors.py, nucypher/cli/stake.py, tests/blockchain/eth/entities/actors/test_stakeholder.py, tests/cli/ursula/test_run_ursula.py, tests/cli/ursula/test_stakeholder_and_ursula.py, tests/fixtures.py
=> Deprecates "funding account" and account creation options

nucypher/characters/chaotic.py, nucypher/characters/control/controllers.py, nucypher/config/constants.py, nucypher/keystore/keypairs.py, nucypher/network/protocols.py, nucypher/network/server.py, tests/network/test_static_service.py
Adds Twisted/Hendrix static file resources to our web server characters.
This will allow us to build better/nicer admin/monitor/status pages without resorting to hosting statics in centralized ways.
~Much of the code in this PR could be removed if these two PRs to hendrix were merged https://github.com/hendrix/hendrix/pulls~
Much of the code in /network/protocols.py could be removed if we could resolve some dependency issues and use the latest version of Hendrix
=> [WIP] Adds static file service to all web server endpoints

nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/interfaces.py, nucypher/cli/characters/alice.py, nucypher/cli/characters/bob.py, nucypher/cli/characters/ursula.py, nucypher/cli/stake.py, tests/blockchain/eth/clients/test_mocked_clients.py, tests/cli/ursula/test_stakeholder_and_ursula.py
Fix and test for https://github.com/nucypher/nucypher/issues/1199
Also adds nice progress bar to report syncing progress on all CLI sync scenarios.
=> Improved Blockchain Syncing UX

nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/providers.py, nucypher/blockchain/eth/registry.py, nucypher/cli/painting.py, nucypher/cli/status.py, tests/blockchain/eth/clients/test_mocked_clients.py, tests/cli/ursula/test_federated_ursula.py
Fixes #656 https://github.com/nucypher/nucypher/issues/1136 - Based on #1064
=> Restore 'nucypher status'

nucypher/characters/base.py, nucypher/characters/lawful.py, nucypher/cli/actions.py, nucypher/cli/characters/alice.py, nucypher/cli/characters/ursula.py, nucypher/cli/stake.py, nucypher/config/node.py, nucypher/config/storages.py, nucypher/network/nodes.py, nucypher/network/protocols.py, nucypher/network/server.py, tests/cli/test_alice.py, tests/cli/ursula/test_federated_ursula.py, tests/learning/test_domains.py
Based on #1175 
The systemd service file I'm using, in case it's useful:
```
[Unit]
Description="Run 'Ursula', a NuCypher Staking Node."
[Service]
Type=simple
Environment="NUCYPHER_KEYRING_PASSWORD=<your keyring password>"
Environment='NUCYPHER_WORKER_ETH_PASSWORD=<your account password>'
ExecStart=<virtualenv path>/bin/nucypher ursula run --teacher <teacher_uri>
[Install]
WantedBy=multi-user.target
```
=> Bugfixes for getting operative testnet nodes

.circleci/config.yml, nucypher/config/constants.py
These are needed for docker deployments and for flexibility in general.
=> some constants as envvars for flexible deployment

docs/source/demos/local_fleet_demo.rst, docs/source/guides/installation_guide.md, nucypher/blockchain/eth/policies.py, nucypher/characters/base.py, nucypher/characters/lawful.py, nucypher/cli/characters/alice.py, nucypher/cli/characters/bob.py, nucypher/cli/characters/enrico.py, nucypher/cli/characters/ursula.py, nucypher/cli/painting.py, nucypher/config/node.py, nucypher/network/nodes.py, nucypher/network/server.py
Minor touchups and workarounds to achieve a full Alice-Enrico-Bob data flow. Major blockers/bugs to fix are #1202 and #1090 
-----
Steps to reproduce
```
nucypher alice init --provider ipc:///your/provider/geth.ipc  --poa
nucypher bob init --provider ipc:///your/provider/geth.ipc  --poa
```
```
nucypher bob public-keys
```
_Output_:
```
bob_encrypting_key ...... 0202a6be8e400acdd50db42f8b4c62241b61461a08462731efc064b86d63c7cf6f
bob_verifying_key ...... 02ce770f45fecbbee0630129cce0da4fffc0c4276093bdb3f83ecf1ed824e2696c
```
```
nucypher alice grant 
--teacher TEACHER_URI 
--bob-verifying-key 02ce770f45fecbbee0630129cce0da4fffc0c4276093bdb3f83ecf1ed824e2696c 
--bob-encrypting-key 0202a6be8e400acdd50db42f8b4c62241b61461a08462731efc064b86d63c7cf6f 
--label asdf 
--expiration …
```
=> Minimum working example for decentralized Alice-Bob data flow

nucypher/network/server.py, nucypher/network/templates/basic_status.j2
=> Add nucypher version to Ursula status page

nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol, nucypher/policy/policies.py, tests/blockchain/eth/contracts/main/staking_escrow/test_sampling.py, tests/blockchain/eth/contracts/main/staking_escrow/test_sampling_distribution.py, tests/characters/test_ursula_prepares_to_act_as_mining_node.py
Corrects a minor bug in `StakingEscrow.sample()` that was affecting sampling (Fixes #1090)
Also adds a test that checks that sampling produces an acceptable distribution (Closes #1019)
=> Touches to StakingEscrow.sample()

nucypher/characters/chaotic.py, tests/cli/test_felix.py
Branch with the changes made to felix as currently running as the backend for Nubot.
rebased on nucypher/master as of 9/3
=> Felix live

docs/source/demos/local_fleet_demo.rst, docs/source/guides/installation_guide.md, nucypher/cli/config.py, scripts/local_fleet/run_local_fleet.sh
Some of our local fleet scripts/files have had some neglect and were not working.
=> Resolve issues running local development fleet scripts/files

docs/source/guides/staking_guide.rst, docs/source/guides/ursula_configuration_guide.rst
Fixing documentation in accordance with the issues found
=> Staking / Ursula guide update

README.md, docs/source/index.rst
See: https://forum.nucypher.com/t/nucypher-s-mission-values/81/2?u=jmyles
=> Project description.

nucypher/network/status/assets/stylesheet.css, nucypher/network/status/status_page.py
1. Headers and values are different sizes for the widgets
2. Hyperlinks open in new windows/tabs
3. Previous States section has a cleaner display
=> Moe/Ursula Status Page Widgets Cleanup

.circleci/config.yml, Pipfile.lock, dev-requirements.txt, requirements.txt, scripts/circle/compare_reqs.sh, scripts/circle/rebuild_pipenv.sh, scripts/installation/relock_dependencies.sh
Currently prevents new CI workflows from running.
See <https://circleci.com/gh/nucypher/nucypher/46185>
=> Relock Dependencies

nucypher/blockchain/eth/actors.py, nucypher/cli/characters/ursula.py
=> Fixes #1333

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/deployers.py, tests/blockchain/eth/contracts/main/adjudicator/conftest.py, tests/blockchain/eth/entities/deployers/test_adjudicator_deployer.py, tests/blockchain/eth/entities/deployers/test_interdeployer_integration.py
This PR is 100% code optimization following the PR that introduced it (#1157).
Overall, it's more deletions than additions, since it's dehydrating some shared deployer logic.  Makes things a bit more maintainable...
=> Upgradable and Ownable Deployer Mixins

Pipfile.lock, dev-requirements.txt, requirements.txt
See: <https://circleci.com/gh/nucypher/nucypher/47711?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link>
=> Update dependency locks

.circleci/config.yml, README.md, docs/Makefile, docs/source/api/policy.rst, docs/source/architecture/contracts.md, docs/source/demos/local_fleet_demo.rst, docs/source/guides/contribution_guide.rst, docs/source/guides/deployment_guide.rst, docs/source/guides/federated_testnet_guide.rst, docs/source/guides/installation_guide.md, docs/source/guides/staking_guide.rst, docs/source/index.rst
Fixes broken formatting in the docs index and in the staking guide.
Also, some minor touches here and there wrt to formatting.
=> Fixes broken formatting in the docs

nucypher/utilities/sandbox/blockchain.py, tests/blockchain/eth/interfaces/test_chains.py, tests/fixtures.py
* Reset state for chain each module
* Stub for gas estimation while `transact`
=> Contracts tests time optimization

docs/source/guides/staking_guide.rst
- Added commands for MacOS
- Fixed some typos
=> Add commands for MacOS and fixed typos.

docs/source/guides/staking_guide.rst, docs/source/guides/ursula_configuration_guide.rst, nucypher/config/base.py
Fixed some typos, some commands which you updated but didn't update the docs
=> Doc upgrades and addition of verbose output for FileExistsError

nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/interfaces.py, nucypher/characters/base.py, nucypher/characters/lawful.py, nucypher/config/keyring.py, nucypher/crypto/powers.py, nucypher/network/nodes.py
Implements some of the proposed ideas here: <https://github.com/nucypher/nucypher/pull/1338#issuecomment-537176316>
```python
#
#
PROVIDER_URI = '~/.ethereum/goerli/geth.ipc'
KEYRING_ROOT = "~/.local/share/nucypher/keyring"
ACCOUNT = ''
PASSWORD = ''
SEEDNODES = [
...
]
#
#
try:
keyring = NucypherKeyring.generate(keyring_root=KEYRING_ROOT, password=PASSWORD, checksum_address=ACCOUNT)
except ExistingKeyringError:
keyring = NucypherKeyring(keyring_root=KEYRING_ROOT, account=ACCOUNT)
keyring.unlock(password=PASSWORD)
#
#
from nucypher.characters.lawful import Alice
alice = Alice(keyring=keyring, known_nodes=SEEDNODES, provider_uri=PROVIDER_URI)
alice.start_learning_loop(now=True)
```
=> Character Creation Ease

docs/source/glossary.rst
Also, general cleanup.
Fixes #1403
=> Add "TreasureMap" to the Glossary.

.circleci/config.yml
See https://github.com/pypa/pip/issues/4537#issuecomment-373386803
=> Adiós, dependency conflicts! 👋

nucypher/characters/chaotic.py, nucypher/cli/characters/moe.py, nucypher/crypto/api.py, nucypher/keystore/keypairs.py, nucypher/network/status_app/moe.py, nucypher/network/status_app/templates/moe.html
=> Moe self-signed certificate for HTTPS + WSS

nucypher/characters/chaotic.py, nucypher/cli/characters/moe.py, nucypher/network/status_app/moe.py
Some fixes that should make the loading of Moe's web page much more reasonable.
=> Ensure tls websocket is subscribed to state and node events

nucypher/blockchain/eth/actors.py, nucypher/cli/characters/stake.py
=> Re-activate TransactingPower immediately before deploying contracts with ContractAdministrator

nucypher/network/server.py, nucypher/network/templates/basic_status.j2
=> Add staker address to Ursula status page

.circleci/config.yml, scripts/installation/install_solc.sh
Fixes #828 (Needs testing on OSX)
=> Fixes #828 - Allow solc install script to crash instead of report success 

nucypher/blockchain/economics.py, nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/providers.py, nucypher/blockchain/eth/registry.py, nucypher/blockchain/eth/sol/compile.py, nucypher/blockchain/eth/sol/source/contracts/Adjudicator.sol, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/lib/UmbralDeserializer.sol, nucypher/blockchain/eth/token.py, nucypher/config/keyring.py, nucypher/crypto/powers.py, tests/blockchain/eth/entities/actors/test_staker.py
=> After TODO party clean-up 🎉

nucypher/characters/lawful.py, nucypher/cli/painting.py, nucypher/crypto/utils.py, nucypher/keystore/db/models.py, nucypher/keystore/keystore.py, nucypher/network/middleware.py, nucypher/network/server.py, nucypher/policy/collections.py, tests/characters/test_bob_handles_frags.py, tests/keystore/test_keystore.py
=> Excavate Re-encryption logic; WorkOrder Datastore Models

nucypher/cli/actions.py, nucypher/cli/characters/alice.py, nucypher/cli/characters/bob.py, nucypher/network/teachers.py
Follow up for accidentally merged commits in #1494
=> Static Nodes from Disk

nucypher/network/protocols.py
=> Workaround for urlparse problem

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/token.py, nucypher/cli/actions.py, nucypher/cli/characters/alice.py, nucypher/cli/characters/bob.py, nucypher/cli/characters/stake.py, nucypher/cli/characters/ursula.py, nucypher/cli/painting.py, nucypher/config/base.py, nucypher/config/node.py, nucypher/utilities/logging.py, tests/cli/ursula/test_federated_ursula.py, tests/config/test_base_configuration.py, tests/config/test_character_configuration.py, tests/conftest.py
Fixes #1270, #1375, #1231, #1243, #859, #1233, #1154, #835, #1260, #1460  out of the Incentivized Testnet Milestone.
=> Improves Staking UX via CLI; Many Bug Fixes

nucypher/cli/characters/stake.py
Related to my comment in #1536 : https://github.com/nucypher/nucypher/pull/1536#discussion_r359909349
and subsequent discussion in discord:
https://discordapp.com/channels/411401661714792449/411401661714792451/662402385276305458
=> Modify allowed value range for divide cli prompt

nucypher/cli/actions.py, nucypher/cli/characters/felix.py, nucypher/cli/characters/stake.py, tests/cli/test_alice.py, tests/cli/test_bob.py, tests/cli/test_felix.py, tests/cli/ursula/test_run_ursula.py, tests/cli/ursula/test_stakeholder_and_ursula.py, tests/config/test_character_configuration.py
=> Incorrect recommendation for missing StakeholderConfiguration file

nucypher/cli/characters/alice.py, nucypher/cli/characters/stake.py, nucypher/cli/deploy.py
Fix-up a mistake made in PR #1434
=> Fix some minor bugs introduced by PR1434

nucypher/blockchain/eth/utils.py
Thanks to @michwill and @vzotova for the solution!
=> Fixes #1435 - Rethink datetime to period utils.

docs/source/guides/staking_guide.rst, nucypher/characters/control/interfaces.py, nucypher/characters/control/serializers.py, nucypher/characters/lawful.py, nucypher/cli/actions.py, nucypher/cli/commands/alice.py, nucypher/cli/commands/deploy.py, nucypher/cli/commands/status.py, nucypher/cli/commands/ursula.py, nucypher/cli/options.py, nucypher/config/constants.py, nucypher/policy/collections.py, nucypher/policy/policies.py, tests/cli/test_alice.py, tests/cli/test_cli_lifecycle.py, tests/cli/test_felix.py, tests/cli/test_mixed_configurations.py, tests/cli/ursula/test_federated_ursula.py, tests/cli/ursula/test_run_ursula.py
=> Adds support to --rate when granting, tweaks to the Staking Guide, and other beasts

nucypher/characters/chaotic.py, nucypher/cli/commands/felix.py, tests/cli/test_felix.py
Using this branch to test and stage felix, currently running as the NuBot Faucet backend.
=> Felix Update and Staging

nucypher/blockchain/eth/agents.py, nucypher/characters/lawful.py, nucypher/cli/commands/ursula.py, nucypher/config/storages.py, nucypher/network/nodes.py, nucypher/utilities/metrics.py
- Adjustments for compatibility with nucypher-monitor
- a little code reorg 
- new agent method: `missing_periods`
- optional Ursula metrics endpoint (prometheus format) with `--metrics`
=> Basic Prometheus Exporter & Monitoring Adjustments

.bumpversion.cfg, docs/source/conf.py, nucypher/__about__.py
Publication build: <https://circleci.com/workflow-run/850059a1-d5bf-411e-86cf-d598396beef9>
=> [Release] Bump version: 2.0.0-beta.0 → 2.0.0-beta.1

.bumpversion.cfg, docs/source/conf.py, nucypher/__about__.py
Publication Build: <https://circleci.com/workflow-run/c381e3d0-afbd-414c-b5dd-9ac782dddc35>
=> [Release] Bump version: 2.0.0-beta.1 → 2.0.0-beta.2

docs/source/guides/installation_guide.md, docs/source/index.rst, docs/source/support/community.rst, docs/source/support/faq.rst, docs/source/support/troubleshooting.rst
Community Resources, Troubleshooting and FAQ.
=> Initial Support docs

nucypher/cli/actions.py
I was following the steps from Phase 2 and noticed that the winddown text was a bit cluttered. I did **not** modify the text, just the spacing.
@vzotova - I assume the existing text still holds after #1652 .
=> Winding down agreement was a bit cluttered

nucypher/network/middleware.py, nucypher/network/nodes.py
=> Todo party

nucypher/cli/commands/alice.py
Fixes #1682
Also `grant()` now uses `m` and `n` from the schema, and not from the config - seems more logical to me, and they are already present there.
=> Extract options used only by alice-init and alice-config in a separate option group

nucypher/blockchain/eth/actors.py, nucypher/cli/commands/stake.py, nucypher/cli/commands/worklock.py
=> Hotfix: Allow to create transacting WorkLock bidders with HW wallets (Fixes #1721)

nucypher/blockchain/eth/interfaces.py, nucypher/cli/commands/deploy.py, tests/cli/test_bob.py, tests/fixtures.py
Ensure then entire test suite can be run at once.
=> Keep master passing

docs/source/guides/installation_guide.md, docs/source/guides/staking_guide.rst, docs/source/guides/ursula_configuration_guide.rst, docs/source/support/faq.rst
Variety of updates to the docs:
-  [x] Fixes #1616
-  [x] Fixes #1619
-  [x] Fixes #1600
-  [x] Fixes #1596
-  [x] Fixes #1604 
-  [x] Fixes #1594
Related to #1414, #829
=> Documentation Blitz

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, nucypher/cli/commands/alice.py, nucypher/cli/commands/deploy.py, nucypher/cli/commands/stake.py, nucypher/cli/commands/status.py, nucypher/cli/painting.py, tests/blockchain/eth/contracts/main/policy_manager/test_policy_manager.py, tests/blockchain/eth/entities/actors/test_deployer.py, tests/blockchain/eth/entities/actors/test_staker.py, tests/blockchain/eth/entities/agents/test_policy_manager_agent.py, tests/blockchain/eth/entities/deployers/test_policy_manager_deployer.py, tests/cli/test_deploy_commands.py, tests/cli/test_status.py, tests/cli/ursula/test_stakeholder_and_ursula.py, tests/fixtures.py
Refs #1567 
Fixes #1021
Opens #1709
* reward rate range set by admin
* multiple CLI commands to control min rate and reward range
=> [DO NOT MERGE YET] Reward rate range

.bumpversion.cfg, docs/source/conf.py, nucypher/__about__.py
Publication Build: <https://circleci.com/workflow-run/7775bf27-0ce9-4f8d-831f-5dc869786cf5>
=> Bump version: 2.0.0-beta.8 → 2.0.0-beta.9

.bumpversion.cfg, docs/source/conf.py, nucypher/__about__.py
Publication build: <https://circleci.com/workflow-run/4108ad4d-cf36-4494-b5c6-e03d1128dedf>
=> Bump version: 2.0.0-beta.9 → 2.0.0-beta.10

.bumpversion.cfg, docs/source/conf.py, nucypher/__about__.py
Publication Build: <https://circleci.com/workflow-run/0ecf0857-8ec0-4e56-b421-57fc1855e82d>
=> Bump version: 2.0.0-beta.10 → 2.0.0-beta.11

docs/source/support/faq.rst
https://github.com/nucypher/nucypher/blob/ravital-faq/docs/source/support/faq.rst
=> Documentation - Update FAQ support

docs/source/guides/network_node/ursula_configuration_guide.rst, nucypher/config/keyring.py
Related to https://github.com/nucypher/nucypher/commit/891dd04d2ae8f9d25ea0ae3861d5839542b14851#diff-9baeffadd2f996b1479a4332a067fa0d
=> Remove in docs staker address flag from ursula init

nucypher/blockchain/eth/sol/source/contracts/WorkLock.sol, tests/blockchain/eth/contracts/main/worklock/test_worklock.py
=> Manual shutdown for worklock

deploy/ansible/azure/README.md, deploy/ansible/azure/deploy_nucypher_azure_infra.yml, deploy/ansible/azure/inventory.yml
With guidance from damonC, I've created the following tutorial, ansible playbook, and inventory to allow the Nucypher community to rapidly deploy staker/worker infrastructure to the Azure cloud.
The playbook configure Azure resources including: virtual network, network configuration, and virtual machines. Including specific configuration such as open ports required for Nucypher communication.
=> Deploying Nucypher Infrastructure to Azure

nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/sol/source/contracts/Issuer.sol, nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol, tests/blockchain/eth/contracts/base/test_issuer.py, tests/blockchain/eth/contracts/integration/test_intercontract_integration.py, tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow.py, tests/blockchain/eth/entities/deployers/test_deploy_idle_network.py, tests/metrics/estimate_gas.py
* Changes life cycle of `StakingEscrow`: now almost everything is possible before activation except `confirmActivity`
* Method to deposit for many stakers and many sub-stakes in one tx
=> StakingEscrow pre-allocations

Pipfile.lock, dev-requirements.txt, nucypher/characters/chaotic.py, nucypher/characters/control/controllers.py, nucypher/config/constants.py, nucypher/datastore/keypairs.py, nucypher/network/server.py, nucypher/utilities/sandbox/middleware.py, requirements.txt, scripts/installation/relock_dependencies.sh, tests/cli/test_mixed_configurations.py, tests/network/test_failure_modes.py
closes https://github.com/nucypher/nucypher/issues/1743
=> Limit data size posted to Nucypher nodes to 50k

docs/source/index.rst
Related to #1806 (https://github.com/nucypher/nucypher/pull/1806#issuecomment-606233155) and https://github.com/nucypher/mining-paper/pull/3
=> Update link to 2-phase economics document

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/AbstractStakingContract.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PreallocationEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/StakingInterface.sol, tests/blockchain/eth/contracts/contracts/StakingContractsTestSet.sol, tests/blockchain/eth/contracts/integration/test_intercontract_integration.py, tests/blockchain/eth/contracts/main/staking_contracts/conftest.py, tests/blockchain/eth/contracts/main/staking_contracts/test_preallocation_escrow.py, tests/blockchain/eth/contracts/main/staking_contracts/test_staking_interface.py, tests/blockchain/eth/contracts/main/staking_contracts/test_staking_interface_router.py, tests/blockchain/eth/entities/agents/test_preallocation_escrow_agent.py, tests/cli/ursula/test_stake_via_allocation_contract.py
This PR is preparation for "pooling contract" PR
Attempt to make `PreallocationEscrow` just as an example of a staking contract
* `WorkLock` methods in `StakingInterface`
* Updates for `AbstractStakingContract`
* Refactoring for tests
Versions:
`StakingInterface` : `v1.3.1` -> `v1.4.1`
=> Staking contracts updates

nucypher/blockchain/eth/actors.py, nucypher/characters/base.py, nucypher/characters/lawful.py, nucypher/cli/actions.py, nucypher/cli/commands/stake.py, nucypher/cli/commands/ursula.py, nucypher/cli/options.py, nucypher/cli/painting.py, nucypher/config/characters.py, nucypher/config/node.py, nucypher/config/storages.py, nucypher/network/middleware.py, nucypher/network/nicknames/__init__.py, nucypher/network/nodes.py, nucypher/network/sensors.py, nucypher/network/server.py
Fixes several regressions introduced in #1462 and #1697 
Advances fixes for https://github.com/nucypher/nucypher/issues/1698, #1823, and #1820 
Tested in live production environment.
=> Bug fixes for Ursula: availability sensor, cert/stamp verification, nicknames

Pipfile, Pipfile.lock, dev-requirements.txt, requirements.txt
=> Relock Deps

deploy/ansible/worker/README.md, deploy/ansible/worker/get_workers_status.yml, deploy/ansible/worker/include/check_running_ursula.yml, deploy/ansible/worker/include/init_ursula.yml, deploy/ansible/worker/include/init_worker.yml, deploy/ansible/worker/include/run_geth.yml, deploy/ansible/worker/include/run_ursula.yml, deploy/ansible/worker/include/setup_docker.yml, deploy/ansible/worker/include/setup_user.yml, deploy/ansible/worker/include/update_existing_ursula.yml, deploy/ansible/worker/inventory.yml, deploy/ansible/worker/setup_remote_workers.yml, deploy/ansible/worker/update_remote_workers.yml
cleans up some documentation and examples,
removes default variable for hosts
removes STAKER_ADDRESS as required argument
removes confirmation of bonding as requirement for deployment
=> Gemini ansible worker deploy tweaks

docs/source/guides/network_node/staking_guide.rst
Introduction of external signing documentation focused on clef and the staking CLI.
=> External signer documentation for staking CLI

nucypher/blockchain/eth/actors.py, nucypher/characters/lawful.py, nucypher/cli/actions.py, nucypher/cli/painting.py, nucypher/cli/processes.py, nucypher/network/middleware.py, nucypher/network/nodes.py, nucypher/network/sensors.py, nucypher/network/trackers.py, tests/cli/ursula/test_federated_ursula.py, tests/conftest.py, tests/network/test_availability.py
=> Availability sensor bug fixes and Improvements

scripts/circle/run_finnegans_wake_demo_docker-circle.sh, scripts/circle/run_heartbeat_demo_docker-circle.sh
=> Fix failed examples tests on CI

tests/blockchain/eth/contracts/contracts/LibTestSet.sol, tests/blockchain/eth/contracts/lib/test_reencryption_validator.py
Fixes #954
Not possible to do before solidity 0.6
=> Test ReEncryptionValidator library constants 

docs/source/guides/deployment_guide.rst, docs/source/guides/development/cli_guide.rst, docs/source/guides/network_node/ursula_configuration_guide.rst, docs/source/guides/worklock_guide.rst, nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/interfaces.py, nucypher/cli/actions.py, nucypher/config/node.py, scripts/hooks/nucypher_agents.py
=> Autodetect POA

nucypher/blockchain/eth/sol/__conf__.py, nucypher/blockchain/eth/sol/source/contracts/Adjudicator.sol, nucypher/blockchain/eth/sol/source/contracts/Issuer.sol, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/AbstractStakingContract.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PreallocationEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/StakingInterface.sol, tests/blockchain/eth/contracts/contracts/AdjudicatorTestSet.sol, tests/blockchain/eth/contracts/contracts/IssuerTestSet.sol, tests/blockchain/eth/contracts/contracts/PolicyManagerTestSet.sol, tests/blockchain/eth/contracts/contracts/StakingContractsTestSet.sol, tests/blockchain/eth/contracts/contracts/StakingEscrowTestSet.sol, tests/blockchain/eth/contracts/contracts/WorkLockTestSet.sol, tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow_additional.py
Fixes #1845
| WARNING: Not upgradeable changes |
| --- |
=> Immutable fields in contracts

docs/source/index.rst, docs/source/support/faq.rst, docs/source/support/node_providers.rst
=> Add list of node-as-a-service providers

.bandit, .flake8, .pre-commit-config.yaml, Pipfile, Pipfile.lock, dev-requirements.txt, docs/source/guides/installation_guide.md, nucypher/cli/actions.py, nucypher/cli/main.py, requirements.txt, scripts/hooks/validate_circleci_config.sh
`pip install nucypher -e . -r dev-requirements`
`pre-commit install`
`pre-commit run --all-files`
Pre-commit hooks will execute on commits automatically preventing commit on failure.  This can be disabled in a few ways, to name a few: 
- `PRE_COMMIT_ALLOW_NO_CONFIG=1 git commit ...`
- `git commit ... --no-verify`
```
(nucypher) kieran@pegasus:~/Git/nucypher$ git commit -m "Pre-hook configuration; Includes bandit setup and custom circleCI checker."
Don't commit to branch...................................................Passed
Forbid new submodules....................................................Passed
Check for byte-order marker..............................................Passed
Check that executables have shebangs.....................................Passed
Check for added large …
```
=> Introduce Pre-Commit Framework

nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/utils.py, nucypher/cli/actions.py, nucypher/cli/options.py, nucypher/utilities/sandbox/constants.py, tests/blockchain/eth/clients/test_geth_integration.py, tests/blockchain/eth/interfaces/test_chains.py
Fixes #1777  #1185  
Advances #1504
=> Verify consistent ownership during deployment; Handle Insufficient funds TX failure.

docs/requirements.txt, docs/source/guides/contribution_guide.rst, docs/source/support/node_providers.rst, setup.py
=> Random update to docs: update link to node providers, building docs

Makefile, docs/Makefile, docs/source/conf.py
=> Fix for Autodoc build on ReadTheDocs

docs/source/guides/environment_variables.rst, docs/source/guides/installation_guide.rst, docs/source/index.rst
=> Document nucypher environment variables

docs/source/guides/network_node/ursula_configuration_guide.rst
Related to #1583 ,  #1923 
Fixes #1634
=> Document Ursula Monitoring (Status and Prometheus)

nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/signers.py, tests/blockchain/eth/clients/test_keystore_signer.py, tests/cli/ursula/test_ursula_local_keystore_cli_integration.py, tests/fixtures.py
Fixes #1962; Advances (possibly fixes) #1861 #1859 
Additional testing for keystore signer filesystem integration.
=> Bug Fixes: WSS Provider, Keystore file Handling

tests/cli/conftest.py, tests/cli/test_mixed_configurations.py, tests/cli/ursula/test_ursula_local_keystore_cli_integration.py
Responds to CI failure during release: <https://app.circleci.com/pipelines/github/nucypher/nucypher/4543/workflows/6228719f-1079-48d9-9ccf-01679b8cf292>
=> Fixes mixed configuration test inaccuracy

docs/source/guides/development/cli_guide.rst, docs/source/guides/development/getting_started.rst, docs/source/guides/ethereum_node.rst, docs/source/guides/network_node/staking_guide.rst, docs/source/guides/network_node/ursula_configuration_guide.rst, docs/source/guides/worklock_guide.rst, docs/source/index.rst, docs/source/support/faq.rst
=> Documentation of running ETH node and using clef

nucypher/blockchain/economics.py
=> Proposal: set slashing coefficients to almost zero

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/token.py, tests/blockchain/eth/entities/actors/test_worker.py
This PR proves that CA is called only once on start up then once period.
Advances #2002 
Co-Author: @cygnusv
=> Test reproducing double CA bug and Fix 1/2 of (#2002)

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/cli/commands/worklock.py, nucypher/cli/literature.py, tests/blockchain/eth/entities/agents/test_worklock_agent.py, tests/cli/functional/conftest.py, tests/cli/functional/test_worklock_cli_functionality.py, tests/cli/test_worklock_cli.py
=> Estimate number of bidders, functional test for enable-claiming

docs/source/architecture/contracts.rst, docs/source/guides/development/getting_started.rst, docs/source/guides/installation_guide.rst
=> Fix broken links in docs.

docs/source/guides/ethereum_node.rst, nucypher/blockchain/eth/signers.py
=> Add documentation for local Keystore signer

Makefile, docs/Makefile, docs/source/architecture/contracts.rst, docs/source/conf.py, docs/source/glossary.rst, docs/source/guides/development/cli_guide.rst, docs/source/guides/development/getting_started.rst, docs/source/guides/environment_variables.rst, docs/source/guides/ethereum_node.rst, docs/source/guides/installation_guide.rst, docs/source/guides/network_node/staking_guide.rst, docs/source/guides/network_node/ursula_configuration_guide.rst, docs/source/guides/worklock_guide.rst, docs/source/index.rst, docs/source/support/faq.rst, docs/source/support/troubleshooting.rst, nucypher/blockchain/eth/signers.py, readthedocs.yml
**Chaperone: @derekpierre**
**Goals:**
* Documentation needed before activating StakingEscrow
**Fixes:**
Related to #2038 (merged into master directly)
**Ramp Order:**
=> [EPIC] Kerabatsos - Documentation Before Mainnet

.circleci/config.yml, nucypher/cli/actions/select.py, nucypher/cli/commands/worklock.py, nucypher/cli/literature.py, tests/integration/cli/test_worklock_cli_functionality.py
* Increases WL command coverage in 11%, reaching almost 97% (Fixes #2035)
* Fix small bug in WorkLock. This unit testing effort was worth it!
* Fix wrong configuration of sampling statistical test in nightly CI build
=> Increase worklock command coverage to ~97%

docs/source/architecture/contracts.rst
=> Small updates in contract docs

nucypher/cli/commands/ursula.py, nucypher/cli/processes.py, tests/acceptance/cli/test_help.py, tests/acceptance/cli/ursula/test_ursula_command.py
=> Hide 'commit-next' from help messages

nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/token.py, nucypher/cli/commands/deploy.py, nucypher/cli/commands/status.py, tests/acceptance/blockchain/interfaces/test_chains.py, tests/fixtures.py, tests/mock/interfaces.py, tests/unit/test_block_confirmations.py, tests/utils/blockchain.py
=> Improve block confirmation logic and tests

nucypher/cli/literature.py, nucypher/cli/painting/worklock.py, nucypher/cli/utils.py
* Removed duplicated connection to the blockchain
* Added WL address to `nucypher worklock status`
* Introduce some emojis to WL command output 👯
=> Minor enhancements to WorkLock command

nucypher/characters/lawful.py, nucypher/cli/commands/ursula.py, nucypher/utilities/prometheus/collector.py, nucypher/utilities/prometheus/metrics.py
=> Ensure that prometheus imports are locally scoped

docs/source/guides/network_node/staking_guide.rst, docs/source/support/faq.rst, nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/cli/commands/stake.py, nucypher/cli/literature.py, nucypher/types.py, tests/acceptance/blockchain/actors/test_staker.py, tests/acceptance/blockchain/agents/test_staking_escrow_agent.py, tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py, tests/integration/cli/test_stake_cli_functionality.py, tests/integration/cli/test_worklock_cli_functionality.py, tests/integration/conftest.py, tests/mock/agents.py
=> `mint` command + minor updates for `collect-reward` in CLI

nucypher/utilities/prometheus/collector.py, nucypher/utilities/prometheus/metrics.py
=> Ensure Prometheus metric for CommitmentMade is correctly updated on startup

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/deployers.py, nucypher/blockchain/eth/sol/source/contracts/Issuer.sol, nucypher/cli/commands/deploy.py, nucypher/cli/literature.py, tests/acceptance/blockchain/agents/test_sampling_distribution.py, tests/acceptance/blockchain/agents/test_staking_escrow_agent.py, tests/acceptance/cli/test_deploy.py, tests/contracts/base/test_issuer.py, tests/contracts/integration/test_contract_economics.py, tests/contracts/integration/test_intercontract_integration.py, tests/contracts/main/staking_escrow/test_staking.py, tests/contracts/main/staking_escrow/test_staking_escrow.py, tests/contracts/main/staking_escrow/test_staking_escrow_additional.py
A very minor change to allow the DAO agent to activate the contract without giving tokens to it.
=> [The Royal We] Allow StakingEscrow initialization from a separate funding source

docs/source/guides/network_node/staking_guide.rst, nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/token.py, nucypher/cli/commands/stake.py, nucypher/cli/literature.py, nucypher/cli/painting/staking.py, tests/acceptance/blockchain/actors/test_staker.py, tests/acceptance/blockchain/agents/test_staking_escrow_agent.py, tests/acceptance/blockchain/interfaces/test_token_and_stake.py, tests/acceptance/characters/test_stakeholder.py, tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py, tests/integration/blockchain/test_token_and_stake.py, tests/integration/cli/test_stake_cli_functionality.py, tests/integration/conftest.py
Refs #1766
* Extract tx and validation from `Stake` class
* New methods in `StakingEcrowAgent` to cover *new* functions in contract 
* `Increase` method in `Staker`
* `increase` command in CLI
* More tests...🧟‍♀️
=> Command to increase stake and small refactoring for `Stake` class

docs/source/guides/network_node/staking_guide.rst, nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/token.py, nucypher/cli/actions/select.py, nucypher/cli/commands/stake.py, nucypher/cli/literature.py, tests/acceptance/blockchain/actors/test_staker.py, tests/acceptance/blockchain/agents/test_staking_escrow_agent.py, tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py, tests/integration/blockchain/test_token_and_stake.py, tests/integration/cli/actions/test_select_stake.py, tests/integration/cli/test_stake_cli_functionality.py
Fixes #1766
Fixes #2015 
Fixes #2065
=> `create`/`increase`: flag to use unlocked tokens, `merge` command in `stake`

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/multisig.py, nucypher/blockchain/eth/registry.py, nucypher/blockchain/eth/token.py, nucypher/cli/commands/stake.py, nucypher/cli/commands/status.py, nucypher/cli/literature.py, nucypher/cli/painting/staking.py, nucypher/cli/painting/status.py, nucypher/cli/processes.py, tests/acceptance/blockchain/agents/test_contract_agency.py, tests/acceptance/cli/test_status.py, tests/acceptance/cli/ursula/test_stake_via_allocation_contract.py, tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py, tests/integration/cli/test_stake_cli_functionality.py, tests/unit/test_registry_basics.py
Fixes #2114
Fixes #1739
Fixes #1436
Fixes #2066
Fixes #1545
=> Few more fixes for `staker`

Makefile, docs/source/guides/contribution_guide.rst, docs/source/guides/installation_guide.rst, nucypher/cli/literature.py, scripts/circle/compare_reqs.sh
=> Random documentation improvements

docs/source/architecture/worklock.rst
The values used in the examples can be modified at a later date, since it takes time to determine good values for the scenarios. As a stop-gap, I will overly highlight the `hypothetical` nature of the examples even more, until I can work through some examples with actual values.
Updated page:
=> Further reinforce hypothetical nature of WorkLock example scenarios

docs/source/architecture/worklock.rst
**NOTE:** Of course, minimum escrow will fluctuate based on ETH/USD rate so that remains hypothetical.
=> Modify WorkLock properties/values to be more closely related to actual limits

nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PoolingStakingContract.sol, nucypher/blockchain/eth/sol/source/zeppelin/ownership/Ownable.sol, tests/contracts/main/staking_contracts/conftest.py, tests/contracts/main/staking_contracts/test_pooling_contract.py
Refs #1674
Consider this PR as starting point for pooling contract
Opens #2202
=> First iteration of pooling contract

docs/source/guides/ethereum_node.rst
=> Add geth version requirements to clef documentation

docs/source/guides/network_node/staking_guide.rst, nucypher/blockchain/eth/actors.py, nucypher/cli/actions/confirm.py, nucypher/cli/commands/stake.py, nucypher/cli/literature.py, nucypher/cli/painting/staking.py, nucypher/cli/painting/status.py, tests/acceptance/blockchain/actors/test_staker.py, tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py, tests/constants.py
=> Stake command to control snapshots flag

tests/integration/conftest.py
=> Add thread lock to MockLMDB

nucypher/network/nodes.py
This PR is motivated by reducing the number of calls nucypher/nucypher-monitor needs to make to ethereum clients when operating as a `Crawler(Learner)`.
=> Allow learners to explicity opt out of verifying stranger bonding

nucypher/characters/lawful.py, nucypher/config/characters.py
=> Don't run availability checks by default

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/sol/__conf__.py, nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PoolingStakingContract.sol, nucypher/cli/commands/deploy.py, nucypher/cli/literature.py, tests/acceptance/blockchain/actors/test_deployer.py, tests/acceptance/blockchain/agents/test_staking_escrow_agent.py, tests/acceptance/cli/test_deploy_commands.py, tests/contracts/integration/test_intercontract_integration.py, tests/contracts/main/staking_escrow/test_staking_escrow.py, tests/metrics/estimate_gas.py
Basically removes changes by #2191
=> Remove force re-stake lock

docs-requirements.txt
=> Equalize dependency versions with nucypher requirements.

docs/source/demos/finnegans_wake_demo.rst, docs/source/demos/heartbeat_demo.rst, docs/source/demos/local_fleet_demo.rst, docs/source/guides/ethereum_node.rst, docs/source/guides/installation_guide.rst, examples/finnegans_wake_demo/README.md, examples/heartbeat_demo/heartbeat_demo.md
=> Docs Update

nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol, tests/contracts/integration/test_intercontract_integration.py, tests/contracts/main/staking_escrow/test_staking_escrow.py
=> StakingEscrow: enable wind down for claim from worklock

docs/source/guides/installation_guide.rst, docs/source/guides/network_node/ursula_configuration_guide.rst
=> Document operational requirements for Worker node.

nucypher/config/storages.py, nucypher/crypto/api.py, nucypher/network/nodes.py, nucypher/network/server.py, nucypher/network/trackers.py
=> Fixes for #1820 - Handle invalid node certificates (storage and discovery)

nucypher/network/nodes.py, nucypher/network/server.py, nucypher/network/templates/basic_status.j2, nucypher/utilities/prometheus/collector.py, tests/integration/learning/test_fleet_state.py
* Fix missing domain in Ursula's status page and JSON
* Restore lost commits from #1881 (probably my fault during a rebase)
* Includes the contribution from #2281 , which fixes #1735 by showing it was not true.
* Adds nickname and nickname icon to Prometheus metrics collector (Closes #2310)
=> Blue Oyster Mushrooms aftertaste

docs/source/guides/network_node/ursula_configuration_guide.rst
=> Remove unused <YOUR STAKING ADDRESS> from docker docs (closes #2275)

nucypher/cli/commands/deploy.py, tests/acceptance/cli/deploy/conftest.py, tests/acceptance/cli/deploy/test_deploy_cli.py, tests/acceptance/cli/deploy/test_deploy_cli_commands.py, tests/acceptance/cli/deploy/test_deploy_cli_multisig
Restores 100% passing CI checks on `main`; Closes #2316
=> Fixes #2316; CI timeout for deploy CLI tests

.circleci/pytest.ini, Pipfile, Pipfile.lock, dev-requirements.txt, requirements.txt
https://github.com/pytest-dev/pytest-timeout
=> Pytest-timeout configuration; Dependency relock

nucypher/cli/commands/deploy.py, tests/acceptance/cli/deploy/test_deploy_cli.py
Fixes #2338. Ensure proper testnet check is performed and added a test.
=> Ensure that testnet flag is set correctly for deployer

deploy/ansible/worker/include/check_running_ursula.yml, deploy/ansible/worker/include/init_ursula.yml, deploy/ansible/worker/include/init_worker.yml, deploy/ansible/worker/include/run_geth.yml, deploy/ansible/worker/include/run_ursula.yml, deploy/ansible/worker/include/stop_containers.yml, deploy/ansible/worker/include/update_existing_ursula.yml, deploy/ansible/worker/setup_remote_workers.yml, deploy/ansible/worker/stop_remote_workers.yml, docs/source/guides/network_node/network_node.rst, docs/source/guides/network_node/nucypher_host_management_cli.rst, nucypher/blockchain/eth/actors.py, nucypher/cli/commands/cloudworkers.py, nucypher/cli/commands/workers.py, nucypher/cli/main.py, nucypher/cli/painting/staking.py, nucypher/config/characters.py, nucypher/config/node.py, nucypher/utilities/clouddeploy.py, nucypher/utilities/templates/cloud_deploy_ansible_inventory.j2
`nucypher cloudworkers up —remote-provider https://infura... —cloudprovider digitalocean`
=> Automated cloud deployment for all!

nucypher/blockchain/eth/token.py, tests/acceptance/blockchain/actors/test_worker.py
Not a complete solution, but a mitigation.
=> Sprinkles a little randomness on work tracker intervals

nucypher/cli/commands/cloudworkers.py, nucypher/utilities/clouddeploy.py
* custom per-host SSH hints,
* infer provider if all hosts are the same provider
* bugfix in digital ocean deploy
=> Cloud Deploy UX improvements

docs-requirements.txt
=> Change Jinja version in docs-requirements to match that in other requirements

nucypher/acumen/perception.py, nucypher/characters/unlawful.py, nucypher/network/nodes.py, nucypher/network/server.py, nucypher/policy/policies.py, tests/acceptance/network/test_network_actors.py, tests/utils/middleware.py
Fixes #1714 
Fixes #2186
Fixes #1075 
Adds logs to help track down #2345 / #1698
=> Hibiscus (closure of all remaining jMyles' activation issues)

nucypher/cli/commands/stake.py, tests/integration/cli/test_stake_cli_functionality.py
Discovered during testing - ensure that minimum bid of 15,000 NU is actually allowed.
=> Actually allow minimum stake of 15,000 NU

nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/interfaces.py, nucypher/blockchain/eth/token.py, nucypher/network/nodes.py, nucypher/utilities/datafeeds.py, nucypher/utilities/gas_strategies.py, tests/acceptance/blockchain/actors/test_worker.py, tests/fixtures.py, tests/integration/characters/test_bob_joins_policy_and_retrieves.py, tests/integration/conftest.py, tests/mock/agents.py, tests/unit/test_blockchain_interface.py, tests/unit/test_datafeeds.py, tests/utils/blockchain.py
Advances #2385 and #2370 
Co-Author: @KPrasch
=> Track pending commitment transactions in WorkTracker

nucypher/blockchain/eth/token.py, tests/acceptance/blockchain/actors/test_worker.py, tests/unit/test_work_tracker_error_handling.py
=> restart worker task on fail

docs/source/guides/ethereum_node.rst
=> Documentation for signing with hardware wallets

nucypher/blockchain/eth/sol/source/contracts/Adjudicator.sol, nucypher/blockchain/eth/sol/source/contracts/Issuer.sol, nucypher/blockchain/eth/sol/source/contracts/MultiSig.sol, nucypher/blockchain/eth/sol/source/contracts/NuCypherToken.sol, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol, nucypher/blockchain/eth/sol/source/zeppelin/token/ERC20/ERC20.sol, nucypher/blockchain/eth/sol/source/zeppelin/token/ERC20/SafeERC20.sol
Change relative import path to absolute in contracts
=> Preparation for #2439

newsfragments/2441.bugfix.rst, nucypher/blockchain/eth/token.py, nucypher/cli/commands/stake.py, tests/integration/cli/test_stake_cli_functionality.py
=> Allow arbitrary decimal precision as input to nucypher CLI

docs/source/guides/network_node/staking_guide.rst, newsfragments/2450.feature.rst, nucypher/blockchain/eth/token.py, nucypher/cli/actions/select.py, nucypher/cli/painting/staking.py
* Warns stakers that they have unused substakes. Closes #2449 
* Improves docs of `nucypher stake remove-unused`
* Paint inactive stakes when using `nucypher stake remove-unused`
=> Improve user experience of removing unused substakes (CLI and docs)

nucypher/cli/commands/alice.py
- Include missing network kwarg for Alice account selection
=> Fixes missing network kwarg in Alice CLI

nucypher/blockchain/eth/sol/source/contracts/staking_contracts/AbstractStakingContract.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/CasiPooling.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PoolingStakingContract.sol, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/WorkLockPoolingContract.sol, nucypher/blockchain/eth/sol/source/zeppelin/proxy/Initializable.sol, tests/contracts/contracts/StakingContractsTestSet.sol, tests/contracts/main/staking_contracts/test_staking_interface.py, tests/contracts/main/staking_contracts/test_worklock_pooling_contract.py
Fixes #1674
The contract allows users to delegate liquid tokens and participate in worklock.
Key features:
- Contract owner is multisig wallet
- Each delegator can withdraw ETH or NU at any time
=> Worklock pooling contract

newsfragments/2474.misc.rst, nucypher/blockchain/eth/actors.py, nucypher/cli/actions/configure.py, nucypher/cli/actions/confirm.py, nucypher/cli/commands/stake.py, nucypher/cli/literature.py, nucypher/cli/painting/help.py, nucypher/cli/painting/staking.py, tests/acceptance/blockchain/actors/test_deployer.py, tests/acceptance/cli/test_alice.py, tests/acceptance/cli/test_bob.py, tests/acceptance/cli/test_cli_config.py, tests/acceptance/cli/test_mixed_configurations.py, tests/acceptance/cli/ursula/test_federated_ursula.py
=> Pretty worker & staker console messages

nucypher/characters/unlawful.py
Prevents `Vladimir` from littering in the test folder with its temporary database.
=> Prevent Vladimir from creating a ":memory:" directory

deploy/ansible/worker/include/run_ursula.yml, docs/source/guides/network_node/nucypher_host_management_cli.rst, newsfragments/2475.bugfix.rst, nucypher/cli/commands/cloudworkers.py, nucypher/utilities/clouddeploy.py, nucypher/utilities/templates/cloud_deploy_ansible_inventory.mako
=> Cloudworkers: bugfixes, better cleaner envvar support

.circleci/config.yml, .gitignore, .pre-commit-config.yaml, docs-requirements.txt, docs/source/.static/style.css, docs/source/conf.py, docs/source/contracts_api/index.rst, docs/source/index.rst, newsfragments/2477.doc.rst, scripts/installation/install_solc.py, scripts/solidity_doc/generate_doc.py, setup.py
> High-level idea of the changes introduced in this PR.  
Generates documentation for smart contracts from natspec
None
Fixes #2350
Improves docs. 
We already have descriptions inside contract sources but now it's much more convenient to show/explain how API works
> What should reviewers focus on?
- New resulting htmls for contracts in …
=> Autodoc for smart contracts

docs/source/conf.py, newsfragments/2492.bugfix.rst, scripts/installation/install_solc.py
Added small step in making docs - installation of solidity compiler (if not installed) 
RTD still fails after solidity docs PRs, this PR is trying to fix it
See #2477 and #2489
=> Continued fix rtd build

README.md, docs/source/index.rst, docs/source/support/faq.rst, newsfragments/2520.doc.rst
Makes resource on network fees more accessible 
None
This doesn't address any productdev issues!
None, should be easy to approve!
=> pricing paper on front pages & small faq modification

newsfragments/2551.feature.rst, nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/interfaces.py, nucypher/characters/control/controllers.py, nucypher/characters/control/emitters.py, nucypher/characters/control/specifications/bob.py, nucypher/cli/actions/collect.py, nucypher/cli/actions/confirm.py, nucypher/cli/actions/validate.py, nucypher/cli/commands/alice.py, nucypher/cli/commands/bob.py, nucypher/cli/commands/enrico.py, nucypher/cli/painting/policies.py, nucypher/cli/utils.py, nucypher/policy/policies.py, tests/acceptance/cli/lifecycle.py
Feature 
2
Completes CLI interactivity and parameter collection for CLI usage of Alice, Bob, and Enrico.
The following usages are now supported, all flags are optional:
```
nucypher alice grant
nucypher enrico encrypt
nucypher bob retrieve
```
Improves usability and legibility of grant and retrieve while using the CLI.  This is particularly impactful for application developers  and demo presenters.
=> Completes CLI Interactivity for Grant, Encrypt and Retrieve

newsfragments/2585.misc.rst, nucypher/config/constants.py
Extend probationary period for policy creation to 2021-04-30 23:59:59 UTC.
> - Fixes #...
Fixes #2584 .
Related to #2353 , #2460 
Original probationary period ended on 2021-02-28 23:59:59 UTC.
=> Extend policy probationary period for 2 months to 2021-04-30T23:59:59 UTC

.circleci/config.yml, tests/acceptance/utilities/test_prometheus_collectors.py
Adds testing for prometheus collectors.
> - Fixes #...
Related to #2590 - these tests would have prevented missing that bug.
I don't think we need a newsfragment for this internal change.
=> Tests for prometheus collectors.

newsfragments/2598.bugfix.rst, nucypher/cli/commands/cloudworkers.py
FIxes some minor quality of life issues in cloudworkers commands
=> cloudworkers: small bugfixes

nucypher/blockchain/economics.py, tests/acceptance/blockchain/actors/test_staker.py, tests/acceptance/blockchain/agents/test_worklock_agent.py, tests/acceptance/blockchain/deployers/test_deployers_during_migration.py, tests/acceptance/characters/control/conftest.py, tests/acceptance/characters/control/test_web_control_blockchain.py, tests/acceptance/characters/test_decentralized_grant.py, tests/acceptance/characters/test_freerider_attacks.py, tests/acceptance/characters/test_ursula_prepares_to_act_as_worker.py, tests/acceptance/cli/lifecycle.py, tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py, tests/acceptance/network/test_network_actors.py, tests/contracts/integration/test_contract_economics.py, tests/fixtures.py, tests/integration/blockchain/test_exact_economics_model.py, tests/integration/blockchain/test_token_and_stake_integration.py, tests/metrics/estimate_gas.py, tests/unit/test_blockchain_economics_model.py
Feature
Finalization of period extension.
See #2226, option 2
Based on PR #2549 
Co-Author: @vzotova 
Co-Author: @KPrasch
=> Extended period economics

tests/acceptance/blockchain/agents/test_sampling_distribution.py
Fix nightly test (`test_sampling_distribution`)
=> Fix sampling distribution test

docs/source/architecture/dao.rst, newsfragments/2599.doc.rst
…ting proposal..
Documents requirements for > 60% support, and > 25% approval for DAO voting,.
> - Fixes #...
=> Add documentation about approval / validation requirements for DAO proposals

nucypher/blockchain/eth/token.py
Feature
1
Handles an edge case in work tracker during period increase migration
=> Handle period migration in work tracker

newsfragments/2603.bugfix.rst, nucypher/blockchain/eth/interfaces.py
…load
> Fixes issue introduced by latest geth release.
> - Fixes  #2602 
> Should probably test on a testnet before release.
=> attempt potential fix of #2602 by removing chainID from tx.build_payload

nucypher/cli/commands/stake.py
=> Fixes stake CLI name errors

newsfragments/2614.bugfix.rst, nucypher/cli/actions/collect.py, nucypher/cli/actions/confirm.py, nucypher/cli/commands/alice.py, nucypher/cli/commands/stake.py, nucypher/cli/literature.py, nucypher/cli/painting/staking.py, tests/integration/cli/actions/test_confirm_actions.py, tests/integration/cli/test_stake_cli_functionality.py
The change of period lengths causes some CLI displayed values to be incorrect eg. length of staking
Related to #2594 
=> Updated Period length CLI UX

newsfragments/2596.feature.rst, nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PoolingStakingContractV2.sol, tests/contracts/main/staking_contracts/test_pooling_contract_v2.py
Fix some weak places in pool contract
Next step of improvements for pool contract
Explanation how it works #2597
=> Refinements for pool staking contract

nucypher/characters/lawful.py
- Replaces duplicated logic in `Alice.create_policy()` with call to `super` method `BlockchainPolicyAuthor.create_policy()`.
- Fixes: #2442
- I'm not sure whether this PR covers 100% of the #2442
=> Fix shadowed and unused method

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/cli/commands/stake.py, nucypher/cli/literature.py, tests/acceptance/cli/lifecycle.py
Feature
2
Provides a CLI command for manual period migration.
Provides an action for stakers who have unbonded stakes during period migration who will otherwise be unable to make commitments.
=> Manual migration CLI command

tests/integration/network/test_node_storage.py
Testing Bugfix
1
Mature known nodes before comparing them in test to prevent intermittent failure.
=> Fixes intermittently failing CLI test on CI

nucypher/blockchain/eth/actors.py
=> Correct misnamed kwarg in migrate CLI.

tests/contracts/test_contracts_upgradeability.py
Follow-up Issue https://github.com/nucypher/nucypher/issues/2645
=> Temporary skip for contract upgradeability test

docs/source/staking/running_a_worker.rst, newsfragments/2617.bugfix.rst, newsfragments/2617.feature.rst, nucypher/cli/actions/configure.py, nucypher/cli/actions/select.py, nucypher/cli/commands/alice.py, nucypher/cli/commands/bob.py, nucypher/cli/commands/felix.py, nucypher/cli/commands/ursula.py, nucypher/cli/literature.py, nucypher/cli/painting/help.py, nucypher/config/base.py, nucypher/config/characters.py, tests/acceptance/cli/test_alice.py, tests/acceptance/cli/test_mixed_configurations.py, tests/acceptance/cli/ursula/test_run_ursula.py, tests/integration/cli/actions/test_select_config_file.py, tests/integration/config/test_character_configuration.py
For the CLI, separate generation of CharacterConfiguration from writing the configuration file to disk.
Fixes #1251 
Incorrect configuration filepath being printed to CLI when non-default path used.
=> Ensure that correct config filepath is printed when initializing character

nucypher/cli/commands/stake.py
=> Fix missing str caster in remove-inactive --all painting.

tests/contracts/test_contracts_upgradeability.py
Fix upgradeability test
Fixes #2645
=> Fix upgradeability test

newsfragments/2619.feature.rst, nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol, tests/contracts/main/policy_manager/test_policy_manager.py, tests/metrics/estimate_gas.py
One new function in `PolicyManager` to create multiple policies in one tx
Refs #2508
Decrease gas cost when multiple policies needed with the same parameters
=> Creating multiple policies in one tx

docs/source/architecture/service_fees.rst, newsfragments/2677.doc.rst
Service fee pricing was not updated.
Related to #2610 .
=> Update service fees pricing to reflect 7-day period duration

.circleci/config.yml
- Remove workaround for old (broken) pip version
- Add sanity check to make sure package is importable
- Fixes #2493
- Fixes #2454 
=> Update pip checks in CI

docs/source/support/contribution.rst
- [X ] Documentation
Address issue while running pytest without specifying which test directory
Allows new contributors to successfully run a subset of tests
Review of adding `__init__.py` to respective test directories if need.
=> Update suggested pytest command to target unit tests

deploy/docker/porter/docker-compose.yml
Docker compose for Porter service. Based over #2720 .
Fixes #2669
=> Porter Docker

newsfragments/README.md
… text.
Simple update to newsfragment README.
=> Update newsfragment README file to include 'removal' type

nucypher/policy/maps.py, tests/metrics/estimate_gas.py
- Fix the issue with `__new__` not being called quickly enough and not populating the `_splitters` objects.
- Fix the issue with POLICY_ID_LENGTH in `estimate_gas`
=> Fix TreasureMap splitter dict population bug

docs/source/.static/img/porter_diagram.svg, docs/source/application_development/porter.rst, docs/source/glossary.rst, docs/source/index.rst, docs/source/support/contribution.rst, nucypher/cli/commands/porter.py
Initial documentation of Porter. Based over #2726  .
Related to #2670 .
Build artifact available here - https://136953-100446516-gh.circle-artifacts.com/0/docs/build/html/application_development/porter.html.
This is an initial writeup of already implemented functionality up to "basic authentication" (#2726 ). `/revoke` and `/exec_work_order` APIs haven't been implemented as yet.
I would like to also add some application-specific documentation about specifics of using Porter aside from just stating the API. I intend to add this in separate PRs.
One mistake I made is doing documentation as a separate task, instead of providing a simple base document and then adding to the document as …
=> Initial Porter Documentation

.circleci/config.yml, deploy/docker/porter/Dockerfile, deploy/docker/porter/docker-compose.yml, docs/source/application_development/porter.rst
Based over #2732 .
Related to #2669 , #2724 .
We need to publish a docker image for porter specifically.
=> Publish Porter docker image

docs/source/application_development/porter.rst, nucypher/control/controllers.py, nucypher/control/specifications/fields/base.py, nucypher/utilities/porter/control/specifications/porter_schema.py, tests/acceptance/porter/control/test_porter_web_control_blockchain.py, tests/integration/porter/control/test_porter_web_control_federated.py, tests/integration/porter/test_porter_specifications.py, tests/unit/test_control.py, tests/unit/test_porter.py
Closes https://github.com/nucypher/nucypher/issues/2735.
@derekpierre what do you think? I think it solves all our problems.
=> Allow query parameters to be passed in the URL

.bumpversion.cfg, docs/source/conf.py, docs/source/release_notes/releases.rst, nucypher/__about__.py, nucypher/utilities/gas_strategies.py, tests/unit/test_datafeeds.py
Related to #2769 .
No newsfragment necessary, already incorporated as part of original hotfix, and updated releases page.
**For reviewers**
Is this the best way to reconcile with `tags/v5.3.1`?
=> Include changes and release notes from v5.3.1 hotfix in `main`

Pipfile, Pipfile.lock, dev-requirements.txt, docs-requirements.txt, examples/heartbeat_demo/doctor_keys.py, newsfragments/2798.misc.rst, nucypher/characters/base.py, nucypher/crypto/keystore.py, nucypher/crypto/powers.py, nucypher/crypto/tls.py, nucypher/crypto/umbral_adapter.py, requirements.txt, setup.py, tests/acceptance/cli/ursula/test_local_keystore_integration.py, tests/contracts/lib/test_signature_verifier.py, tests/contracts/lib/test_umbral_deserializer.py, tests/integration/blockchain/test_keystore_signer_filesystem_integration.py, tests/integration/cli/test_ursula_local_keystore_cli_functionality.py, tests/unit/crypto/test_keystore.py, tests/unit/test_datafeeds.py, tests/unit/test_web3_signers.py
- Other
- 2
Updates the usage of Umbral, bumps its version to 0.3 and relocks dependencies.
=> Updates for Umbral 0.3

newsfragments/2785.bugfix.rst, nucypher/blockchain/eth/events.py, nucypher/utilities/prometheus/collector.py, nucypher/utilities/prometheus/metrics.py
Investigation of potential prometheus memory issues.
*For reviewers*
It would be great if someone with a worklock allocation could run their node briefly with prometheus to ensure the worklock collectors work appropriately - worklock collectors are not tested on testnets.
=> Prometheus Memory

docs/source/release_notes/releases.rst, newsfragments/2810.bugfix.rst, newsfragments/2810.misc.rst, newsfragments/2826.bugfix.rst, nucypher/acumen/perception.py, nucypher/network/nodes.py, nucypher/network/server.py, tests/acceptance/characters/test_freerider_attacks.py, tests/acceptance/learning/test_fault_tolerance.py, tests/acceptance/network/test_network_actors.py
Redid changes from #2820 over the tags/v5.3.2 branch in order to allow for a 5.3.3 release.
Originally authored by @fjarri .
Related to #2820 
There are many conflicts trying to cherry-pick changes from #2820 onto 5.3.2.
=> Fix Ursula Memory Leak Issue (v5.3.3 Candidate)

newsfragments/2838.feature.rst, nucypher/blockchain/eth/sol/source/contracts/PREApplicationStub.sol, nucypher/blockchain/eth/sol/source/contracts/SimplePREApplication.sol, tests/contracts/contracts/PREApplicationTestSet.sol, tests/contracts/contracts/StakingEscrowTestSet.sol, tests/contracts/main/application/conftest.py, tests/contracts/main/application/test_worker.py
- Feature
- 3
PRE application with simplified logic (worker configuration)
Based on #2825
=> Simple PRE application

nucypher/blockchain/eth/contract_registry/mumbai/contract_registry.json
=> Updated SubscriptionManager registry for mumbai

docs/source/pre_application/node_providers.rst, docs/source/pre_application/overview.rst, docs/source/support/faq.rst
Add to the existing Threshold Network merger section of the FAQ.
=> Augment FAQ for Threshold Network merger

.circleci/config.yml, .github/workflows/pr_release_note_entry.yml
=> CI for development branch

.bumpversion.cfg, docs/source/conf.py, nucypher/__about__.py
=> Bump version: 5.3.3 → 6.0.0-rc

newsfragments/2909.misc.rst, nucypher/cli/actions/validate.py, nucypher/cli/commands/alice.py, nucypher/cli/commands/bob.py, nucypher/cli/commands/contacts.py, nucypher/cli/commands/deploy.py, nucypher/cli/commands/porter.py, nucypher/cli/commands/status.py, nucypher/cli/commands/ursula.py, nucypher/control/emitters.py
Adds for color to the nucypher cli output, especially when `BadOptionUsage` are hit
=> Add more color to nucypher cli output, fixes #1150

.github/workflows/darker.yml, .pre-commit-config.yaml, newsfragments/2921.misc.rst
Add a pre-commit hook and github action for [Darker](https://github.com/akaihola/darker) to ensure all future changes conform to black and isort.
=> Add a pre-commit hook and github action for Darker

.circleci/config.yml, newsfragments/2932.misc.rst, setup.py
=> Fixes #2902; Removes [docs] pip extra

newsfragments/2944.misc.rst, nucypher/network/nodes.py
Oryx testnet on Ropsten needs a default seed node.
> - Fixes #...
=> Add default seed node for Oryx

docs/source/pre_application/node_providers.rst
Re: https://github.com/nucypher/validator-profiles/pull/42.
=> Add Nodefolio to list of staking providers

docs/source/pre_application/node_providers.rst
BisonTrails -> Coinbase Cloud - including update to hyperlink.
=> Change BisonTrails to Coinbase Cloud.

newsfragments/2954.misc.rst, nucypher/utilities/prometheus/collector.py, nucypher/utilities/prometheus/metrics.py, tests/acceptance/cli/ursula/test_run_ursula.py, tests/acceptance/utilities/test_prometheus_collectors.py
Follow-up to #2950 and based over #2950.
- Take this opportunity to reorganize/rename metrics
- Added metrics
- Fixed prometheus tests.
Prometheus metrics can now be collected - tested on ibex. Base functionality works, we can think about additional metrics in a separate issue if necessary.
Fixes #2797 .
Fixes #2928 .
=> Prometheus revamp for Threshold - Follow up of #2950

Pipfile, Pipfile.lock, dev-requirements.txt, docs-requirements.txt, requirements.txt
=> Updates deps for nucypher-core prerelease

Pipfile, Pipfile.lock, dev-requirements.txt, docs-requirements.txt, nucypher/network/server.py, nucypher/policy/conditions/base.py, nucypher/policy/conditions/context.py, nucypher/policy/conditions/evm.py, requirements.txt, tests/acceptance/blockchain/conditions/test_conditions.py
Based over #2965 .
Actual verification of EIP712 message provided as part of ":userAddress" context variable.
Related to https://github.com/nucypher/tdec/issues/39.
Allows actual signature validation of data provided for `:userAddress` context variable.
I opted to use the https://github.com/ConsenSysMesh/py-eip712-structs library for now, but may use https://github.com/ApeWorX/eip712 when library is updated to handle JSON -> EIP Struct functionality. Ongoing discussion with ApeWorx team about potential updates to their library - https://discord.com/channels/922917176040640612/938897808147247186/1019985917219455046.
We can always switch later on since the …
=> Actual verification of ":userAddress" context variable data

nucypher/policy/conditions/context.py, tests/acceptance/blockchain/conditions/conftest.py, tests/acceptance/blockchain/conditions/test_conditions.py, tests/fixtures.py, tests/unit/conditions/conftest.py
Follow-up RFCs from #2966 that weren't completed before PR merge.
Follow-up of #2966.
=> Follow up RFCs from #2966.

docs/source/pre_application/node_providers.rst
… Cloud.
Copies updates made to https://docs.threshold.network/extras/staking-providers for InfStones. Additional change from Bison Trails to Coinbase Cloud.
=> Update information for InfStones, and change Bison Trails to Coinbase Cloud

docs/source/pre_application/node_providers.rst
Update list of staking providers to remove Nodefolio.
> - Fixes #...
=> Remove Nodefolio from staking providers

nucypher/policy/conditions/lingo.py
=> Inspiration credits to lit protocol

nucypher/network/server.py, nucypher/policy/conditions/__init__.py, nucypher/policy/conditions/base.py, nucypher/policy/conditions/evm.py, nucypher/policy/conditions/lingo.py, nucypher/policy/conditions/time.py, tests/acceptance/blockchain/conditions/conftest.py, tests/acceptance/blockchain/conditions/test_conditions.py, tests/unit/conditions/conftest.py, tests/unit/conditions/test_condition_lingo.py, tests/unit/conditions/test_condition_validity.py
Just a simple musing for now about exception handling until we decide what we are doing regarding https://github.com/nucypher/tdec/issues/60. This is along the lines of the 2. option mentioned here - https://github.com/nucypher/tdec/issues/60#issuecomment-1262791297.
- https://github.com/nucypher/tdec/issues/60
In https://github.com/nucypher/tdec/issues/60 there were other possible ideas about handling exceptions potentially checking them as condition results as well. This strategy just propagates the error message back to the caller. Other scenarios can be explored.
=> Handle RPC Condition call failure and other failure modes

newsfragments/2996.feature.rst, nucypher/blockchain/eth/contract_registry/tapir/contract_registry.json, nucypher/blockchain/eth/networks.py, nucypher/network/nodes.py
Add tapir network to network, nodes, and registry
=> Add tapir network to network, nodes, and registry

nucypher/network/server.py, nucypher/policy/conditions/_utils.py, nucypher/policy/conditions/base.py, nucypher/policy/conditions/context.py, nucypher/policy/conditions/evm.py, nucypher/policy/conditions/exceptions.py, nucypher/policy/conditions/lingo.py, nucypher/policy/conditions/time.py, tests/acceptance/blockchain/conditions/test_conditions.py, tests/integration/characters/test_bob_handles_frags.py, tests/integration/characters/test_conditional_reencryption.py, tests/unit/conditions/test_condition_lingo.py, tests/unit/conditions/test_condition_validity.py
Better handle error cases and condition failure cases.
> - Fixes #...
=> Ursula server update - fix abstraction leaks

nucypher/network/middleware.py
=> Fixes missing call to response.json on HTTP 400.

.coveragerc, .github/workflows/python_tests.yml, README.md, pytest.ini, tests/acceptance/blockchain/actors/test_ursula_operator.py
=> Code Coverage

.gitignore, nucypher/blockchain/eth/registry.py, nucypher/characters/base.py, nucypher/crypto/tls.py, nucypher/policy/conditions/_utils.py, nucypher/policy/conditions/context.py, nucypher/policy/conditions/evm.py, nucypher/utilities/ethereum.py, tests/unit/conditions/test_condition_lingo.py, tests/unit/conditions/test_evaluate_conditions.py, tests/unit/conditions/test_evm_condition_serializers.py, tests/unit/conditions/test_utils.py, tests/unit/test_operator_bonded_tracker.py
…n method.
Our current test coverage is pretty low.  Let's improve our testing coverage via this PR. All are welcome to add commits to this PR with tests (and potential bug fixes where needed) (cc @theref , @KPrasch ).
To get an overview of our current coverage and areas that are lacking - see https://app.codecov.io/gh/nucypher/nucypher/.
=> Testing blitz to improve code coverage.

newsfragments/3025.bugfix.rst, nucypher/characters/lawful.py, nucypher/network/retrieval.py, nucypher/network/server.py, nucypher/policy/conditions/base.py, nucypher/policy/conditions/evm.py, nucypher/policy/conditions/exceptions.py, nucypher/policy/conditions/lingo.py, nucypher/policy/conditions/rust_shims.py, nucypher/policy/conditions/time.py, nucypher/policy/conditions/types.py, nucypher/policy/conditions/utils.py, tests/acceptance/blockchain/conditions/conftest.py, tests/acceptance/blockchain/conditions/test_conditions.py, tests/integration/characters/test_bob_handles_frags.py, tests/unit/conditions/test_condition_lingo.py, tests/unit/conditions/test_condition_validity.py, tests/unit/conditions/test_evm_condition_serializers.py, tests/unit/conditions/test_return_value.py, tests/unit/conditions/test_utils.py, tests/utils/policy.py
Reencryption request without conditions causes failure:
```
Traceback (most recent call last):
File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/controllers.py", line 221, in handle_request
response = self._perform_action(action=method_name, request=request_body)
File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/controllers.py", line 44, in _perform_action
response = method(**params)  # < ---- INLET
File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/interfaces.py", line 17, in wrapped
return func(*args, **kwargs)
File "/Users/derek/Documents/Github/repos/forks/derek/nucypher-porter/porter/interfaces.py", line 68, in retrieve_cfrags
retrieval_outcomes = …
```
=> Handle retrieval request with no conditions

nucypher/policy/conditions/base.py, nucypher/policy/conditions/evm.py, nucypher/policy/conditions/lingo.py, nucypher/policy/conditions/types.py, nucypher/policy/conditions/utils.py, nucypher/policy/kits.py
=> Refine typing used for LingoList; better define constituent parts.

.github/workflows/contract_tests.yml, .github/workflows/darker.yml, .github/workflows/python_tests.yml, .github/workflows/run_demo.yml, codecov.yml
Based over #3019 
* Speed up gh action builds
* Limit excessive builds eg. when a PR comment gets edited, or PR moved to Ready for Review (don't trigger a build 😅 )
=> Update GH actions - scope triggers, and use caching

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/sol/source/contracts/Coordinator.sol, tests/mock/coordinator.py, tests/unit/test_coordinator.py
Missed commits after rebase for #3054 .
* Verify caller when posting aggregated transcripts to Coordinator contract
* Nodes now post the dkg public key when posting their aggregated transcripts.
=> Ferveo-DKG - post public key with aggregated transcripts (missed changes from 3054 rebase)

tests/acceptance/blockchain/agents/test_coordinator_agent.py, tests/acceptance/learning/test_fault_tolerance.py, tests/integration/blockchain/test_dkg_ritual.py, tests/integration/blockchain/test_ritualist.py, tests/mock/coordinator.py, tests/unit/test_external_ip_utilities.py
In anticipation of creating a testnet soon, ensure that DKG tests now pass.
=> Make DKG test pass

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/trackers/dkg.py, nucypher/characters/lawful.py, nucypher/crypto/ferveo/dkg.py, nucypher/network/middleware.py, nucypher/network/server.py, nucypher/utilities/events.py, tests/acceptance/blockchain/actors/test_ritual.py, tests/acceptance/cli/ursula/test_run_ursula.py, tests/integration/blockchain/test_dkg_ritual.py, tests/integration/blockchain/test_ritualist.py, tests/mock/coordinator.py, tests/unit/test_coordinator.py
=> Bugfixes: coordinator event scanning and tdec request/response

scripts/hooks/nucypher_dkg.py
Based over #3092 .
Script for testing optional ritual creation, and encryption/decryption of data using the cohort of nodes.
=> Dkg Script

nucypher/crypto/keypairs.py, nucypher/crypto/utils.py, tests/unit/crypto/test_keccak_sanity.py, tests/unit/crypto/test_keypairs.py
Replaces unintentionally closed PR #3111 
1
=> Deprecates pysha3 direct dependency

nucypher/blockchain/eth/contract_registry/mumbai/contract_registry.json
=> Add StakeInfo and Coordinator abis to mumbai registry

docs/source/conf.py, readthedocs.yml, setup.py
Updates docs configuration to use python 3.8, and new image.
=> Update docs configuration files

scripts/hooks/nucypher_dkg.py
Updates the dkg script to use separate provider uris for eth staking network and coordinator network.
The script can be tested using existing dkg ritual id `2`.
=> Update `nucypher_dkg` hook/script to use separate provider uris for staking and coordinator

scripts/hooks/nucypher_dkg.py
- Allow dkg size to be specified
- Allow multiple rituals to be created via parameter.
> - Fixes #...
=> DKG ceremony initiation script improvements

Pipfile, Pipfile.lock, nucypher/blockchain/eth/actors.py, nucypher/characters/chaotic.py, nucypher/characters/lawful.py, nucypher/crypto/ferveo/dkg.py, nucypher/crypto/powers.py, nucypher/network/server.py, requirements.txt, tests/integration/blockchain/test_dkg_ritual.py, tests/integration/config/test_keystore_integration.py
- Other
- 2
- Ensures compatibility with an upcoming `nucypher-core@0.11.0` release
- Related to: https://github.com/nucypher/nucypher-core/pull/69
- Awaits release of `nucypher-core@0.11.0` and replacing the git dependencies to an actual Python package
=> Tracking changes for `nucypher-core@0.11.0` update

tests/acceptance/conditions/test_multichain_evaluation.py
=> includes a few missing 'contractType' fields in condition tests.

examples/tdec/simple_tdec_local.py, examples/tdec/simple_tdec_using_testnet.py, nucypher/cli/commands/ursula.py, nucypher/config/migrations/common.py, nucypher/config/migrations/configuration_v1_to_v2.py, nucypher/config/migrations/configuration_v3_to_v4.py, nucypher/config/migrations/configuration_v4_to_v5.py, nucypher/config/migrations/configuration_v4_to_v6.py, nucypher/config/migrations/configuration_v5_to_v6.py, nucypher/policy/conditions/evm.py
- Bugfix
- 1
- Fixes an `AttributeError` upon condition evaluation (specifically during POA chain setup)
- Corrects incorrectly named configuration migration field (`condition_providers` -> `condition_provider_uris`)
- Adds missing `conditionType` field in `nucypher/examples`
**Notes**
- This PR is tagged `dkg-dev-11` and deployed to `lynx`
=> Assorted Bugfixes (migrations, multichain, condition schema)

nucypher/blockchain/eth/contract_registry/mumbai/contract_registry.json
Related to work being done in `nucypher-contracts` - https://github.com/nucypher/nucypher-contracts/pull/119
Craft a candidate for Lynx `alpha-13`.
> - Fixes #...
=> Lynx `alpha-13` Candidate

nucypher/blockchain/eth/contract_registry/lynx/contract_registry.json
Related to #3247 .
Lynx registry needs to be updated as well.
> - Fixes #...
=> Update lynx registry to have TACoApplication

nucypher/blockchain/eth/contract_registry/lynx/contract_registry.json, nucypher/blockchain/eth/contract_registry/mumbai/contract_registry.json, tests/acceptance/ape-config.yaml, tests/acceptance/conftest.py
- Use latest contract changes, and test them via acceptance tests
- Update contract registries for `lynx` and `mumbai` based on lynx deployment
> - Fixes #...
=> Lynx Alpha 13 Deployment Registries (pt. II)

scripts/hooks/nucypher_agents.py
=> Update `nucypher_agents` script

newsfragments/3277.misc.rst, nucypher/blockchain/eth/contract_registry/tapir.json
Other
1
Add latest contract registry for Tapir deployment (October 6th, 2023).
**Notes**
Deployment PR in nucypher-contracts https://github.com/nucypher/nucypher-contracts/pull/141
=> Add Tapir contract registry from latest deployment.

.github/workflows/lynx.yml, .github/workflows/ruff.yaml, examples/testnet_simple_taco.py, newsfragments/3185.feature.rst
> How many reviews does the PR author need?
Creates a GH action that runs the testnet script on Lynx
* Action is triggered by pushing PRs, manually, and every 20 minutes.
* It will give us valuable information about state of Lynx testnet and API stability
Sister PR for nucypher-ts: https://github.com/nucypher/nucypher-ts/pull/316
Improvements for later:
* The 20 minutes schedule can be reconsidered soon, once we gain a bit of confidence in both Lynx and the GH action workflow.
* The workflow can be improved with more informative diagnosis in case of failures
* For the moment, it uses many hard-coded values (ritual ID, encryptor signing key, RPC provider, etc). There's lot of room for improvement there too. …
=>  Running Lynx simple example as a GH action

examples/local_simple_taco.py, examples/testnet_compound_multichain_taco.py, examples/testnet_simple_taco.py, newsfragments/3293.feature.rst, nucypher/policy/conditions/evm.py, nucypher/policy/conditions/exceptions.py, nucypher/policy/conditions/lingo.py, nucypher/policy/conditions/time.py, scripts/hooks/nucypher_dkg.py, tests/acceptance/actors/test_dkg_ritual.py, tests/acceptance/conditions/test_conditions.py, tests/fixtures.py, tests/integration/blockchain/test_integration_dkg_ritual.py, tests/integration/characters/test_conditional_reencryption.py, tests/integration/characters/test_dkg_and_testnet_bypass.py, tests/integration/config/test_keystore_integration.py, tests/integration/learning/test_domains.py, tests/unit/conditions/test_compound_conditions.py, tests/unit/conditions/test_condition_lingo.py, tests/unit/conditions/test_condition_validity.py
Add functionality for `not` operator for logical conditions.
> - Fixes #...
=> Add Not Operator Functionality

newsfragments/3290.misc.rst, nucypher/cli/commands/taco.py
Add `nucypher taco rituals...` command to display ritual information
- By default only active rituals are shown but the `--include-inactive`/`-i` option can be used to include inactive rituals. 
- Specific ritual ids (multiple at the same time can also be specified) using `--ritual-id`. If not specified, all rituals are considered.
For example:
```
$ nucypher taco rituals --domain tapir --blockchain-endpoint <>
╒══════╤═════════════════════╤═════════════════════╤═════════════╤═════════════════════╤════════════════════════╤══════════╤══════════╕
│   ID │ Authority           │ AccessController    │ Threshold   │ Participants        │ Expiry                 │   State  │ Active   │ …
```
=> Add `taco` CLI command to list rituals for a specific TACo domain

newsfragments/3292.bugfix.rst, tests/integration/cli/test_ursula_config_cli.py
Add a new test for IP address detection
Also, a newsfragment info has been added following these suggestions: https://github.com/nucypher/nucypher/pull/3292/files#r1365709989
And some typos were fixed.
This is the continuation of https://github.com/nucypher/nucypher/pull/3292
=> Add a new test for IP address detection

tests/acceptance/agents/test_taco_application_agent.py, tests/acceptance/agents/test_taco_child_application_agent.py, tests/acceptance/ape-config.yaml, tests/acceptance/conftest.py
Uses latest code from `nucypher-contracts` which utilizes open zepellin 5.0.0 and resolves "Potential overflow" issue in `nucypher` acceptance tests via https://github.com/nucypher/nucypher-contracts/pull/162.
> - Fixes #...
=> Update `nucypher` based on OZ5 changes in `nucypher-contracts`

nucypher/blockchain/eth/registry.py, nucypher/cli/actions/select.py, tests/integration/cli/actions/test_select_client_account.py
=> Removes Ununsed Code

nucypher/utilities/prometheus/collector.py
=> Cast domain to a string for metrics collection

nucypher/policy/payment.py
=> Fixes incorrect `TACoDomain` import

newsfragments/3332.bugfix.rst, nucypher/blockchain/eth/registry.py, nucypher/cli/commands/taco.py, nucypher/cli/utils.py, nucypher/network/nodes.py, nucypher/policy/conditions/evm.py, nucypher/policy/conditions/lingo.py, nucypher/policy/conditions/time.py, tests/acceptance/conftest.py, tests/unit/conditions/test_return_value.py, tests/unit/conditions/test_rpc_condition.py, tests/unit/conditions/test_time_condition.py
Based over #3330 .
- Fixes incorrect seed node URL for `seeds.nucypher.network`
> - Fixes #...
=> Fix seed node URL

.pre-commit-config.yaml
- Update versions of pre-commit tooling to latest.
- Related to @manumonti 's point here - https://github.com/nucypher/nucypher-porter/pull/52#discussion_r1386168017
> - Fixes #...
=> Update versions of `darker` and `ruff` for pre-commit checks.

examples/testnet_compound_multichain_taco.py, examples/testnet_simple_taco.py
Changes examples to use lynx ritual 24 instead of 3.
> - Fixes #...
=> Lynx Ritual 3 is expired; use 24 instead for examples

newsfragments/3311.doc.rst, newsfragments/3318.misc.rst, newsfragments/3331.dev.rst, nucypher/policy/conditions/context.py, nucypher/policy/conditions/evm.py, nucypher/policy/conditions/lingo.py, tests/acceptance/conditions/test_conditions.py, tests/unit/conditions/test_context.py, tests/unit/conditions/test_return_value.py
=> Validate context variable names

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/cli/commands/taco.py, nucypher/cli/options.py, scripts/hooks/nucypher_dkg.py, tests/acceptance/actors/test_dkg_ritual.py, tests/acceptance/agents/test_coordinator_agent.py, tests/acceptance/ape-config.yaml, tests/integration/blockchain/test_integration_dkg_ritual.py, tests/mock/coordinator.py, tests/unit/test_coordinator.py, tests/unit/test_ritualist.py
Makes updates to `nucypher` based on changes in https://github.com/nucypher/nucypher-contracts/pull/187.
> - Fixes #...
- Updates made to ritual state/status.
=> Updates based on last minute Coordinator contract changes in `nucypher-contracts`

nucypher/blockchain/eth/contract_registry/lynx.json
Based over #3344 
==============
Update lynx contract registry based on deployment performed in https://github.com/nucypher/nucypher-contracts/pull/191. 
> - Fixes #...
=> Lynx Updated Contract Registry

nucypher/blockchain/eth/actors.py, nucypher/network/server.py, nucypher/policy/conditions/utils.py, tests/unit/conditions/test_utils.py
Update tests.
Related to #3326 , #3351 .
> - Fixes #...
=> Always raise `ConditionEvalError` (previously `EvalError`) instead of returning then raising

newsfragments/3339.feature.rst, nucypher/utilities/prometheus/collector.py, nucypher/utilities/prometheus/metrics.py, tests/integration/utilities/test_prometheus_collectors.py
- Remove unused metrics.
- Add metrics for root and child networks.
- Replace node discovery metrics from enum to gauge
#3236 #3240
Related to https://github.com/nucypher/nucypher/issues/3380
=> Update exported metrics to current Ursula code

nucypher/blockchain/eth/contract_registry/tapir.json
Sync tapir registry with the latest deployed contracts on Tapir testnet, https://github.com/nucypher/nucypher-contracts/pull/221
> - Fixes #...
=> Sync tapir contract registry with latest tapir update

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/registry.py, nucypher/characters/lawful.py, nucypher/network/templates/basic_status.mako
Bugfix
1
- Fixes #3381 
- Fixes the following log formatting issues:
```
M
Node 0xce057adc39dcD1b3eA28661194E8963481CC48b2 has pending tx b'\xc4f}Y\x9e\x07g\x8e\xd7\x10\xe1\x1b\xd4<\xc5 -kj\x19\x1cZ\xd7\xddh\x9f\xc8]\xe6tK\xa4' for posting aggregated transcript for ritual 6; skipping execution
```
```
Warning: <class 'nucypher.blockchain.eth.registry.EmbeddedRegistrySource'> is not a primary source.
```
```
THIS IS YOU: Ursula: (Ursula)⇀NO_NICKNAME↽ (None)
```
```
Fetching registry from <class 'nucypher.blockchain.eth.registry.GithubRegistrySource'> failed.
```
=> Fix log formatting and Favicon 404

nucypher/characters/lawful.py, nucypher/network/templates/basic_status.mako, tests/integration/network/test_ursula_web_status.py
=> Include latest event scanner block in `/status` endpoint

newsfragments/3223.feature.rst, newsfragments/3231.feature.rst, newsfragments/3339.feature.rst, newsfragments/3368.bugfix.rst, newsfragments/3376.misc.rst, newsfragments/3388.feature.rst, newsfragments/3390.bugfix.rst, newsfragments/3393.dev.rst, newsfragments/3396.bugfix.rst, newsfragments/3397.feature.rst, newsfragments/3398.bugfix.rst, newsfragments/3416.misc.rst, releases.rst
=> v7.1.0 Release Notes

nucypher/blockchain/eth/contract_registry/mainnet.json
Copies over `mainnet.json` from https://github.com/nucypher/nucypher-contracts/pull/239.
> - Fixes #...
Closes #3442 .
=> Update mainnet contract registry with latest changes deployed to mainnet - getParticipants that allows for paging results

nucypher/blockchain/eth/contract_registry/tapir.json, tests/acceptance/agents/test_sampling_distribution.py, tests/acceptance/agents/test_taco_application_agent.py
Copy over tapir registry based on https://github.com/nucypher/nucypher-contracts/pull/242.
> - Fixes #...
=> Update embedded tapir contract registry

newsfragments/3465.bugfix.rst, nucypher/cli/commands/ursula.py, tests/acceptance/ape-config.yaml, tests/acceptance/conftest.py, tests/integration/cli/test_ursula_cli_ip_detection.py, tests/integration/cli/test_ursula_cli_prometheus.py, tests/integration/cli/test_ursula_cli_run.py
Fixes #3448 .
Ran out of time to figure out how to actually test the change. Feel free to add additional commits regarding testing.
> - Fixes #...
The added integration test passes.
I'm not quite sure why the acceptance tests are failing - they pass locally on my machine. That being said, it is failing for the v7.3.x branch and so seems unrelated to this PR.
=> Auto-migrate specified config file

nucypher/crypto/utils.py
fix a typo: `betwee`->`between`
=> chore: fix typos

.github/workflows/python_tests.yml
Fixes issues with codecov uploads.
> - Fixes #...
=> Use latest version of codecov GH action

nucypher/policy/conditions/auth/evm.py, nucypher/policy/conditions/context.py, tests/fixtures.py, tests/unit/conditions/test_context.py, tests/unit/conditions/test_evm_auth.py
Just a code reorg, with no new functionality, to make way for other authentication strategies in the future.
> - Fixes #...
=> Refactored User Auth

scripts/network_client_versions.py
=> Add script to scrape `nucypher` client versions from nodes on the network

nucypher/blockchain/eth/actors.py, nucypher/blockchain/eth/agents.py, nucypher/blockchain/eth/models.py, nucypher/characters/chaotic.py, nucypher/characters/lawful.py, nucypher/crypto/ferveo/dkg.py, nucypher/crypto/powers.py, scripts/nucypher_dkg.py, tests/acceptance/actors/test_dkg_failures.py, tests/acceptance/actors/test_dkg_ritual.py, tests/acceptance/actors/test_ursula_operator_dkg_rounds.py, tests/acceptance/agents/test_coordinator_agent.py, tests/acceptance/ape-config.yaml, tests/acceptance/conftest.py, tests/integration/blockchain/test_integration_dkg_ritual.py, tests/mock/coordinator.py, tests/unit/test_coordinator.py, tests/unit/test_ritualist.py
Tests in `v7.5.x` will fail now that the work from https://github.com/nucypher/nucypher-contracts/pull/270 is merged into `main`. This PR updates our tests to use updated contracts and the new fee model architecture.
> - Fixes #...
Fixes #3514 .
Subsumes #3516 
> Is there a particular commit/function/section of your PR that requires more attention …
=> Fee Model Architecture Update For Tests

scripts/nucypher_dkg.py
=> Allow nucypher-dkg script to be used on mainnet

scripts/dkg/differing_ferveo_keys.py, scripts/dkg/verify_dkg.py
=> DKG verification script

nucypher/cli/commands/ursula.py, tests/integration/cli/test_ursula_public_keys_cli.py
Follow-up based on outstanding suggestion in #3538  - https://github.com/nucypher/nucypher/pull/3538#discussion_r1723134526.
> - Fixes #...
=> `ursula public-keys` error message cleanup

.bumpversion.cfg, newsfragments/3549.bugfix.rst, nucypher/__about__.py, nucypher/blockchain/eth/clients.py, nucypher/blockchain/eth/interfaces.py, nucypher/policy/conditions/evm.py, pyproject.toml, tests/mock/interfaces.py, tests/unit/test_blockchain_interface.py, tests/unit/test_web3_clients.py
=> [EPIC] v7.4.1 Hotfix

newsfragments/3558.feature.rst, nucypher/policy/conditions/lingo.py, nucypher/policy/conditions/types.py, tests/unit/conditions/test_condition_lingo.py, tests/unit/conditions/test_if_then_else_condition.py
Condition that allows for if-then-else branching based on underlying conditions 
i.e. **IF** `CONDITION A` **THEN** `CONDITION B` **ELSE** `CONDITION_C`.
The **ELSE** component can either be a Condition or a boolean value - this allows for more flexibility of what to do if the **IF** condition is false.
Grammar for if-then-else condition:
```
IF_THEN_ELSE_CONDITION = {
"conditionType": "if-then-else",
"ifCondition": CONDITION,
"thenCondition": CONDITION,
"elseCondition": CONDITION | true | false,
}
```
> - Fixes #...
**Notes for …
=> If-Then-Else Condition

tests/unit/conditions/test_json_api_condition.py
=> Json Condition :userAddress context variable

README.md, SECURITY.md
Update README links to docs.taco.build.
I'm not sure if using `main` branch as base for this PR is the right way to proceed. Can you confirm @KPrasch @derekpierre ?
=> Update README links to docs

nucypher/policy/conditions/types.py, tests/acceptance/conditions/conftest.py, tests/acceptance/conftest.py, tests/data/test_conditions.json, tests/unit/conditions/test_condition_lingo.py
- added `ConditionDict` types for `JsonRpcCondition` and update `JsonApiCondition` to include `authorizationToken`
- update old `test_conditions.json` file to adhere to latest condition schemas
- added all current condition types to the test file
- added test to check all entries in the file.
> - Fixes #...
=> Lingo Cleanup

nucypher/utilities/logging.py
Based over #3585.
Redact IP addresses of HTTP requesters from log files. 
The original log message is created here, https://github.com/twisted/twisted/blob/twisted-20.3.0/src/twisted/web/http.py#L2719, with the formatted configured here, https://github.com/twisted/twisted/blob/twisted-20.3.0/src/twisted/web/http.py#L3093. 
This manifests on Ursula and Porter (once the dependency is updated). Note: all request messages that include IP addresses will have the IP address redacted. This can be heavy handed since it applies across all requests including those for P2P learning, which may make debugging issues harder.
- on Ursula:
```
2024-11-26T14:24:36+0000 [twisted.python.log#info] "<IP_REDACTED>" - - [26/Nov/2024:14:24:36 +0000] …
```
=> Redact IP addresses of http requesters from logs
