- nkms/crypto/keypairs.py
- nkms/crypto/keyring.py
- tests/crypto/test_keypairs.py
- tests/test_network_actors.py
1. Allows iterable objects to be passed instead of just expecting plain `bytes` objects.
2. Adds a `digest` method to `SigningKeypair` that accepts an `Iterable` as `data`.
1. If `data` is of `bytes` type, then it just hashes like normal.
2. If `data` is not `bytes` but is an `Iterable`, then each item within it is updated into the digest.
> Allow iterables to be digested and signed

- nkms/characters.py
- nkms/crypto/powers.py
- nkms/keystore/keypairs.py
- tests/characters/test_crypto_characters_and_their_powers.py
- tests/crypto/test_signing_power.py
- tests/keystore/test_keypairs.py
1. Implements `SigningPower` in `nkms.crypto.powers`.
1. Adds tests in `tests.keystore.test_keypairs` and `tests.crypto.test_signing_power`.
2. Fixes tests that use `SigningKeypair` and replaces it with `SigningPower`.
3. Fixes character code that use `SigningKeypair` and uses `SigningPower`.
2. Implements a `sign` and `verify` method on `SigningKeypair`.
1. `verify` verifies with the keypair's own public key.
> Implement SigningPower

- nkms/keystore/keystore.py
- tests/keystore/test_keystore.py
1. Adds a `KeyNotFound` Exception class.
1. This gets raised in `KeyStore.get_key` when the fingerprint requested isn't found.
2. Implements `KeyNotFound` in the `tests.keystore.test_keystore` tests.
> Implement KeyNotFound Exception

- nkms/keystore/keypairs.py
- nkms/keystore/keystore.py
- tests/keystore/test_keypairs.py
1. Adds a method for deserializing a serialized key in `Keypair`.
2. Adds test for serializing and deserializing a key.
3. Calls `Keypair.deserialize_key` in `Keystore.get_key`.
> Add method for deserializing key in Keypair

- nkms/characters.py
- nkms/crypto/api.py
- nkms/crypto/constants.py
- nkms/crypto/signature.py
- nkms/keystore/keypairs.py
- nkms/network/protocols.py
- tests/characters/test_crypto_characters_and_their_powers.py
- tests/crypto/test_api.py
- tests/keystore/test_keypairs.py
- tests/keystore/test_keystore.py
- tests/network/test_network_actors.py
Public Keys are now generated with metabytes.
**This PR does not include metabytes for Private Keys - only public.**
A `PublicKey` class includes metadata for total length and metabyte length as well as a facility for stripping metabytes.
> Metabytes for key generation, PublicKey class, and safety for public key de/serialization.

- .travis.yml
- nkms/characters.py
- nkms/crypto/api.py
- nkms/crypto/kits.py
- nkms/crypto/powers.py
- nkms/crypto/signature.py
- nkms/crypto/splitters.py
- nkms/data_sources.py
- nkms/keystore/keypairs.py
- nkms/keystore/keystore.py
- nkms/network/protocols.py
- nkms/network/server.py
- nkms/policy/models.py
- tests/characters/test_alice_can_grant_and_revoke.py
- tests/characters/test_bob_handles_frags.py
- tests/characters/test_crypto_characters_and_their_powers.py
- tests/fixtures.py
- tests/network/test_network_actors.py
Alice can now `grant` and then disappear from the network, never to be seen again.
Subsequently, any number of `DataSources` can supply messages for `Bob`.
This is comparable to our discussions about a four-character narrative involving a `Character` named `Enrique` the Encapsulator (See #182).
However, once `Enrique` was written, it was clear that he *wasn't* a `Character`.  He didn't require any special powers (remember, his only notable role was to encrypt, which any `Character` can do).
Additionally, unlike the other characters in our cryptological narrative, `Enrique`'s exact interests are very hard to pin down: he doesn't pay, nor does he stake, nor does he rely on messages from the other actors.  In fact, his role is arguably optional: `Alice` *can* do everything he does.
So, …
> Separating Delegation from Encapsulation

- tests/blockchain/eth/contracts/test_government.py
- tests/blockchain/eth/contracts/test_integration.py
- tests/blockchain/eth/contracts/test_miners_escrow.py
- tests/blockchain/eth/contracts/test_policy_manager.py
All contracts tests pass under one condition:
Max gas limit should be increased up to 4626271 of gas if gas estimate buffer is 1.5.
Eth tester has no api for that (or I missed it), so for quick fix may change GENESIS_GAS_LIMIT or GAS_ESTIMATE_BUFFER in eth_tester\backends\pyevm\main.py
> Fixes for solidity and web3 tests

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/chains.py
- nucypher/blockchain/eth/constants.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/policies.py
- nucypher/characters.py
- tests/blockchain/eth/entities/test_actors.py
- tests/blockchain/eth/entities/test_agents.py
- tests/blockchain/eth/test_api.py
- tests/blockchain/eth/test_setup.py
- tests/blockchain/eth/utilities.py
- tests/eth_fixtures.py
- tests/utilities.py
This was the original design of the blockchain client, that can now be revisited. Agents have a close relationship to the smart contracts code they can execute, and TokenActors compose their usage.
Overall, this PR is mostly relocation of code, but some additional solidity methods are also exposed, as well as the Agents API usage on Actors and Characters, and several utility functions.
This PR is very similar to #297, but utilizing an esoteric feature of Python that causes it to run properly in the absence of syntax errors. It is also very similar to #299, but with a fresh history, since GH did not update the diff.
> Push contract API down to Agents 

- nucypher/blockchain/eth/interfaces.py
- nucypher/characters.py
- nucypher/crypto/powers.py
- tests/characters/test_crypto_characters_and_their_powers.py
1. Adds `BlockchainPower` with `sign_message` and `verify_message` methods.
2. Adds `call_backend_sign` and `call_backend_verify` methods on `DeployerCircumflex`.
3. `call_backend_sign` uses some `eth_tester` stuff to sign messages if the `EthereumTester` provider is being used, otherwise, it defaults to the (deprecated) `w3.eth.sign` which might be problematic.
> Create a BlockchainPower with signing and verifying methods

- .circleci/config.yml
- Pipfile
- Store XML Test result summary for circleci API
- Updates web3.py to 4.4.1 (Causes secondary Issue requiring a downgrade of `py-evm` + `eth-tester`). 
- Fixes `Pipfile` versioning for PR #329 
- Removes unused dependencies
- Organize and label `Pipfile`
Prior Issue reference with working versions: PR #301
> Store test Results; Upgrade Web3

- examples/finnegans-wake-federated.py
- examples/run_ursula_with_rest_and_dht_but_no_mining.py
- examples/sandbox_resources.py
- nucypher/characters.py
- nucypher/crypto/signing.py
- nucypher/keystore/keystore.py
- nucypher/network/middleware.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- tests/characters/test_alice_can_grant_and_revoke.py
- tests/characters/test_bob_handles_frags.py
- tests/conftest.py
- tests/network/test_network_actors.py
* Updates all of the demo machinery (non-mining node script, middleware, demo script) with new features and semantics
* Cleans up signing logic for node verification
* Allows TreasureMaps to *either* be passed in *or* looked up by ID, instead of needing two steps
* Cleans up some tests in light of #356
> Uniting Finnegan's Wake demo logic with current master.

- nucypher/characters.py
- nucypher/network/server.py
- nucypher/policy/models.py
- tests/characters/test_bob_handles_frags.py
- tests/characters/test_crypto_characters_and_their_powers.py
1. Adds an exception class to `Character` as `InvalidSignature`.
2. Raises `InvalidSignature`if `verify_from` in all cases where `is_valid == False`.
3. Adds try/except blocks for `InvalidSignature` in places in `network.server` and `characters` where `verify_from` is called.
4. Fixes tests for this pattern.
5. Removes unused `hrac` variable in `characters.Bob.join_policy`.
6. Raises the Cryptography.io `InvalidSignature` error in `crypto.api.ecdsa_verify` if the signature was invalid instead of returning the boolean.
6. Resolves #358
> Raise InvalidSignature in verify_from

- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/characters/unlawful.py
- nucypher/config/node.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- tests/characters/test_ursula_prepares_to_act_as_mining_node.py
- tests/fixtures.py
- tests/network/test_network_actors.py
Previously, it was possible for a chaotic actor to replay old node metadata, causing out-of-date information, including possibly public keys for compromised keypairs, to propagate across the network.
This PR address this in the following way:
* Ursula now creates a new timestamp whenever she signs her interface info (building on @tuxxy's previous work on timestamp)
* When nodes are remembered, their timestamp is kept as an attribute.
* When a node is passed to `remember_node` it is only remembered if it is the newest timestamp among those nodes.
Other things:
* Learners now fully verify nodes at "remember time" (recall that, if the learning loop is not run in eager mode, they only validate the metadata, rather than fully verifying the node during learning).  (This essentially nullifies …
> Protection against node metadata replay attacks.

- Pipfile
- nucypher/network/protocols.py
- nucypher/network/server.py
- tests/network/test_network_actors.py
1. Removes the Kademlia `digest` function and uses `nucypher.crypto.api.keccak_digest` instead.
2. Calls `unhexlify` on the `treasure_map_id` to hash the raw bytes instead of the digest.
3. Removes `rpcudp` dependency
4. Resolves #472 #474
> Remove Kademlia digest function 

- Pipfile
- nucypher/blockchain/eth/interfaces.py
- Integrates `eth-tester==0.1.0b33`
- Removes pinned dependency for constantSorrow; Use `constant-sorrow` on PyPI
> Remove Pinned GitHub Dependencies

- Pipfile
- cli/main.py
- nucypher/__init__.py
- nucypher/utilities/logging.py
- scripts/install_solc.sh
- setup.py
- tests/config/test_storages.py
* Deprecate CLI Simulate Command
* Accept Load-Balanced Teacher URI's 
* Cleanup Simple Observer Output
* Skip S3 Storage Tests (Recent Version Incompatibility with `boto`, `botocore`, `moto`) #527
* Include 'cli' as a top-level module.  #502 
* Pin `tzlocal==1.5.1` (Version Conflicts unresolved via Pipenv)
> Inline Teacher URI Option; CLI Touch-ups

- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/config/keyring.py
- nucypher/config/node.py
- nucypher/config/storages.py
- nucypher/crypto/powers.py
- nucypher/keystore/keypairs.py
- tests/characters/test_alice_can_grant_and_revoke.py
- tests/config/test_firstula_circumstances.py
- tests/config/test_keyring.py
- tests/keystore/test_keypairs.py
Currently, DelegatingPower is not persistent, which means that Alice can only grant access to Bobs while her DelegatingPower is in memory; when restored through the Keyring, a new DelegatingPower is created, and due to its random nature, it cannot recreate the same policies.
This PR extends the Keyring to store the state of the DelegatingPower so it can be restored for later use. 
Additionally, it provides a convenience method `Alice.get_policy_pubkey_from_label()` to derive policy public keys independently of policy creation. This supports one of the use case we mention often, where Enricos can encrypt for a policy _even before_ Alice has started to grant access to it.
> Persistent DelegatingPower

- nucypher/characters/lawful.py
- nucypher/cli.py
- nucypher/config/storages.py
- nucypher/network/templates/basic_status.j2
- Fixes CLI errors when `nucypher stake` and `nucypher accounts` are called with no arguments.
- Adds docs to CLI commands `nucypher configure` and `nucypher stake`
- Shallow changes to the node status page (favicon, sans-serif font, removes text shadow which reads badly, etc)
> Touch-ups to CLI and status page

- Pipfile
- setup.py
Umbral will have soon a new non-backwards-compatible release. Let's pin umbral to current release (v0.1.1a3) for the moment. `vodka` will fix everything (it always does, right?).
> Pin umbral==0.1.1a3 before new API-breaking release

- Pipfile
- nucypher/keystore/keystore.py
- nucypher/network/middleware.py
- nucypher/network/server.py
- nucypher/policy/models.py
- requirements.txt
- tests/characters/test_alice_can_grant_and_revoke.py
- tests/characters/test_bob_handles_frags.py
This is for the `vodka` branch.
- Adapts NuCypher to `umbral==0.1.2a0`
- Brings back `coincurve` (pinned to v9.0.0)
> Adapt NuCypher to umbral==0.1.2a0

- .gitignore
- Pipfile
- deploy/ansible/provision.yml
- deploy/ansible/restart_all.yml
- deploy/ansible/run_seednodes.yml
- deploy/ansible/terminate.yml
- deploy/ansible/update.yml
- deploy/ansible/wipe_ursula_config.yml
- Separates server provisioning from Ursula network services configuration
- Uses `NUCYPHER_NETWORK_NAME` envvar as dynamic inventory tag
- Updates .gitignore with Ansible variables
> [Federated] Split Ansible playbooks; Use network names

- .gitignore
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/chains.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/registry.py
- nucypher/cli/deploy.py
- nucypher/cli/main.py
- nucypher/cli/types.py
- nucypher/config/characters.py
- nucypher/config/node.py
- nucypher/utilities/sandbox/blockchain.py
- nucypher/utilities/sandbox/constants.py
- tests/blockchain/eth/interfaces/test_solidity_compiler.py
- tests/cli/commands/test_federated_ursula.py
- tests/cli/commands/test_status.py
- tests/cli/conftest.py
- tests/config/test_firstula_circumstances.py
- tests/config/test_storages.py
- tests/fixtures.py
- tests/network/test_node_storage.py
The recent work to build a federated network, left this code on the back-burner for a while.  This PR updates reestablishes decentralisation as the primary and default operating mode.
- Restore nucypher contract deployment CLI (`nucypher-deploy`;  Implements `Deployer` actor)
- Sets `--federated-only` False by default (Fixes #600)
- Select a (possibly) open network port for test runs (Fixes #566 )
- Ensure deployer uses it's internal blockchain reference to produce entities.
- Allow CLI to accept any port number when passed via `--rest-port` (Fixes #601)
- Separates configuration parameter generation and character production
- Ensure federating operating mode is determined by configuration, not always by flag.
> Maintain non-federated CLI

- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/config/keyring.py
- nucypher/crypto/powers.py
- nucypher/keystore/keypairs.py
- nucypher/keystore/keystore.py
- nucypher/network/nodes.py
- nucypher/policy/models.py
- tests/blockchain/eth/entities/agents/test_policy_manager_agent.py
- tests/characters/test_alice_can_grant_and_revoke.py
- tests/characters/test_bob_handles_frags.py
- tests/config/test_keyring.py
- tests/keystore/test_keypairs.py
- tests/keystore/test_keystore.py
1. Renames `EncryptingKeypair` and `EncryptingPower` to `DecryptingKeypair` and `DecryptingPower` respectively. Resolves #597 
2. Renames `TestPolicyMetadata` to `MockPolicyData` as per pytest warnings.
> Rename EncryptingKeypair/EncryptingPower to DecryptingKeypair/DecryptingPower

- .circleci/config.yml
- Pipfile
- nucypher/config/constants.py
- nucypher/utilities/logging.py
- tests/metrics/estimate_gas.py
- tests/metrics/estimate_gas_tester.py
Restores the `estimate_gas.py` scenario-based metrics script. Uses the twisted logger facilities to collect, store, and view gas estimation data.  Log files can possibly be used as a build artefact, or extended for further analysis.  Fixes #602 
- Twisted based logging and data collection
- Save timestamped JSON logs and result reports
- CircleCI build automation and storage of the resulting artefacts
Example Build: <https://circleci.com/gh/nucypher/nucypher/8175#artifacts/containers/0>
Example Artefact: <https://8175-100446516-gh.circle-artifacts.com/0/home/circleci/nucypher-depends/tests/metrics/results/1544742453-estimate-gas.json>
> Maintain Gas Estimation Metrics

- tests/config/test_ursula_config.py
Includes a test that proves `UrsulaConfiguration` is temporary and ephemeral when called with `dev_mode=True`
Basically what we are trying to show here is that development configurations produce unique character instances, and that they use ephemeral resources, like the in-memory database and temporary disk storage
> Ursula Development Configuration Test

- .gitignore
- nucypher/blockchain/eth/chains.py
- nucypher/utilities/sandbox/blockchain.py
- tests/metrics/estimate_gas.py
We have a growing need to run test or scripts within the context of an already deployed nucypher network.
Overrides `TesterBlockchain.connect`; Disregarding arguments, and redirecting to the default PyEVM configuration with an `InMemoryContractRegistry` and deployer options set on `BlockchainDeployerInterface`.
```
testerchain, accounts = TesterBlockchain.bootstrap_network()
```
Once the nucypher network is deployed, you can use the `Agents` API as usual:
```
token_agent = NucypherTokenAgent(blockchain=testerchain)
miner_agent = MinerAgent(blockchain=testerchain)
policy_agent = PolicyAgent(blockchain=testerchain)
```
Included in automated testing in `estimate_gas.py`
> High-level TesterBlockchain network bootstrap method

- nucypher/cli/main.py
- nucypher/cli/protocol.py
- nucypher/config/node.py
- nucypher/network/nodes.py
- nucypher/utilities/sandbox/constants.py
- tests/cli/commands/test_run_ursula.py
- tests/config/test_ursula_config.py
- tests/fixtures.py
- #614 - Question: Do we want this condition to `raise`?
- #634 - Unskip `nucypher ursula run` CLI test (Reactor / Pytest Issue)
- #610 - Timestamp temp system filepaths
- #551 - Auto-generate configuration root directory if it does not exist.
- #578 (Half) - Disable logging via CLI (`--quiet` / `-Q`)
- #583 - Allow destruction of invalid system configurations
Also attempts to address #582 
| Option | Shorthand |
-----------|----------------|
| `--dev` | `-d` |
| `--federated-only` | `-F` |
| `--debug` | `-D` |
| `--quiet` | `-Q` |
| `--force` | - |
| `--dry-run` | `-x` |
- Remove `cleanup` pytest fixture
> CLI bug fixes and enhancements

- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/config/constants.py
- nucypher/config/node.py
- nucypher/network/nodes.py
- nucypher/network/server.py
1. Deserializes domain constants from config files as UTF-8 bytestrings.
- They get serialized as strings.
2. Moves `GLOBAL_DOMAIN` definition to `config.constants`
3. Removes an unused `logging.Logger` import that shadows a `twisted.Logger` import.
4. Resolves #671
> Make domain constants bytestrings

- docs/source/architecture/upgradeable_proxy_contracts.rst
- docs/source/demos/finnegans_wake_demo.rst
- docs/source/demos/local_fleet_demo.rst
- docs/source/guides/contribution_guide.rst
- docs/source/guides/federated_testnet_guide.rst
- docs/source/guides/ursula_configuration_guide.rst
- docs/source/index.rst
- Fixes formatting problems of RST when using inverted quotes for commands (e.g., `` `whatever` ``). It seems that RST requires double-quotes instead of single quotes, which were formatted as italics and some commands weren't shown right (e.g., `--help` was shown as _–help_).
- Fixes broken internal links.
- Fixes link of Discord badge, adds CircleCI badge.
- Typos.
> Fix formatting issues of RST files

- deploy/learning_monitor.py
- deploy/templates/monitor.html
- nucypher/characters/base.py
- nucypher/network/nodes.py
* Introducing `Moe`, an ultralight `Character` which reports results of `learn_from_teacher_node` and `remember_node` via websocket (using the hendrix `hey_joe` API).  `Moe` also uses a customized `FleetStateTracker` which similarly reports changes to the recorded fleet state.
* Provides a small Flask application to access a real-time status page.
* Updates real-time fleet information using handlebars templates.
> Real-time learning monitor

- .bumpversion.cfg
- README.md
- docs/source/conf.py
- nucypher/__about__.py
**Note: This Tag has already been pushed to distributors.  This PR is a follow up to update master with the tagged release commit**
> [Post-Release] Bump version: 0.1.0-alpha.4 → 0.1.0-alpha.5

- deploy/learning_monitor.py
- deploy/templates/monitor.html
- nucypher/characters/lawful.py
- nucypher/network/middleware.py
- nucypher/network/nodes.py
- nucypher/utilities/sandbox/middleware.py
- tests/learning/test_fault_tolerance.py
* Creates new shared middleware `_Client`, which wraps all calls (production and test) to network library code (ie, requests and werkzeug). 
* "cleans" all returning responses, ensuring that `content` is an available attr in either case.
* Moved status-code checking up to the client so that it happens all in one place.
* Raises `NotFound` if an endpoint returns a 404, `UnexpectedResponse` for other > 300 responses.
> Reworking middleware to share more logic.

- .bumpversion.cfg
- .circleci/config.yml
- docs/source/conf.py
- nucypher/__about__.py
**Note: This tag has already been pushed to distributors - This PR is a follow-up to synchronize with `master`**
> [Building] [Release] Bump version: 0.1.0-alpha.5 → 0.1.0-alpha.7

- CODE_OF_CONDUCT.md
- CONTRIBUTING.rst
- README.md
This PR implements some of GitHub's recommended community standards: https://github.com/nucypher/nucypher/community
Remaining recommendations are (do we want these?):
- Issue templates
- Pull request templates
> Includes code of conduct and contributing guide

- .circleci/config.yml
- docs/source/demos/heartbeat_demo.md
- examples/heartbeat_demo/alicia.py
- examples/heartbeat_demo/heartbeat_demo.md
This PR aims at two different things, both related to CircleCI:
1) A naive test of the currently official heartbeat demo (i.e., the command-line one):
- Adds a `heartbeat_demo` task that deploys a local fleet and tests the demo (#599).
- I've run into problems for using the fleet script in CircleCI. I ended up spinning a few nodes individually.
2) A simple, not-at-all-elegant way to speed up the running time of our builds by ~25%:
- Increases the parallelism in a few tasks where there was still some room for improvement.
- Reuses the pipenv workspace for building the docs. (Saved almost 2 minutes here. Yay!)
- This is the "ugly" part: some tasks are being "re-organized" by removing logical dependencies that were making the overall execution too slow (e.g., slow tasks that were chained). …
> Testing heartbeat demo in CircleCI + some build performance optimization

- examples/heartbeat_demo/doctor.py
- nucypher/characters/lawful.py
- nucypher/config/storages.py
- nucypher/keystore/keypairs.py
- nucypher/network/middleware.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- nucypher/utilities/sandbox/middleware.py
- tests/conftest.py
- tests/learning/test_fault_tolerance.py
- tests/network/test_node_storage.py
Our test suite has failed to detect and prevent mistakes related to middleware logic lately.  This is largely because the middleware we use for testing, `MockRestMiddleware`, has shared too little logic with `RestMiddleware`.
This PR changes that by smashing nearly all the logic down into the latter while only overriding small, surgical components needed for testing.
It also gives middleware more of an "onion" shape, by cleaning both requests and responses. 
There was no explicit Issue for these problems; this PR continues the work of #721.  During this work, three related issues were closed:
* Fixes #669 
* Fixes #727 
* Fixes #728
> Middleware unsuckified.

- nucypher/blockchain/eth/sol/source/contracts/MiningAdjudicator.sol
- nucypher/blockchain/eth/sol/source/contracts/lib/UmbralDeserializer.sol
- nucypher/crypto/utils.py
- nucypher/network/server.py
- nucypher/policy/models.py
- tests/blockchain/eth/contracts/main/mining_adjudicator/test_mining_adjudicator.py
- tests/characters/test_bob_handles_frags.py
- tests/crypto/test_signature.py
The goal of this PR is to validate the KFrag signature on-chain, as part of the ZKP verification.
This was pending from #509. Specifically:
- It precomputes the necessary data to validate the signature, namely:
- The pre-hashed message. Pre-hashing has several benefits here: (1) reduced computations, (2) reduce space costs, (3) some data anonymity (we don't need to disclose `delegating_pubkey` and `receiving_pubkey`, which are part of the message).
- the `v` value that allows to recover a public key from a ECDSA signature.
- the signing public key (from Alice) as ETH address (since that's what the EVM's `ecrecover` actually recovers). This also prevents disclosing Alice's verifying public key directly, just the corresponding ETH address.
- Alice's ETH address now is signed by Bob and …
> Check KFrag signature as part of on-chain ZKP verification

- README.md
- docs/source/index.rst
- setup.py
This PR is just a basic UX improvement: Don't make people click on a secondary link (e.g., docs, whitepaper, website, etc) in order to learn about what is NuCypher. 
Other stuff in this PR:
- Fixes badges links and unify styles.
- Tries to fix bad render of Markdown text in pypi project description (see #794).
> Short summary of NuCypher in the README

- examples/postman/NuCypher.postman_collection.json
- examples/postman/README.md
- examples/postman/dev.postman_environment.json
I added the postman collection we used at ETHDenver to the /examples/postman and added a quick readme to describe the workflow
> Add postman collection and README for general workflow

- .bumpversion.cfg
- docs/source/conf.py
- nucypher/__about__.py
- Alice revoke interface and HTTP character control endpoint
- Token denomination management with `NU` and "NuNit"
- Stake management with `Stake` class
- Testnet token faucet (Felix)
- Initial "Slashing Protocol" documentation
- New banner art "NU" and "NuCypher"
- Updates to Web3 5.0.0a8
> Bump version: 0.1.0-alpha.20 → 0.1.0-alpha.21

- README.md
- docs/source/index.rst
* Slight touch to the README, since the very first sentence was a reference to Umbral and proxy re-encryption. Instead of saying *how* we do it (i.e., PRE), we should say *what* we do (i.e., E2E access control, etc).
* Switches coverall badge to codecov
> Updates README: Slight touch to first paragraph. Codecov badge

- nucypher/characters/control/controllers.py
- nucypher/characters/control/interfaces.py
- nucypher/characters/control/serializers.py
- nucypher/characters/control/specifications.py
- nucypher/characters/lawful.py
- nucypher/cli/characters/alice.py
- nucypher/crypto/utils.py
- nucypher/policy/models.py
- tests/characters/test_alice_can_grant_and_revoke.py
- tests/characters/test_character_control.py
1. Adds a function `construct_policy_id` in `nucypher.crypto.utils` to form a "policy ID".
- This is a Keccak hash of `label || bob_verifying_key`.
2. Modifies Alice's `active_policies` by having policies stored under the policy ID as a key.
3. Fixes controller endpoints to use label and bob's verifying key.
Please release after merging.
> Store active policies via a policy ID

- nucypher/characters/lawful.py
- nucypher/network/server.py
- tests/characters/conftest.py
- tests/characters/test_bob_handles_frags.py
- tests/characters/test_bob_joins_policy_and_retrieves.py
- tests/characters/test_character_control.py
- tests/fixtures.py
Bob previously had trouble retrieving twice.  Ursula raised an error instead of 404'ing if a KFrag was `NotFound`.  Both of these are fixed, as well as smoothing out the retrieval flow and adding some test logic.
Fixes #833 
Fixes #851 
Opened #892 
**Note**: Presently, even though Bob *can* retrieve multiple times, he does not pass `cache=True` to `retrieve(...)` in any of the control APIs, so he will still fail in this case.  If we determine that this is the sane default, I'll add it in this PR.  If more discussion is in order, it can be added later or as an option for dapp developers.
> Bob handles failure cases with a bit more tact

- nucypher/cli/actions.py
- nucypher/cli/characters/alice.py
- nucypher/cli/characters/bob.py
- nucypher/cli/characters/felix.py
- nucypher/cli/characters/moe.py
- nucypher/cli/characters/ursula.py
- nucypher/config/node.py
- nucypher/network/teachers.py
1. Adds a `TEACHER_NODES` constant dict with network domains as keys.
2. Sets the default network flag to `goerli-testnet`.
3. Modifies the `cli.actions.load_seednodes` function to use the `TEACHER_NODES` default via network domain.
- Raises a `KeyError` if the network domain specified has no teacher nodes specified for it.
4. `--teacher-uri` and `--network` are now basically optional for the testnet.
**Related Issue: https://github.com/nucypher/nucypher/issues/967**
> Clean startup

- docs/source/architecture/contracts.md
- nucypher/blockchain/economics.py
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/sol/source/contracts/Issuer.sol
- nucypher/blockchain/eth/sol/source/contracts/MinersEscrow.sol
- nucypher/blockchain/eth/sol/source/contracts/MiningAdjudicator.sol
- nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol
- nucypher/blockchain/eth/sol/source/contracts/UserEscrowProxy.sol
- nucypher/cli/characters/ursula.py
- nucypher/utilities/sandbox/constants.py
- nucypher/utilities/sandbox/ursula.py
- tests/blockchain/eth/contracts/contracts/MinersEscrowTestSet.sol
- tests/blockchain/eth/contracts/contracts/MiningAdjudicatorTestSet.sol
- tests/blockchain/eth/contracts/contracts/UserEscrowTestSet.sol
- tests/blockchain/eth/contracts/integration/test_intercontract_integration.py
- tests/blockchain/eth/contracts/main/miners_escrow/conftest.py
- tests/blockchain/eth/contracts/main/miners_escrow/test_miners_escrow.py
- tests/blockchain/eth/contracts/main/miners_escrow/test_miners_escrow_additional.py
- tests/blockchain/eth/contracts/main/miners_escrow/test_mining.py
- tests/blockchain/eth/contracts/main/miners_escrow/test_tracking.py
- tests/blockchain/eth/contracts/main/mining_adjudicator/test_mining_adjudicator.py
- tests/blockchain/eth/contracts/main/user_escrow/test_user_escrow.py
- tests/blockchain/eth/entities/actors/test_miner.py
- tests/blockchain/eth/entities/agents/test_miner_escrow_agent.py
- tests/blockchain/eth/entities/agents/test_user_escrow_agent.py
- tests/blockchain/eth/entities/deployers/test_economics.py
- tests/metrics/estimate_gas.py
Before this PR a staker can't be an intermediary contract (such as User Escrow) because contract can't sign anything (and we can't slash it). 
Now miner/staker can set worker who can confirm activity and doesn't matter how many intermediary contracts between worker and MinersEscrow.
Any suggestions on renaming "worker" are welcome.
`MinersEscrow` API cahnges:
* `lock` method no longer includes `mint` and `confirmActivity` methods
* `setWorker(address)` method - necessary to set worker before confirm activity
* `getWorkerByMiner(address)`
* `getMinerByWorker(address)`
* Only worker can call `confirmActivity()`
Also `MiningAdjudicator` uses `getMinerByWorker(address)` to get miner for slashing
> Separate worker role from miner/staker

- .circleci/config.yml
- scripts/circle/compare_reqs.sh
- scripts/installation/rebuild_pipenv.sh
Our requirements.txt and dev-requirements.txt files have undergone many massive but seemingly arbitrary revisions over the last few months, mostly depending on who the last person was to generate them.
This PR  adds a test in Circle which ensures that requirements files are generated by consistent methods.
Note:  It will also fail if sub-dependencies are updated without an accompanying update of reqs files.
I think this is probably a good thing.
> Standardize pip reqs files

- nucypher/cli/main.py
- tests/cli/test_mixed_configurations.py
1. Defenestrates the `nucypher remove` command from the CLI.
2. Closes #1096 
1. It deleted my home directory and now it must die.
> Defenestrate 'nucypher remove' from the CLI

- dev/docker/8-federated-ursulas.yml
- examples/finnegans_wake_demo/finnegans-wake-demo.py
- nucypher/characters/lawful.py
- nucypher/cli/characters/ursula.py
- nucypher/cli/main.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- tests/cli/test_mixed_configurations.py
- tests/cli/ursula/test_federated_ursula.py
Fixes #941 and also many of the issues that made it so difficult to track down the problem.
* Adds `--log-level` to top-level `nucypher` CLI interface.
* Adds a few key logging statements for understanding Ursula's early learning experience.
* Adds `--interactive` to `nucypher ursula ...` - `UrsulaCommandProtocol` now only launches if this flag is provided.
* Logs phantom nodes.
> Fixes debug docker problem.

- .circleci/config.yml
- pytest.ini
- tests/blockchain/eth/entities/actors/test_deployer.py
- tests/blockchain/eth/entities/agents/test_user_escrow_agent.py
- tests/blockchain/eth/entities/deployers/test_user_escrow_deployer.py
- tests/blockchain/eth/interfaces/test_chains.py
- tests/cli/test_deploy.py
Fix several `py.test` warnings that can obscure real ones from tests.
- Declare `slow` mark explicitly in `pytest.ini`
- Fix a typo: `pytest.mark.usesfixtures` -> `pytest.mark.usefixtures` (this actually makes these tests pass)
- Rename `TesterBlockchain` on import in tests to prevent `py.test` from trying to pick it up
> Fix `py.test` warnings

- .circleci/config.yml
Trims about 2 minutes off total CI build with potential for additional time savings each time docker is used for future tests.
> Speed up CI builds

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/cli/deploy.py
- nucypher/cli/stake.py
- nucypher/crypto/powers.py
- tests/blockchain/eth/clients/test_mocked_clients.py
- tests/blockchain/eth/entities/actors/test_stakeholder.py
- tests/characters/test_crypto_characters_and_their_powers.py
- tests/crypto/test_powers.py
Based on #1130 
Uses Agency and Deployer methods to deploy a single contract by it's registry name form the CLI.  This may act as a good secondary means of managing failed deployments as part of an automated series.
> "Resume" and single-contract deployments via CLI.

- nucypher/cli/characters/bob.py
Fix for issue #1138 , by replacing `make_control_transport()` with the new function. Also replaced the emitter with emit at Line:146 of nucypher/cli/characters/bob.py
> Fix for issue #1138

- nucypher/cli/characters/ursula.py
- nucypher/cli/painting.py
- nucypher/cli/stake.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
- Fix #1162: Bad suggestion in `nucypher ursula init`
- Fix #1160: Better account hint in `nucypher ursula init`
- Fix #1158: Help text for `nucypher stake`
- Fix #1142: Fail on `nucypher stake <bad-action>`
- Fix #1164: Fix `nucypher ursula confirm-activity`
- Implement `nucypher stake detach-worker`: Useful in case the staker wants to remove her current relationship with her worker (e.g., the worker has been compromised, the worker is in a corrupt setting, etc.)
> Minor CLI bug fixes for nucypher stake and nucypher ursula

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/characters/lawful.py
- nucypher/cli/actions.py
- nucypher/cli/characters/ursula.py
- nucypher/cli/deploy.py
- nucypher/cli/painting.py
- nucypher/cli/stake.py
- nucypher/crypto/powers.py
- nucypher/network/nodes.py
- tests/cli/test_deploy.py
- tests/cli/test_mixed_configurations.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
- tests/fixtures.py
_Based on #1146._
Tested with a local private chain, but mocking "goerli" (chain ID 5) in order to pass as a public chain (i.e., not local). 
In case you want to replicate, this is [my genesis file](https://gist.github.com/cygnusv/12ccfa3ae559530efe65645ae8629cb9). I ran the geth node with the following params: `--networkid 5 --nodiscover --verbosity 5 --mine --minerthreads=1`
Steps followed:
```
nucypher-deploy contracts --poa --provider file:///Users/david/dev/mi-genesis/geth.ipc
rm /Users/david/Library/Application\ Support/nucypher/stakeholder.json
nucypher stake new-stakeholder --provider ipc:///Users/david/dev/mi-genesis/geth.ipc  --poa --registry-filepath /Users/david/Library/Application\ Support/nucypher/contract_registry.json
nucypher stake accounts --no-sync
nucypher-deploy …
```
> CLI cleanup (vol. 2): Making CLI work with local non-dev private chain

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/deployers.py
- nucypher/cli/deploy.py
- nucypher/cli/painting.py
- tests/blockchain/eth/entities/deployers/conftest.py
- tests/blockchain/eth/entities/deployers/test_adjudicator_deployer.py
- tests/blockchain/eth/entities/deployers/test_interdeployer_integration.py
- tests/blockchain/eth/entities/deployers/test_policy_manager_deployer.py
- tests/blockchain/eth/entities/deployers/test_staking_escrow_deployer.py
- tests/blockchain/eth/entities/deployers/test_token_deployer.py
- tests/blockchain/eth/entities/deployers/test_user_escrow_deployer.py
Deploying NuCypher contracts during installation can take some time, so adding a progress bar would improve UX.
Note: deploying to a local blockchain will be much faster.
Example output from my testing
```
Press any key to continue
Deploying Contracts  [##----------------------------------]    7%  00:00:38
NuCypherToken (0x1e31e55280412d033E817a4eC04d07b34a006c21)
**********************************************************
OK | txhash | 0x4b6d009c2ec2b3f29571bb25c2e5126a4ae1857d1a785b78c20e8a12b2d5f73c (782882 gas)
Block #14 | 0xa5d1732c412b66ab8d3640ca62a8d3aa4b29d095142c84fd648df2a7f1580187
Press any key to continue
Deploying Contracts  [#############-----------------------]   38%  00:00:29
StakingEscrow (0x1E3452C1708fd8246D63a1119E866C52580deaA2) …
```
> UX: Add the ability to provide progress during NuCypher contract deployments

- deploy/services/felix_faucet.j2
- deploy/services/firstula_node.j2
- deploy/services/ursula_node.j2
- nucypher/blockchain/eth/policies.py
- nucypher/characters/control/serializers.py
- nucypher/network/server.py
- nucypher/policy/models.py
- scripts/local_fleet/run_local_fleet.sh
- scripts/local_fleet/run_local_ursula_fleet.py
- scripts/local_fleet/run_lonely_ursula.py
- scripts/local_fleet/run_single_ursula.py
It seems that the old issue of variable length ISO8601 dates (#906) was behind #1134.
For the record, this is the grant command that previously failed as in #1134, but now works after this fix:
```
nucypher alice grant --teacher-uri 127.0.0.1:11500 --bob-verifying-key 0277b5f24dbd68d4cdbbb9f54d6b892b52a48513695be4f703c2516a1f94e1dc9e --bob-encrypting-key 0277b5f24dbd68d4cdbbb9f54d6b892b52a48513695be4f703c2516a1f94e1dc9e --label asdf --expiration 2019-12-30T10:07:50Z --m 1 --n 1 --dev
```
Tested with a lonely dev ursula for the moment. The output seems to show everything is OK:
```
/ \  | (_) ___ ___
/ _ \ | | |/ __/ _ \
/ ___ \| | | (_|  __/
/_/   \_|_|_|\___\___|
the Authority.
WARNING: Running in Federated mode
treasure_map ...... …
```
> Fix #1134 and #906: Support variable length ISO8601 dates

- nucypher/cli/painting.py
The `Enactment` listing provides full date and uses local timezone. Fixes #1198 
```
███╗   ██╗██╗   ██╗
████╗  ██║██║   ██║
██╔██╗ ██║██║   ██║
██║╚██╗██║██║   ██║
██║ ╚████║╚██████╔╝
╚═╝  ╚═══╝ ╚═════╝
======================================= Active Stakes =========================================
| ~ | Staker | Worker | # | Value    | Duration     | Enactment
|   | ------ | ------ | - | -------- | ------------ | -----------------------------------------
| 0 | 0xAE8B | 0x0000 | 0 | 45000 NU | 56 periods . | Aug 09 14:27:49 EDT - Oct 03 14:27:49 EDT
```
> Improve format of stake enactment datetimes for stakes listing

- nucypher/blockchain/eth/interfaces.py
- tests/blockchain/eth/clients/test_mocked_clients.py
Allow `--provider` uri option to not require a scheme for files (`file://` or `ipc://`) on the cli. 
Without the scheme specified, this would allow for autcompletion of file paths in our cli when `--provider` is used.
> Auto-detect for file scheme provider uri

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/token.py
- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/cli/characters/ursula.py
- nucypher/config/node.py
- nucypher/config/storages.py
- nucypher/crypto/powers.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- nucypher/policy/policies.py
- nucypher/utilities/sandbox/ursula.py
- tests/blockchain/eth/entities/actors/conftest.py
- tests/blockchain/eth/entities/actors/test_staker.py
- tests/blockchain/eth/entities/actors/test_worker.py
- tests/characters/test_stakeholder.py
- tests/characters/test_ursula_prepares_to_act_as_mining_node.py
- tests/cli/test_mixed_configurations.py
- tests/cli/ursula/test_run_ursula.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
- tests/config/test_storages.py
- tests/conftest.py
- tests/crypto/test_powers.py
- tests/learning/test_fault_tolerance.py
Fixes #1279 - Known nodes are now lazily loaded from the disk at Character learning-time, instead of pre-init.
Fixes #1282 - ~~Sets geth keyring unlock time to 10 Years.~~ Unlocks and Relocks keyring between confirmations.
Fixes #1281 - Uses `WorkTracker` to perform activity confirmations
Fixes #1283 - Allow staking to maximum amount per address.
> Staking Process Relief

- .github/labeler.yml
- .github/workflows/label.yml
First test of Github Actions: for the moment I'd like to try the automatic PR labeler; initially I just defined some very basic labeling rules (found [here](https://github.com/nucypher/nucypher/pull/1287/files#diff-69a161780e8c3442ad32efea8760ff94)) based on which files are modified (e.g, if contracts are modified then the label "ETH Contracts" should automatically be added to the PR).
There are other cool GH actions out there but I just wanted to start with something simple.
> Github Actions: Automatic PR labeler

- .bumpversion.cfg
- docs/source/conf.py
- nucypher/__about__.py
Publication Build <https://circleci.com/workflow-run/04f7439b-0b82-4aae-8c02-7f40eda9e448>
> Bump version: 0.1.0-alpha.27 → 0.1.0-alpha.28

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/registry.py
- nucypher/blockchain/eth/sol/source/contracts/UserEscrow.sol
- nucypher/characters/control/emitters.py
- nucypher/cli/characters/stake.py
- nucypher/cli/deploy.py
- nucypher/cli/painting.py
- tests/blockchain/eth/entities/actors/test_deployer.py
- tests/blockchain/eth/entities/agents/test_user_escrow_agent.py
- tests/cli/test_deploy.py
Provides a minimal UX for `nucypher-deploy allocations`. Here's an [example of the allocation process](https://gist.github.com/cygnusv/611d5d2a54b64c9bd718cebc1593f7dd).
Steps to reproduce:
```
nucypher-deploy --provider /path/to/geth.ipc --poa inspect
(Download registry manually first and use it as input next)
nucypher-deploy --provider /path/to/geth.ipc --poa contracts --deployer-address 0xfoobar --contract-name UserEscrowProxy --registry-infile contract_registry.json
nucypher-deploy --provider /path/to/geth.ipc --poa inspect --registry-infile contract_registry.json
nucypher-deploy --provider /path/to/geth.ipc --poa allocations --allocation-infile allocations.json --registry-infile contract_registry.json
```
Steps 1 and 2 are needed only because our current testnet doesn't have a …
> Improve `nucypher-deploy allocations`

- docs/source/guides/staking_guide.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/registry.py
- nucypher/cli/actions.py
- nucypher/cli/characters/stake.py
- nucypher/cli/painting.py
- tests/blockchain/eth/entities/actors/test_staker.py
- tests/blockchain/eth/entities/agents/test_staking_escrow_agent.py
- tests/cli/test_deploy_commands.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
Co-Author: @cygnusv 
Fixes #1269, Includes extracted changes from #1227 
`nucypher stake restake --enable`
`nucypher stake restake --disable`
`nucypher stake restake --lock-until <PERIOD>`
```
$ nucypher stake restake --enable
____    __            __                      
/\  _`\ /\ \__        /\ \                     
\ \,\L\_\ \ ,_\    __ \ \ \/'\      __   _ __  
\/_\__ \\ \ \/  /'__`\\ \ , <    /'__`\/\`'__\
/\ \L\ \ \ \_/\ \L\.\\ \ \\`\ /\  __/\ \ \/ 
\ `\____\ \__\ \__/.\_\ \_\ \_\ \____\\ \_\ 
\/_____/\/__/\/__/\/_/\/_/\/_/\/____/ \/_/ 
The Holder of Stakes.                                      
======================================= Active Stakes =========================================
| ~ | Staker | Worker | # | Value    | Duration     | Enactment          
|   | ------ | …
```
> Restaking Control

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/registry.py
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/cli/actions.py
- nucypher/cli/deploy.py
- nucypher/cli/painting.py
- nucypher/utilities/sandbox/constants.py
- tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow_additional.py
- tests/blockchain/eth/entities/deployers/test_staking_escrow_deployer.py
- tests/cli/conftest.py
- tests/cli/test_cli_lifecycle.py
- tests/cli/test_deploy.py
- tests/cli/test_deploy_commands.py
- tests/cli/test_felix.py
- tests/cli/test_mixed_configurations.py
- tests/cli/test_status.py
- tests/cli/ursula/test_run_ursula.py
Deployment tooling and UX response to state verification failures experienced during `StakingEscrow` upgrade.  Provides a workflow to help mitigate a *partially* completed contract upgrade.
- Engagement of `_deploy_essential` without deploying a proxy any additional transactions via CLI (`--bare`).
- Proxy contract upgrade / retargeting without contract re-deployment (nucypher upgrade --retarget ...).
- Adds deployer methods for better direct-access to contracts both targeted and, untargeted by proxies.
- Allows for an alternate registry output file path to be used via depolyment CLI (`--registry-outfile`).
- Clean-up registry mocking and fixture usage.  (always use `MOCK_REGISTRY_FILEPATH`)
Based on #1345  and #1350 
without gas limit -> …
> Bare Deployment and Retargeting Workflow

- .circleci/config.yml
- pytest.ini
- tests/blockchain/eth/contracts/main/staking_escrow/test_sampling_distribution.py
- tests/conftest.py
* Adds support in our pytest config to the `@pytest.mark.nightly` marker, similar to  `@pytest.mark.slow` but for tests that are specifically designed for nightly builds.
* Uses this marker for running a more robust statistical test for sampling (Closes #1288)
* Schedules tests to run at **06:00 UTC** (08:00 CEST, 23:00 PDT).
* East coast nucypherinos should be sleeping
* West coast nucypherinos should be brushing their teeth
* European nucypherinos are snoozing the alarm for the third time
> Add @pytest.mark.nightly marker to specify nightly tests

- docs/source/glossary.rst
- docs/source/index.rst
While I'm playing with the docs for #1365, I figured we could add some initial work on a glossary that could be updated over time.
To reference the glossary term anywhere in the docs, you can use :term:\`Glossary Term\` - see https://sublime-and-sphinx-guide.readthedocs.io/en/latest/glossary.html.
Fixes #28 .
> Glossary Page for Docs

- docs/source/guides/staking_guide.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/decorators.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/registry.py
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/blockchain/eth/sol/source/contracts/UserEscrowProxy.sol
- nucypher/blockchain/eth/token.py
- nucypher/characters/lawful.py
- nucypher/cli/actions.py
- nucypher/cli/characters/stake.py
- nucypher/cli/painting.py
- nucypher/crypto/powers.py
- tests/blockchain/eth/contracts/integration/test_intercontract_integration.py
- tests/blockchain/eth/contracts/main/user_escrow/test_user_escrow.py
- tests/blockchain/eth/entities/actors/test_worker.py
- tests/blockchain/eth/entities/agents/test_user_escrow_agent.py
- tests/blockchain/eth/interfaces/test_decorators.py
- tests/cli/conftest.py
- tests/cli/test_deploy.py
- tests/cli/test_status.py
- tests/cli/ursula/test_stake_via_allocation_contract.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
The goal of this PR is to integrate UserEscrow with CLI staking (Closes #856)
```
nucypher stake create --escrow [--beneficiary-address 0xfoobar]
```
See the [staking guide](https://github.com/cygnusv/nucypher/blob/userescrow/docs/source/guides/staking_guide.rst#staking-using-a-preallocation-contract) for more information.
**Notes**
* You can use [this contract registry](https://gist.github.com/cygnusv/dfe16e5cb6a6570164eec78287dfaaf4) that includes an updated `UserEscrowProxy` deployment with the option `--registry-filepath PATH`.
* You need an allocation contract. Follow the instructions in #1319 .
* Changes to `UserEscrowProxy`:
* Fixes bug in `UserEscrowProxy` that prevented `UserEscrow` contracts from staking all their tokens
* Fixes signature mismatch in method …
> CLI staking via UserEscrow

- nucypher/network/status_app/base.py
- nucypher/network/status_app/moe.py
1. Improve colouring of graphs - uses auto-colour scaling based on values
2. Number of ticks for x-axis was wrong - one less than what was needed
3. Improved layout of nickname in the nodes table
> Darth-Moe Status Page Cleanup

- nucypher/config/keyring.py
- tests/config/test_keyring.py
After moving `keyring_root` to a hidden property, a `@property` decorated method was not created. Characters were never tested with a keyring, so the bug (https://github.com/nucypher/nucypher/issues/1412) was unnoticed.
This PR fixes the issue and tests if Alice can be created with a keyring
> Keyring update prevented character instantiation

- nucypher/blockchain/eth/clients.py
Haven't done any further digging into other issues that may exist on the "parity as an eth client" critical path, but thought I'd leave this PR here.
> Unable to unlock account parity client due to typo

- nucypher/cli/characters/alice.py
- nucypher/cli/characters/bob.py
- nucypher/cli/characters/enrico.py
- nucypher/cli/characters/felix.py
- nucypher/cli/characters/stake.py
- nucypher/cli/characters/ursula.py
- nucypher/cli/config.py
- nucypher/cli/deploy.py
- nucypher/cli/status.py
- tests/cli/conftest.py
- tests/cli/test_alice.py
- tests/cli/test_bob.py
- tests/cli/test_cli_lifecycle.py
- tests/cli/test_enrico.py
- tests/cli/test_felix.py
- tests/cli/test_help.py
- tests/cli/test_mixed_configurations.py
- tests/cli/ursula/test_federated_ursula.py
- tests/cli/ursula/test_run_ursula.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
Fixes #1286 .
In our current CLI setup we lay out all of the options for all commands even though some options only apply to specific "commands", and not to others. Furthermore, we can't do something like:
```
nucypher <character> <command> --help
```
and get specific help for that specific command.
One way for us to get around this could be to restructure our CLI commands a bit to instead use `click.group` and `click.command`. It would allow us to ensure that required options for a specific command/action are provided by specifying `required=True` for options tied to those specific commands/actions, or that options that aren't applicable to specific commands, can't be specified (a recurring example in our code is the `dev` option)
This would improve UX by providing more context-specific …
> Improve CLI commands to better detect invalid option/commands and provide context-specific help

- docs/source/guides/staking_guide.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/registry.py
- nucypher/blockchain/eth/token.py
- nucypher/blockchain/eth/utils.py
- nucypher/characters/lawful.py
- nucypher/cli/actions.py
- nucypher/cli/characters/stake.py
- nucypher/cli/deploy.py
- nucypher/cli/painting.py
- nucypher/crypto/powers.py
- nucypher/network/nodes.py
- nucypher/utilities/sandbox/constants.py
- tests/blockchain/eth/entities/deployers/test_deploy_preallocations.py
- tests/blockchain/eth/interfaces/test_decorators.py
- tests/blockchain/eth/interfaces/test_registry.py
- tests/cli/test_deploy_commands.py
- tests/cli/test_status.py
- tests/cli/ursula/test_stake_via_allocation_contract.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
- tests/fixtures.py
* `TransactingPower` now auto-detects that the account comes from a HW, using the data provided by geth endpoint `personal_listWallets`. Fix #1385. Fix #1128 
* Check min staking size when learning. Also accepts staking for next period, which makes possible creating a stake and running a discoverable Ursula in the same period. Closes #1115 
* Fix confusion between staked and locked+rewards. Fixes #1369 
* Fix lack of client account selection for `nucypher stake collect-reward`
* Complete CLI tests for staking via contracts, except for divide.
* Revamp output files of allocation process and how allocation users stake. Closes #1351 
* Fix datetimes printed by `nucypher stake`.
* `nucypher stake list` now only prints active stakes. Fixes #1418
> Auto-detect HW accounts in TransactingPower. Finalize basic staking via contract CLI functionality.

- nucypher/network/status_app/base.py
- nucypher/network/status_app/moe.py
Comments from @cygnusv in #963 :
> Cleanup of Moe Status Page regarding checksum, graphs, and states

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/registry.py
- tests/blockchain/eth/entities/deployers/test_deploy_preallocations.py
Command to use the allocation CLI:
```nucypher-deploy allocations --provider <PROVIDER> --poa  --allocation-infile <ALLOCATION_FILE>```
Example of allocation file in CSV:
```
"beneficiary_address","name","amount","duration_seconds"
"0x1715a31490371EBC469D775d6b384C354Be803C7","Aunt Irma",15000000000000000000,259200
```
Note you need those exact column names.
> Touchups to the CLI allocation process: support for CSV, bugfixes, etc.

- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/cli/characters/alice.py
- nucypher/cli/characters/stake.py
- nucypher/cli/characters/ursula.py
- nucypher/cli/status.py
- nucypher/config/characters.py
- nucypher/config/node.py
- nucypher/utilities/sandbox/blockchain.py
- tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow.py
- tests/blockchain/eth/entities/agents/test_staking_escrow_agent.py
- tests/blockchain/eth/interfaces/test_chains.py
- tests/cli/test_status.py
* Pagination for `getAllActiveStakers()` to mitigate problems with light node/client (geth/parity)
* Added "light" parameter to the blockchain interface
* Use "light" marker to get default pagination in `StakingEscrowAgent`
> Pagination for `getAllActiveStakers` method

- nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol
- nucypher/blockchain/eth/sol/source/contracts/WorkLock.sol
- nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PreallocationEscrow.sol
- nucypher/blockchain/eth/sol/source/zeppelin/utils/Address.sol
- tests/blockchain/eth/contracts/contracts/PolicyManagerTestSet.sol
- tests/blockchain/eth/contracts/contracts/ReentrancyTest.sol
- tests/blockchain/eth/contracts/main/policy_manager/test_policy_manager_operations.py
- tests/blockchain/eth/contracts/main/staking_contracts/test_preallocation_escrow.py
- tests/blockchain/eth/contracts/main/worklock/test_worklock.py
[EIP-1884](https://github.com/ethereum/EIPs/blob/dcc573e74adc0e6dd25821ddaabf862e8f85e107/EIPS/eip-1884.md)
Potential issue: 
Problem may appear in calling `someAddress.transfer(ethAmount)` because it uses fixed gas limit (2300). Transfering ETH to some contract executes fallback function which can consume more than 2300 gas and probability of exceeding gas limit becomes greater with EIP-1884. For our network it means that not every intermediary contract can withdraw ETH (policy reward, worklock refund) from our contracts.
Fix:
Instead of not adjustable `transfer()` function use `call("")` with all initial gas limit
> [APPROVED - DON'T MERGE YET] Fix potential problem with EIP-1884

- nucypher/network/nodes.py
Fixes #1519 - Patch to fix unhandled `NotStaking` exception raised in `Learner.remember_node`
Related to https://github.com/nucypher/nucypher/issues/567
> Tolerate non-staking nodes in storages; Handle NotStaking in learning

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/registry.py
- nucypher/blockchain/eth/sol/source/contracts/Issuer.sol
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/blockchain/eth/sol/source/contracts/WorkLock.sol
- nucypher/cli/deploy.py
- nucypher/utilities/sandbox/blockchain.py
- tests/blockchain/eth/contracts/base/test_issuer.py
- tests/blockchain/eth/contracts/contracts/IssuerTestSet.sol
- tests/blockchain/eth/contracts/contracts/StakingEscrowTestSet.sol
- tests/blockchain/eth/contracts/contracts/WorkLockTestSet.sol
- tests/blockchain/eth/contracts/integration/test_intercontract_integration.py
- tests/blockchain/eth/contracts/main/staking_escrow/conftest.py
- tests/blockchain/eth/contracts/main/staking_escrow/test_staking.py
- tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow.py
- tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow_additional.py
- tests/blockchain/eth/contracts/main/worklock/test_worklock.py
- tests/blockchain/eth/contracts/test_contracts_upgradeability.py
- tests/cli/test_deploy.py
- tests/fixtures.py
Included #1321 
Opens #1540, #1529, #1508
* Burn tokens in `StakingEscrow` (for future reward)
* Ability to burn remaining tokens in `WorkLock`
* Explicit initialization for `StakingEscrow` and `WorkLock`
* New function - `cancelBid`
* Tokens locked in `PreallocationEscrow` in `claim`
* Ability to change `WorkLock` address in `StakingEcrow` if test flag was set <-- (what do you think, is it ok?)
> WorkLock updates

- docs/source/guides/staking_guide.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PreallocationEscrow.sol
- nucypher/blockchain/eth/token.py
- nucypher/cli/characters/stake.py
- nucypher/cli/deploy.py
- nucypher/cli/painting.py
- nucypher/crypto/powers.py
- tests/blockchain/eth/contracts/main/staking_contracts/test_preallocation_escrow.py
- tests/blockchain/eth/entities/agents/test_token_agent.py
- tests/cli/test_deploy.py
* "Simplified" deployment of `PreallocationEscrow` contracts, using a SW controlled account (a.k.a _the Sidekick_) to handle the initial steps of deployment (contract creation). The funding & locking is still controlled by the main deployer account (IRL, a HW account).
* Uses `approveAndCall()` instead of `approve()` and an additional method for calling `token.safeTransferFrom()`. This reduces costs when depositing funds into `PreallocationEscrow` and `StakingEscrow`. Closes #1534 
* After applying previous measures, and tweaking the ordering of deployment steps,  the number of confirmations in the HW device when deploying a preallocation contract is reduced from 4 to 1.
> Dehydrate PreallocationEscrow deployment

- nucypher/blockchain/eth/interfaces.py
- nucypher/characters/control/emitters.py
- nucypher/cli/actions.py
- nucypher/cli/characters/alice.py
- nucypher/cli/characters/bob.py
- nucypher/cli/characters/enrico.py
- nucypher/cli/characters/felix.py
- nucypher/cli/characters/stake.py
- nucypher/cli/characters/ursula.py
- nucypher/cli/common_options.py
- nucypher/cli/config.py
- nucypher/cli/deploy.py
- nucypher/cli/status.py
- nucypher/config/node.py
- nucypher/utilities/logging.py
- tests/cli/test_help.py
- tests/cli/test_rpc_ipc_transport.py
- tests/cli/ursula/test_stake_via_allocation_contract.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
- tests/cli/ursula/test_ursula_command.py
- tests/conftest.py
A continuation of PR #1417, fixes #1431
- Moved repeating CLI options to a separate file
- Collected groups of options into objects to avoid long parameter lists
- Removed `etherscan` option from `config.py` - it is not used anywhere
- Moved `mock_networking` option from `config.py` to the characters that use it
- Got rid of `NucypherClickConfig` import in `CharacterConfiguration` constructor; fixes #1503 
- Removed assignments to `NucypherClickConfig` attributes which did nothing, and replaced these assignments with `GlobalLoggerSettings` method calls in `conftest.py`. **Note:** I'm assuming here that `NucypherClickConfig` was only used in CLI calls, which were all started with `click.invoke()` and therefore setting `NucypherClickConfig` attributes in the main process had no effect.
- …
> CLI options cleanup

- docs/source/architecture/contracts.md
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/blockchain/eth/utils.py
- nucypher/characters/control/interfaces.py
- nucypher/characters/control/serializers.py
- nucypher/characters/control/specifications.py
- nucypher/characters/lawful.py
- nucypher/config/characters.py
- nucypher/policy/policies.py
- tests/blockchain/eth/contracts/contracts/PolicyManagerTestSet.sol
- tests/blockchain/eth/contracts/contracts/StakingContractsTestSet.sol
- tests/blockchain/eth/contracts/contracts/StakingEscrowTestSet.sol
- tests/blockchain/eth/contracts/integration/test_intercontract_integration.py
- tests/blockchain/eth/contracts/main/policy_manager/test_policy_manager.py
- tests/blockchain/eth/contracts/main/policy_manager/test_policy_manager_operations.py
- tests/blockchain/eth/contracts/main/staking_escrow/test_staking.py
- tests/blockchain/eth/entities/agents/test_policy_manager_agent.py
- tests/blockchain/eth/entities/agents/test_preallocation_escrow_agent.py
- tests/blockchain/eth/entities/agents/test_sampling_distribution.py
- tests/characters/control/blockchain/conftest.py
- tests/cli/ursula/test_stake_via_allocation_contract.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
- tests/fixtures.py
- tests/metrics/estimate_gas.py
Based on #1470
Refs #1188 
Closes #1063 
Refs #1406
Refs #1492
| WARNING: Not upgradeable changes |
| --- |
* discrete payment for all policy periods: if policy starts today, ends tomorrow then fee must be for 2 periods
* flexible end timestamp
* Ursula pays more for confirmActivity (~15k-20k gas) to minimize Alice gas fee (save ~15k per node)
* split creator role into creator and owner
* revocation using owner's signature 
PolicyManager `v1.1.2` -> `v 2.1.1`
StakingEscrow `v1.4.1` -> `v2.1.1`
> Policy refactoring

- nucypher/blockchain/eth/sol/source/contracts/WorkLock.sol
- tests/blockchain/eth/contracts/contracts/WorkLockTestSet.sol
- tests/blockchain/eth/contracts/integration/test_intercontract_integration.py
- tests/blockchain/eth/contracts/main/worklock/test_worklock.py
Changes time-based lock for claimed tokens to stake-based lock (simply by removing PE and directly staking tokens inside `claim()` method)
I want to emphasize - it's not work-based lock because doesn't matter how many work will be produced by staker.
> Removing PE from WorkLock

- .bumpversion.cfg
- .circleci/config.yml
- docs/source/conf.py
- nucypher/__about__.py
Publication Build: https://circleci.com/workflow-run/24ef6d50-a454-48be-a3c8-d30c867132e3
(Manually completed failed docker steps over SSH and followed up with a hot-commit)
> Bump version: 2.0.0-beta.2 → 2.0.0-beta.3

- examples/finnegans_wake_demo/finnegans-wake-demo.py
- examples/populate_mario_box.py
- nucypher/characters/base.py
- nucypher/characters/control/interfaces.py
- nucypher/characters/lawful.py
- nucypher/cli/actions.py
- nucypher/crypto/kits.py
- nucypher/network/nodes.py
- nucypher/policy/collections.py
- nucypher/policy/policies.py
- nucypher/utilities/sandbox/middleware.py
- tests/characters/control/blockchain/conftest.py
- tests/characters/control/blockchain/test_rpc_control_blockchain.py
- tests/characters/control/blockchain/test_web_control_blockchain.py
- tests/characters/control/federated/conftest.py
- tests/characters/control/federated/test_web_control_federated.py
- tests/characters/test_alice_can_grant_and_revoke.py
- tests/characters/test_bob_handles_frags.py
- tests/characters/test_bob_joins_policy_and_retrieves.py
- tests/characters/test_specifications.py
- tests/characters/test_ursula_prepares_to_act_as_mining_node.py
- tests/cli/test_bob.py
- tests/cli/test_felix.py
- tests/cli/ursula/test_stake_via_allocation_contract.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
- tests/fixtures.py
*Summary*: Bob's adventure is now consistent with the assumptions throughout much of the rest of the codebase.  Specifically, in a single adventure: Bob can retrieve messages in any number of capsules, he can leave CFrags attached to Capsules either after activation or after an adventure that does not result in activation, and he can save WorkOrders in a replete form, both with completion metadata and the CFrag attached.
* Fixes #1359: `retrieve` now takes `*message_kits` and accounts for `Bob` adventuring with multiple `capsules`.
* Fixes #999: Bob can now learn "later" (instead of crashing) if a subsequent adventure leads him to a new Ursula.
* Fixes #934: If Bob has all the CFrags he needs (or an already activated Capsule), he does not engage in any network I/O at all (and thus, does …
> [EPIC] Birdcage: A PR for people who want to pretend to like Bob.

- nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- tests/blockchain/eth/contracts/contracts/PolicyManagerTestSet.sol
- tests/blockchain/eth/contracts/integration/test_intercontract_integration.py
- tests/blockchain/eth/contracts/main/policy_manager/test_policy_manager.py
- tests/blockchain/eth/contracts/main/policy_manager/test_policy_manager_operations.py
- tests/blockchain/eth/contracts/main/staking_escrow/test_staking.py
Fixes #1671
Problem possible reproduce only when grant happens in the same period as first deposit of node. Automaticaly it's impossible because `sampling()` returns only active node in the current period. But manually nothing prevents from the bug. 
This PR contains two fixes: 
* `register` and `createPolicy` check consistency of all nodes + `deposit` satisfies new conditions
* partially ignoring wrong state - that leads to losing some historical policy rewards
After fix all affected nodes will be able to `confirmActivity()`
Versions:
StakingEscrow `2.2.1` -> `2.2.2`
PolicyManager `2.1.1` -> `2.1.2`
> Fixes bug in PolicyManager #1671

- docs/source/guides/worklock_guide.rst
- docs/source/index.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/utils.py
- nucypher/characters/lawful.py
- nucypher/cli/actions.py
- nucypher/cli/commands/worklock.py
- nucypher/cli/main.py
- nucypher/cli/painting.py
- nucypher/cli/types.py
- nucypher/config/storages.py
- nucypher/network/nodes.py
- nucypher/policy/policies.py
- nucypher/utilities/sandbox/policy.py
- tests/cli/test_felix.py
- tests/cli/test_worklock_cli.py
* Makes `nucypher worklock` operative, since it had a series of minor bugs. 
* Successful `bid`, `cancel-bid` and `claim`
* Skeleton of WorkLock guide in the docs
* Added several TODOs throughout the codebase
* Some janitorial work here and there
Other:
* Fixes #1660 
* Fixes #1647
* Really closes #1346
> Fixes to `nucypher worklock`

- deploy/ansible/worker/include/check_running_ursula.yml
- deploy/ansible/worker/include/update_existing_ursula.yml
When restarting ursula after an update, EC2 nodes with 4GB of RAM occasionally spaz on scrypt/keychain decryptiont because of geth taking too much memory.
So lets stop geth and clear out some RAM before restarting ursula container.  This seems to solve it.
Also adds NuCypher version to status output
```
"MediumTurquoise Clock Purple Heart",
"nucypher version:      2.0.0-beta.5",
"staker address:        0xB1171EE4fd7E54ed960ccF9ECa383E0f3B1C6B06",
"worker address:        0x94fBC43fC56d7D3A3002E85C3575009316BcCcB9",
"rest url:              https://52.34.68.134:9151",
"missing_confirmations: 0",
"last active period:    18307",
"balances:",
"   ETH:                0.045739414712468285",
"   NU:                 0.0"
```
> improve ansible deployment/management/status

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/characters/control/interfaces.py
- nucypher/characters/lawful.py
- nucypher/characters/unlawful.py
- nucypher/network/middleware.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- nucypher/policy/collections.py
- nucypher/policy/policies.py
- nucypher/utilities/sandbox/policy.py
- tests/characters/control/blockchain/conftest.py
- tests/characters/control/blockchain/test_web_control_blockchain.py
- tests/characters/test_alice_can_grant_and_revoke.py
- tests/characters/test_freerider_attacks.py
- tests/fixtures.py
Closes #121 - presently our oldest open issue.
Ursula now checks both that there is a valid transaction placing the Policy in PolicyManager and also that she is specifically named as a Worker for the Policy.
**Introducing `Amonia`**, the unlawful sibling to `Alice`.
`Amonia` grants without paying, employing a number of tricks to try to sneak a Policy onto the network for free.
Other notes:
* The status code from the `enact()` middleware step is now composed on the `Arrangement`.
* `Alice` handles `UnexpectedResponse`, although additional elegance will be welcome when we're more focused on Alice.
* `Amonia's` freerider attacks are saved as `suspicious_activity` by `Ursula`.
* Breaks ground on events API by providing agent-level methods to get Policy and Arrangement metadata from a …
> Sorry Alice, your credit is strained far too thin.

- nucypher/cli/painting.py
As I was going through CASI Phase 3 noticed the following:
1. Justify text in WorkLock terms, and edit statement about servicing re-encryption work orders.
2. Ensure WorkLock capitalization is done for all text.
Sample:
```
In [23]: paint_bidding_notice(emitter, bidder)
* WorkLock Participant Notice *
-------------------------------
- By participating in NuCypher's WorkLock you are committing to operating a staking
NuCypher node after the bidding window closes.
- WorkLock token rewards are claimed in the form of a stake and will be locked for
the stake duration.
- WorkLock ETH deposits will be available for refund at a rate of 37403 wei
per confirmed period. This rate will become frozen on 2020-02-19 10:19:17-05:00.
- Once claiming WorkLock tokens, you are obligated to maintain a …
```
> Clean Up WorkLock Terms

- deploy/ansible/worker/include/init_worker.yml
- deploy/ansible/worker/include/run_geth.yml
- deploy/ansible/worker/include/update_existing_ursula.yml
When updating multiple machines, geth sync could take disparate amounts of time and cause the different nodes to actually _lose_ sync while waiting for a straggler.  Better to just restart them quickly.
> Ansible worker deploy tweak: Don't wait for geth sync if we are just updating the node

- nucypher/network/nodes.py
- tests/learning/test_fault_tolerance.py
1. Handles an `InvalidSignature` raised when a `Teacher` gives a `Learner` an improperly signed `node_payload`.
- Instead of raising, this will append the `node_payload` and the `signature` to `suspicious_activities_witnessed`.
2. Adds a test that checks for this case.
3. Resolves #1713
> Handle `InvalidSignatures` on receiving a `node_payload`

- .circleci/config.yml
Makes build go down from ~20 minutes to ~9.
* Don't do codecov in regular build; instead only do that in the nightly
* This is controlled by the `ENABLE_CODECOV` envvar, which exists in the nightly context, but doesn't in the regular context.
* Absorb `network` job into the `basics` job, as both or them are lightweight.
* This saves up 1 container
* Moves `test_build` job sooner in the pipeline, so it can run in parallel with other jobs.
* This reduces the build by ~3 minutes more.
> CircleCI optimization: codecov only in nightly & jobs rearrangement

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/deployers.py
- nucypher/cli/commands/deploy.py
- tests/blockchain/eth/entities/deployers/test_deploy_idle_network.py
- tests/blockchain/eth/entities/deployers/test_staking_escrow_deployer.py
- tests/cli/test_deploy_commands.py
Closes #1532.
Recipe to deploy a network in idle mode:
1. Deploy a NuCypher contract
```
nucypher-deploy contracts --contract-name NuCypherToken --provider $NUCYPHER_PROVIDER_URI --poa --registry-infile ...
```
2. Deploy a StakingEscrow in IDLE mode
```
nucypher-deploy contracts --contract-name StakingEscrow --mode idle --provider $NUCYPHER_PROVIDER_URI --poa --registry-infile ...
```
3. Deploy PolicyManager and Adjudicator
```
nucypher-deploy contracts --contract-name PolicyManager --provider $NUCYPHER_PROVIDER_URI --poa --registry-infile ...
nucypher-deploy contracts --contract-name Adjudicator --provider $NUCYPHER_PROVIDER_URI --poa --registry-infile ...
```
4. When you're ready, activate StakingEscrow
```
nucypher-deploy contracts --contract-name StakingEscrow --activate --provider …
```
> Allow to deploy a network in idle mode. Activate later

- Pipfile.lock
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/providers.py
- nucypher/cli/commands/alice.py
- nucypher/cli/commands/bob.py
- nucypher/cli/commands/deploy.py
- nucypher/cli/commands/stake.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/config.py
- nucypher/cli/types.py
- nucypher/config/node.py
- nucypher/utilities/logging.py
- nucypher/utilities/sandbox/blockchain.py
- requirements.txt
- tests/config/test_character_configuration.py
- Configurable and Inline gas strategies (`--gas-strategy`)
- Increase IPC Timeout to 600 seconds
- Relocks Dependencies
- Show HW Wallet prompts for all Transactions with gas price data
> Configurable Gas Strategy / Higher Timeouts / TX Prompts

- deploy/ansible/worker/inventory.yml
Not much is changed or is different than AWS, however default for azure users regardless of distribution is azureuser, you cannot deploy vms with base user root.
> update inventory to include azure deployments

- deploy/ansible/worker/include/setup_docker.yml
- deploy/ansible/worker/inventory.yml
This adds greater portability for users with mixed environments, allowing ansible to explicitly state which pip version to use. Ansible will typically default to 'python/pip' whichever is set beforehand but that may not be the case for remote hosts where we want to deploy workers.
> Forces ansible playbook to specifically use pip3 for python3

- docs/source/architecture/character.rst
- docs/source/architecture/sub_stakes.rst
- docs/source/guides/development/character_control_guide.rst
- docs/source/guides/development/development.rst
- docs/source/guides/network_node/network_node.rst
- docs/source/guides/network_node/staking_guide.rst
- docs/source/guides/network_node/ursula_configuration_guide.rst
- docs/source/guides/worklock_guide.rst
- docs/source/index.rst
- docs/source/support/faq.rst
- docs/source/support/troubleshooting.rst
Supplemental changes to #1781 .
Some extra comments regarding #829: 
1. I did not include `Will it be profitable/worthwhile run a network node?`  because I think we want to be careful answering such a question. 
2. I linked to our blog post article regarding "advantage over regular PKI" because it is a complicated answer and not easily written in a few lines - I think providing a more wholistic answer, as provided in the blog post is a better strategy.
> Documentation/FAQ Edits

- .bumpversion.cfg
- docs/source/conf.py
- nucypher/__about__.py
<https://app.circleci.com/pipelines/github/nucypher/nucypher/4095/workflows/5b6ba213-4abe-4f39-b486-9df8d52436a6>
> Bump version: 2.0.0-beta.11 → 2.1.0-beta.1

- docs/source/guides/network_node/ursula_configuration_guide.rst
Since `--staker-address` is no longer required it does not refer to anything.
> docs: remove <YOUR STAKER ADDRESS>

- Pipfile
- Pipfile.lock
- dev-requirements.txt
- docs/source/conf.py
- requirements.txt
Fixes #1854 (Should fix it (🤔 ))
1. Relock dependencies to update version of sphinx used
2. Recommonmark needed to be specified differently in the configuration
> Enable docs to build with latest version of sphinx

- nucypher/blockchain/eth/signers.py
Currently Ursula doesn't work with Clef signer because of wrong input/output types in `sign_message`:
- `message` must be passed as hexstring in RPC request
- output signature is expected to be `HexBytes` further down the line.
This pull request fixes that, and also adds Clef default path on Mac.
> Fix signing messages with Clef

- examples/heartbeat_demo/doctor.py
When running *doctor.py* from the _heartbeat_demo_ example, I've got an error
```
Traceback (most recent call last):
File "doctor.py", line 103, in <module>
alice_verifying_key=alices_sig_pubkey
TypeError: retrieve() got an unexpected keyword argument 'message_kit'
```
Since I'm using **2.1.0b2**, I've decided to had a look at the function definition [here](https://github.com/nucypher/nucypher/blob/2da817ae1a958a6c53e8738b31c48bfbaad0c94f/nucypher/characters/lawful.py#L680). From that, I did a little change and it worked.
> fix doctor.retrieve param in heartbeat_demo example

- nucypher/blockchain/eth/__init__.py
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/signers.py
- nucypher/characters/lawful.py
- nucypher/config/node.py
- tests/blockchain/eth/clients/test_keystore_signer.py
- tests/cli/ursula/test_ursula_local_keystore_cli_integration.py
Fixes #1921 Based on #1858 
- Support Ursula operation with a local private key provided by the user.
- Unit testing for `KeystoreSigner`
Try it out: `nucypher ursula config --signer keystore://<PATH TO GETH KEYSTORE>`
Needs manual CLI testing.
> Multi-account management for local keystore signers

- docs/source/glossary.rst
- docs/source/guides/development/cli_guide.rst
- docs/source/guides/development/getting_started.rst
- docs/source/guides/installation_guide.rst
- docs/source/guides/network_node/staking_guide.rst
- docs/source/guides/network_node/ursula_configuration_guide.rst
- docs/source/guides/worklock_guide.rst
- docs/source/index.rst
- docs/source/support/faq.rst
- docs/source/support/troubleshooting.rst
> Shut the FAQ up!

- .circleci/config.yml
- Pipfile
- Pipfile.lock
- dev-requirements.txt
- nucypher/blockchain/eth/sol/__conf__.py
- nucypher/blockchain/eth/sol/compile.py
- requirements.txt
- scripts/installation/install_solc.py
Fixes #1947, prerequisite for #1931 
Formally support py-solc-x <https://github.com/iamdefinitelyahuman/py-solc-x>
Deprecates <https://github.com/nucypher/py-solc>
> Deprecate nucypher py-solc fork; Use py-solc-x

- readthedocs.yml
Ensure that `nucypher` module is installed when building docs on RTD.
Follow-up to #1953 .
> `nucypher` module must be present to build APIs docs section

- dev/docker/Dockerfile
recent changes to install_solc require nucypher to be in path at invocation time.
> install nucypher before solc in dev/docker Dockerfile

- docs/source/guides/network_node/staking_guide.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol
- nucypher/blockchain/eth/sol/source/contracts/staking_contracts/StakingInterface.sol
- nucypher/cli/actions.py
- nucypher/cli/commands/deploy.py
- nucypher/cli/commands/multisig.py
- nucypher/cli/commands/stake.py
- nucypher/cli/commands/status.py
- nucypher/cli/painting.py
- tests/blockchain/eth/contracts/main/policy_manager/test_policy_manager.py
- tests/blockchain/eth/entities/actors/test_deployer.py
- tests/blockchain/eth/entities/actors/test_staker.py
- tests/blockchain/eth/entities/agents/test_policy_manager_agent.py
- tests/blockchain/eth/entities/deployers/test_policy_manager_deployer.py
- tests/cli/test_status.py
- tests/cli/ursula/test_stakeholder_and_ursula.py
- tests/fixtures.py
Follow on from #1959 
`MinFeeRateRange` -> `FeeRateRange`
`min_fee_rate_range` -> `fee_rate_range`
etc 
Use of _min_ is a bit misleading when the variable comprises a fixed, universal maximum, minimum and default rate (also referred to as the "global fee range"). Furthermore, stakers must choose their own _minimum_ acceptable fee rate, which must fall within the global fee range, and so unnecessary name similarities may cause unnecessary confusion.
> Removal of 'min' from fee range & more informative/consistent comments 

- docs/source/guides/installation_guide.rst
Separate `nucypher` requirements from Ethereum node requirements.
Fixes #1598
> Clarify System Requirements

- nucypher/blockchain/eth/providers.py
- nucypher/characters/control/controllers.py
- nucypher/characters/unlawful.py
- nucypher/cli/options.py
- nucypher/exceptions.py
- scripts/local_fleet/run_single_ursula.py
- tests/test_package.py
- Clears blockage for PR #1931 
- Introduces new exception and module: `nucypher.exceptions.DevelopmentInstallationRequired`
- Introduces new tests module `test_package.py` describing lazy imports for tests entities
- Ensures imports to `tests` are lazy as possible and crash with import context if the tests package is missing.  This is especially relevant in 4 distinct situations:
- Calling `Valdimir.from_target_ursula`
- Calling `_get_pyevm_test_backend`
- Calling `JSONRPCController.test_client`
- Handling the `--mock-networking/-Z` CLI flag for `MockRestMiddleware` in `process_middleware`
> Support for missing tests package

- nucypher/blockchain/eth/signers.py
- nucypher/cli/commands/ursula.py
- tests/blockchain/eth/clients/test_keystore_signer.py
- tests/cli/functional/conftest.py
- tests/cli/functional/test_ursula_local_keystore_cli_functionality.py
- tests/cli/ursula/test_local_keystore_integration.py
Simple bugfix / feature enhancement to keystore signer (related to issue #1962).
Path given to keystore signer is stat'd and:
- if it is a directory, it is scanned and regular directory entries are processed
- if it is a regular file, it is processed
- if something else (i.e. device node, etc.), an exception is raised
Additionally during directory scanning, OSError exceptions (such as permission error, etc.) are appended to InvalidSignerURI exception text and raised.
> Correct path handling in keystore signer / support individual files

- tests/blockchain/eth/contracts/main/staking_escrow/test_staking_escrow_additional.py
Seems to be a typo in tests. The assertions as they are are always true, and generate pytest warnings.
> Check the actual boolean values instead of asserting a non-empty tuple

- .circleci/config.yml
Makes codecov accurate. Use codecov CI orb flag for coverage report aggregation and upload.
From this PR.
<https://codecov.io/gh/nucypher/nucypher/tree/f87194ebca285a299227f1b5ff6c3f5f93850eca>
Multiple uploads (one per workflow step) via circleci orb parameters
<https://codecov.io/gh/nucypher/nucypher/commit/f87194ebca285a299227f1b5ff6c3f5f93850eca/build>
Under the Hood:
<https://docs.codecov.io/docs/flags>
CircleCI setting the example:
> We then upload the coverage data from all three test runs using the flags macos, windows, and linux. Codecov is then able to combine the three reports into a single report to give us an overall code coverage metric for the build.
<https://circleci.com/blog/circleci-config-teardown-how-we-write-our-circleci-config-at-circleci/>
> Fix Codecov / CircleCI Integration

- nucypher/config/node.py
- pytest.ini
- tests/cli/test_deploy_commands.py
- tests/fixtures.py
- tests/utils/blockchain.py
* Remove a `print()` seemingly left from debugging.
* Remove a duplicate `agency_local_registry()` fixture
* Add `junit_family=xunit1` to `pytest.ini` to avoid deprecation warnings
* Mark `TesterBlockchain` as a non-test class to avoid pytest warnings
* Fix a warning message in `CharacterConfiguration` constructor
> Small test fixes

- .bumpversion.cfg
- docs/source/conf.py
- nucypher/__about__.py
- tests/integration/cli/test_worklock_cli_functionality.py
The TODO in the included fix is associated with https://github.com/nucypher/nucypher/issues/1984#issuecomment-635024691
> Bump version: 2.1.0-beta.8 → 2.1.0-beta.9

- tests/acceptance/cli/ursula/test_federated_ursula.py
- tests/acceptance/cli/ursula/test_run_ursula.py
- tests/constants.py
- tests/fixtures.py
- tests/integration/cli/actions/test_auth_actions.py
- tests/integration/cli/actions/test_config_actions.py
- tests/integration/cli/actions/test_confirm_actions.py
- tests/integration/cli/actions/test_select_client_account.py
- tests/integration/cli/actions/test_select_client_account_for_staking.py
- tests/integration/cli/actions/test_select_config_file.py
- tests/integration/cli/actions/test_select_network.py
- tests/integration/cli/actions/test_select_stake.py
- tests/integration/cli/test_worklock_cli_functionality.py
- tests/integration/config/test_character_configuration.py
- tests/integration/conftest.py
- tests/mock/io.py
- add `mock_stdin` fixture to directly mock `input()`/`getpass()` instead of mocking `click` functions - fixes #2021
- use `capsys` instead of `mock_stdout` - fixes #2006 
- rename `YES`/`NO` in `tests.constants` to `YES_ENTER`/`NO_ENTER` (to distinguish them to just `YES`/`NO` without the linebreak
> IO test fixtures change: mock stdin directly instead of `click` functions, use `capsys` for stdout

- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/decorators.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/events.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/sol/compile.py
- nucypher/characters/base.py
- nucypher/characters/control/specifications/exceptions.py
- nucypher/cli/commands/stake.py
- nucypher/cli/config.py
- nucypher/crypto/kits.py
- nucypher/crypto/splitters.py
- nucypher/network/nodes.py
- nucypher/types.py
- setup.py
- tests/acceptance/blockchain/agents/test_preallocation_escrow_agent.py
- tests/acceptance/blockchain/agents/test_staking_escrow_agent.py
- tests/acceptance/blockchain/agents/test_token_agent.py
- tests/acceptance/cli/test_deploy.py
- Introduces types and rich annotations in `agents.py` and peripheral code entities reflecting contract APIs.  
- Models custom types after contract stucts. 
- Introduces new module `nucypher.types`.
- Renames `EthereumContractAgent.registry_contract_name` -> `EthereumContractAgent.contract_name`.
Fixes #1348 
PEP 484
PEP 593
PEP 526
@vzotova @fjarri @cygnusv
> Typing for Contract Agents

- nucypher/blockchain/eth/sol/source/contracts/MultiSig.sol
- nucypher/blockchain/eth/sol/source/contracts/proxy/Dispatcher.sol
- nucypher/blockchain/eth/sol/source/contracts/staking_contracts/AbstractStakingContract.sol
- tests/contracts/base/test_dispatcher.py
- tests/contracts/contracts/ReentrancyTest.sol
- tests/contracts/contracts/StakingContractsTestSet.sol
- tests/contracts/contracts/proxy/ReceiveFallbackTestSet.sol
Fixes #1809
Now `Dispatcher` has two functions to handle requests: `receive` and `fallback`, but behaviour remains unchanged. Separate `receive` makes ETH transfer cheaper because less logic inside, also this solves warning from compiler.
This PR does not require to hard fork of any current deployments
> `receive()` function in contracts

- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/multisig.py
- tests/acceptance/blockchain/deployers/test_staking_escrow_deployer.py
Some upstream library/protocol change changed the structure of the transaction AttributeDict and broke our  `fetch_arrangement_addresses_from_policy_txid` method.
This commit fixes that.
> Correct usage of TxReceipt.data during grant

- dev/docker/Dockerfile
- docs/source/guides/development/getting_started.rst
- examples/populate_mario_box.py
- nucypher/characters/control/controllers.py
- nucypher/characters/control/interfaces.py
- nucypher/characters/control/specifications/enrico.py
- nucypher/characters/control/specifications/fields/__init__.py
- nucypher/characters/control/specifications/fields/file.py
- nucypher/characters/control/specifications/fields/signature.py
- nucypher/characters/lawful.py
- nucypher/cli/commands/bob.py
- nucypher/cli/commands/enrico.py
- nucypher/network/middleware.py
- nucypher/utilities/prometheus/metrics.py
- tests/acceptance/characters/control/test_rpc_control_blockchain.py
- tests/acceptance/characters/control/test_web_control_blockchain.py
- tests/acceptance/cli/ursula/test_stake_via_allocation_contract.py
- tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py
- tests/integration/characters/control/conftest.py
- tests/integration/characters/control/test_web_control_federated.py
- tests/integration/characters/federated_encrypt_and_decrypt.py
- tests/unit/test_bytestring_types.py
Bare minimum support of enrico encrypting files via CLI and sending them to an IPFS gateway in time for an active hackathon.
- Encryption of files via `nucypher enrico encrypt --file <PATH> ...`
- Simple upload of message kits to ipfs with `nucypher enrico --ipfs <GATEWAY>`
- Simple retrieval of message kits from IPFS ipfs via CID `nucypher bob retireve --ipfs <GATEWAY> ... --message-kit <CID>`
> Simple Enrico file encryption

- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/blockchain/eth/sol/source/contracts/staking_contracts/StakingInterface.sol
- tests/contracts/contracts/StakingContractsTestSet.sol
- tests/contracts/contracts/StakingEscrowTestSet.sol
- tests/contracts/integration/test_intercontract_integration.py
- tests/contracts/main/staking_contracts/test_staking_interface.py
- tests/contracts/main/staking_escrow/conftest.py
- tests/contracts/main/staking_escrow/test_staking.py
- tests/contracts/main/staking_escrow/test_staking_escrow.py
- tests/contracts/main/staking_escrow/test_staking_escrow_additional.py
- tests/metrics/estimate_gas.py
Refs #1422 
Fixes #1419
Fixes #1933
Refs #1766
Refs #2015
* `StakingEscrow` code size optimization
* Staker for contract is who has tokens or not rewarded periods
* Auto unbond worker when last portion of NU is withdrawn
* New functions to deposit and lock tokens to existing sub-stake (even if value less than minimum)
* New function to merge two sub-stakes
> Updates for staker in StakingEscrow

- docs/source/guides/network_node/staking_guide.rst
- docs/source/guides/network_node/ursula_configuration_guide.rst
- nucypher/cli/commands/stake.py
- nucypher/cli/literature.py
- nucypher/cli/painting/worklock.py
> Variety of cleanup work related to docs/cli output for setting up staker and worker

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/token.py
- nucypher/cli/actions/select.py
- nucypher/cli/commands/stake.py
- nucypher/cli/literature.py
- nucypher/cli/painting/staking.py
- tests/acceptance/blockchain/interfaces/test_token_and_stake.py
- tests/acceptance/characters/test_stakeholder.py
- tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py
- tests/integration/blockchain/test_token_and_stake.py
- tests/integration/cli/actions/test_select_client_account.py
- tests/integration/cli/actions/test_select_client_account_for_staking.py
- tests/integration/cli/actions/test_select_stake.py
- tests/integration/cli/test_stake_cli_functionality.py
Fixes #2113
Fixes #2116
Fixes #1657 
Fixes #1696 
* Adds status for sub-stake
* Simplifies sub-stake selection
* Splitted `StakeHolder.assimilate()` into two methods 
* More tests
> Some fixes for `stake` commands

- docs/source/architecture/worklock.rst
- docs/source/guides/worklock_guide.rst
- nucypher/cli/commands/worklock.py
- nucypher/cli/literature.py
- nucypher/cli/painting/worklock.py
- tests/acceptance/cli/test_worklock_cli.py
- tests/integration/cli/test_worklock_cli_functionality.py
Fix terminology around WorkLock:
* bid -> escrow
* bidder -> participants
* distribution/portion -> allocation
* distribute -> allocate
* token distribution -> network node setup
* remove instances of `tokens`
> Update WorkLock terminology

- nucypher/blockchain/eth/agents.py
- tests/mock/agents.py
Mock.reset_mock() doesn't do that by default so return values remained between test modules
> Restore default return values in mock agents

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/network/nodes.py
- nucypher/policy/policies.py
- tests/acceptance/blockchain/agents/test_policy_manager_agent.py
- tests/acceptance/blockchain/agents/test_sampling_distribution.py
- tests/acceptance/blockchain/agents/test_staking_escrow_agent.py
More logical weighted sampling for stakers, with the sampler extracted to a separate class for the ease of unit testing. `additional_ursulas` and `attempts` parameters removed from `sample()`.
The second commit makes exposes the staker sampler as an iterator-like object. `BlockchainPolicy.sample_essential()` now works as follows:
- `quantity` stakers is needed
- Get the stakers reservoir based on the list of stakers returned by the contract (excluding `handpicked_ursulas` right away)
- Draw `quantity` of stakers, see which ones are already known, and send the rest to the learner
- Wait a little, check for newly known nodes. If it's still not enough (some nodes are being checked), draw more stakers from the reservoir and send them to the learner.
- Loop until time is expired or we have …
> Simplify staker sampling

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/blockchain/eth/sol/source/contracts/WorkLock.sol
- nucypher/cli/commands/deploy.py
- nucypher/cli/literature.py
- tests/acceptance/blockchain/actors/test_deployer.py
- tests/acceptance/blockchain/agents/test_staking_escrow_agent.py
- tests/acceptance/cli/test_deploy_commands.py
- tests/contracts/contracts/StakingEscrowTestSet.sol
- tests/contracts/contracts/WorkLockTestSet.sol
- tests/contracts/integration/test_intercontract_integration.py
- tests/contracts/main/staking_escrow/test_staking_escrow.py
- tests/contracts/main/staking_escrow/test_staking_escrow_additional.py
- tests/metrics/estimate_gas.py
* special method in `StakingEscrow` for depositing tokens from `WorkLock`
* force re-stake lock in `claim` and `batchDeposit`
* removed one slashing test from intercontract test because it's hard to maintain and there is already one test fro this there
* `onlyOwner` modifier for `batchDeposit` method to protect force lock from malicious using
> WorkLock: `restake` lock while claiming tokens

- .circleci/config.yml
This PR facilitates reproducing test runs between CI and local. It simply stores in a text file the list of tests that are executed for each parallel container, so you can just copy-paste locally if you want to reproduce. This text file is stored in the "Artifacts" tab of each job.
> CI: Saving as artifacts the name of the tests to run after splitting 

- nucypher/blockchain/eth/events.py
- nucypher/blockchain/eth/utils.py
- nucypher/cli/commands/status.py
- nucypher/cli/commands/ursula.py
- nucypher/config/constants.py
- nucypher/utilities/prometheus/collector.py
- nucypher/utilities/prometheus/metrics.py
- tests/acceptance/cli/ursula/test_run_ursula.py
- tests/unit/test_blockchain_utils.py
- tests/unit/test_prometheus.py
Some node providers limit the number of blocks for which events can be checked in one call. The smallest I've heard of so far is alchemy with 1000. Without limiting the number of blocks and iterating the calls, the one filter query will fail.
Example
```
File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/eth.py", line 498, in getFilterLogs
RPC.eth_getFilterLogs, [filter_id],
File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/manager.py", line 153, in request_blocking
raise ValueError(response["error"])
ValueError: {'code': -32600, 'message': 'Requested block range for eth_getLogs is greater than the limit of 1000 blocks. Please reduce range and retry.'}
```
This PR has limited scope relative to #2239. …
> Batch/Throttle events filter results 1000 (default) blocks at a time for CommitmentMade prometheus metrics collector

- nucypher/blockchain/eth/actors.py
- tests/acceptance/cli/test_mixed_configurations.py
- tests/acceptance/cli/ursula/test_run_ursula.py
Fixes #2247 .
Sample output:
```
Checking worker settings: waiting for bonding and funding ...
ⓘ Worker not fully started - still waiting for bonding and funding ...
ⓘ Worker not fully started - still waiting for bonding and funding ...
ⓘ Worker not fully started - still waiting for bonding and funding ...
ⓘ Worker not fully started - still waiting for bonding and funding ...
```
```
Checking worker settings: waiting for bonding and funding ...
✓ Worker is funded with 0.1 ETH!
ⓘ Worker not fully started - still waiting for bonding ...
```
Open question to reviewers - is providing the feedback about `still waiting` every 60s too short...? I don't want to make it too long since users may remain unaware.
> Provide periodic feedback to user about still waiting for bonding and funding

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/decorators.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/token.py
- nucypher/characters/lawful.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/processes.py
- tests/acceptance/blockchain/agents/test_policy_manager_agent.py
- tests/acceptance/blockchain/agents/test_preallocation_escrow_agent.py
- tests/acceptance/blockchain/agents/test_staking_escrow_agent.py
- tests/acceptance/cli/test_worklock_cli.py
- tests/acceptance/cli/ursula/test_local_keystore_integration.py
* Immediate help for issues that cause nodes to crash
* Don't leave the cursor hanging, polling the provider for a receipt and confirmations.  
* Allows the work tracker to track transaction hashes instead of receipts, by broadcasting commitment transactions when they are indicated by the staking contract without waiting for a receipt.
* Removes default work tracker qualification callable until #2277 is resolved. (`__requirement`)
* Advances #2070 #1852 #2141 
Additional follow-up in #2141
> Commit without haste

- examples/run_demo_ursula_fleet.py
- nucypher/characters/base.py
- nucypher/config/storages.py
- nucypher/network/nodes.py
- tests/fixtures.py
- tests/integration/config/test_storages.py
- tests/integration/learning/test_domains.py
This PR demonstrates that currently it's possible to learn about nodes from a different domain when they are recovered from storage, which can happen for example when a staker reuses the configuration from a testnet. It then fixes it by introducing a simple domain check when restoring nodes from disk, ignoring nodes that don't belong to current domain.
Closes #1843 
Closes #1623
> Improving restoration of store nodes metadata

- nucypher/characters/lawful.py
- nucypher/network/server.py
- tests/conftest.py
- tests/fixtures.py
- tests/integration/conftest.py
- tests/integration/network/test_network_upgrade.py
- tests/mock/performance_mocks.py
Fixes #2172
The problem is not caused by the DB size (see the comments in the issue), but persistent `Datastore` objects. Fixing that is the main purpose of the PR. Reduced DB size is not relevant - LMDB files are dynamic anyway (although one could argue that the reduced DB size still helps catch some errors).
What it does:
- changes `make_rest_app()` to not retain a reference to `Ursula` or the created datastore in the returned REST app object, **now it is the caller's responsibility;**
- adds a cleanup method to `Ursula`, to be used in fixtures. Weakrefs will make sure the datastore is cleaned up if all references to `Ursula` is released, but that may not be the case in tests, so an explicit method is needed.
- removes the DB size reduction fixture. It doesn't affect file sizes, and …
> Make sure datastores are not retained in tests

- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/blockchain/eth/sol/source/contracts/staking_contracts/StakingInterface.sol
- tests/contracts/contracts/StakingContractsTestSet.sol
- tests/contracts/integration/test_intercontract_integration.py
- tests/contracts/main/staking_contracts/test_staking_interface.py
- tests/contracts/main/staking_escrow/test_staking_escrow.py
- tests/contracts/main/staking_escrow/test_staking_escrow_additional.py
* deposits  from worklock allowed only after initialization
* `setSnapshots` method for `StakingInterface`
* check snapshots in `batchDeposit`
* allow `setWindDown` without deposit
> Some contract updates

- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/providers.py
- nucypher/blockchain/middleware/__init__.py
- nucypher/blockchain/middleware/retry.py
- tests/unit/test_web3_clients.py
- tests/unit/test_web3_middleware.py
> Add default retry functionality to EthereumClients

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/deployers.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/registry.py
- nucypher/cli/commands/deploy.py
- nucypher/cli/commands/status.py
- nucypher/cli/literature.py
- nucypher/cli/options.py
- nucypher/cli/painting/deployment.py
- nucypher/cli/utils.py
- tests/acceptance/blockchain/deployers/test_policy_manager_deployer.py
- tests/acceptance/blockchain/deployers/test_preallocation_escrow_deployer.py
- tests/acceptance/blockchain/deployers/test_staking_escrow_deployer.py
- tests/acceptance/blockchain/interfaces/test_chains.py
- tests/acceptance/cli/test_deploy.py
- tests/acceptance/cli/test_deploy_cli.py
- tests/acceptance/cli/test_deploy_commands.py
- tests/contracts/test_contracts_upgradeability.py
Co-Author: @derekpierre 
- Support block confirmations for upgrade, re-targeting, rollback, etc.
- Display current contract version numbers with `inspect` command
- Eager "Pre-flight" checks for upgrade CLI 
- Deprecated `nucypher deploy transfer tokens`
- Deprecates automated deployment series test (needs further actor-level deprecation)
> Confirmations and pre-flight for upgrade CLI

- nucypher/blockchain/eth/events.py
- nucypher/cli/commands/stake.py
- nucypher/utilities/prometheus/collector.py
- tests/unit/test_blockchain_events.py
This facilitates the use of http(s) for infura to get events as opposed to getting the following error message:
```
ValueError: {'code': -32601, 'message': 'The method eth_newFilter does not exist/is not available’}
```
Fixes #2291 .
Related to #1670
> Use stateless getLogs() rpc instead of event filters across codebase

- nucypher/blockchain/eth/actors.py
- nucypher/cli/commands/stake.py
- nucypher/cli/literature.py
- tests/integration/cli/test_stake_cli_functionality.py
> Allow --from-unlocked flag to specify when only uncollected staking rewards and unlocked substakes are used for creating/increasing a stake.

- nucypher/acumen/nicknames.py
- nucypher/acumen/perception.py
- nucypher/blockchain/eth/actors.py
- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/cli/painting/nodes.py
- nucypher/cli/painting/status.py
- nucypher/config/storages.py
- nucypher/network/nodes.py
- nucypher/network/templates/basic_status.j2
- nucypher/utilities/prometheus/collector.py
- tests/acceptance/characters/test_ursula_web_status.py
- tests/acceptance/network/test_network_actors.py
- tests/integration/learning/test_learning_upgrade.py
*Edit:* the scope of this PR has been limited to get done with public-visible changes first. Can't change the branch name, but it still kinda works.
* use a `Nickname` class to encapsulate nickname data instead of passing around tuples of tuples
* use NATO phonetic alphabet instead of Unicode glyphs for nicknames (to avoid problems with glyph representation in different fonts)
To get a few more bits in the nickname, we can add Æ and Þ (since they have convenient words to match with in English). 
**For reviewers:** please pay specific attention to correct serialization/deserialization. I'm not 100% sure I looked through all the instances where it happens.
> Nickname refactoring & changing nickname symbols to more common ones

- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/sol/__conf__.py
- nucypher/blockchain/eth/sol/source/contracts/PolicyManager.sol
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- tests/contracts/contracts/PolicyManagerTestSet.sol
- tests/contracts/contracts/StakingEscrowTestSet.sol
- tests/contracts/integration/test_intercontract_integration.py
- tests/contracts/main/policy_manager/test_policy_manager.py
- tests/contracts/main/policy_manager/test_policy_manager_operations.py
- tests/contracts/main/staking_escrow/test_staking.py
- tests/contracts/main/staking_escrow/test_staking_escrow.py
Result for now: -6k gas, +92 bytes
Allow `claim` from `WorkLock` before `StakingEscrow` initialization
> One more time: `commitToNextPeriod` gas optimizations

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/signers/software.py
- nucypher/cli/commands/stake.py
- Attempt to fix #2337 by using an overestimation of 50% for the gas limit when committing to next period.
- Fixes wrong password handling in `nucypher stake` when using Trezor as a signer
> Introduce gas limit overestimation. Fixes to `nucypher stake` password handling with Trezor. 

- nucypher/acumen/perception.py
- nucypher/network/nodes.py
- nucypher/network/templates/basic_status.mako
* Fixes #2368 (NO_FLEET_STATE_AVAILABLE and related issues). I was taking the current state info from the attributes set by `update_snapshot()`, while the most recent one is actually contained in `.known_nodes`. 
* Displays the correct state population.
* Displays the total number of known nodes (as @cygnusv suggested).
* Spaces out nickname symbols a little (thanks, @jMyles).
Before:
After:
> Status page fixes

- .circleci/config.yml
At the moment we have to update `docs-dependencies.txt` manually, so sometimes inconsistent deps might creep in. ReadTheDocs uses the new `pip` dependency resolution scheme (https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020) which is strict about that, so if that happens, the `build_docs` CI task passes, but the RTD build fails. This PR makes `build_docs` just as strict.
Case in point: CI for this PR fails at the moment exactly because docs-deps are inconsistent (fixed in PR #2381)
*Edit:* now that I rebased it after the merge of #2381, it should build properly.
> Check for inconsistent dependencies on docs build

- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/clients.py
- tests/acceptance/blockchain/agents/test_policy_manager_agent.py
- tests/acceptance/blockchain/agents/test_preallocation_escrow_agent.py
- tests/acceptance/cli/ursula/test_stake_via_allocation_contract.py
- tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py
- tests/contracts/integration/test_intercontract_integration.py
- tests/contracts/main/policy_manager/test_policy_manager.py
- tests/contracts/main/policy_manager/test_policy_manager_operations.py
- tests/contracts/main/worklock/test_worklock.py
- tests/fixtures.py
- tests/metrics/estimate_gas.py
- tests/mock/agents.py
- tests/utils/blockchain.py
`web3` was bumped from `5.12.1` to `5.12.2` in commit ad7935c725df. Evidently, they changed their method calls to some generalized `Method` class, so it is very strict about positional arguments being passed as positional arguments.
Update:
I'm using https://github.com/ethereum/web3.py/blob/a7ed9070e37c34f0e411a7441d4b79d8e5932a36/web3/eth.py to find all methods that are now `Method` instances. For some reason, not all of these changes were caught in tests. The list of changed methods:
* `getBlock()`
* `sendRawTransaction()`
* `getTransactionReceipt()`
* `getTransaction()`
* `sendTransaction()`
* `signTransaction()`
I think I got them all now.
> Since web3=5.12.2 its methods need positional arguments

- .github/workflows/pr_release_note_entry.yml
- newsfragments/2396.feature.rst
The check that this PR adds, is expected to fail for this PR hehehe 😅 .
Release note entry format readme can be viewed - https://github.com/derekpierre/nucypher/blob/release-notes-action/newsfragments/README.md.
> Simple GitHub action to ensure release note entry included in PRs into main.

- newsfragments/2390.bugfix.rst
- newsfragments/2395.bugfix.rst
- nucypher/blockchain/eth/signers/hardware.py
- nucypher/cli/commands/stake.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/literature.py
- nucypher/cli/painting/staking.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py
- Fixes broken references when using `nucypher stake set-min-rate` (Fixes #2390)
- Reduces even more the learning logging. It's very difficult to try to debug anything with all that learning chatter.
- Other minor fixes here and there for CLI output and exception messages
> Fix for nucypher stake set-min-rate

- newsfragments/2423.bugfix.rst
- nucypher/acumen/perception.py
- nucypher/characters/lawful.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- nucypher/utilities/prometheus/collector.py
- tests/acceptance/characters/test_decentralized_grant.py
- tests/acceptance/cli/ursula/test_stake_via_allocation_contract.py
- tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py
- tests/acceptance/learning/test_fault_tolerance.py
- tests/acceptance/network/test_network_actors.py
- tests/integration/config/test_character_configuration.py
- tests/integration/config/test_configuration_persistence.py
- tests/integration/learning/test_domains.py
- tests/integration/learning/test_firstula_circumstances.py
- tests/integration/learning/test_learning_upgrade.py
- tests/integration/learning/test_learning_versions.py
- tests/integration/network/test_treasure_map_integration.py
- tests/mock/performance_mocks.py
- tests/unit/test_work_tracker_error_handling.py
Domain "leakage", or nodes saving metadata about nodes from other domains (but never being able to verify them) was still possible because domain-checking only occurred in the high-level APIs (and not, for example, when checking metadata POSTed to the node_metadata_exchange endpoint).  This fixes that (fixes #2417).
**As such, the mechanism by which ibex nodes are leaking into some mainnet fleet states is now disabled.**
Additionally, domains are no longer separated into "serving" or "learning".  Each Learner instance now has exactly one domain, and it is called domain.  Fixes #2356.
*Note: the behavior of `handpicked ursulas` is unchanged.  In other words, it is still possible to explicitly specify an off-domain Ursula during an action that takes `handpicked_ursulas` and use it despite …
> Moving domain check into FleetSensor.

- newsfragments/2412.bugfix.rst
- nucypher/acumen/perception.py
- nucypher/network/nodes.py
- nucypher/utilities/logging.py
- tests/unit/test_logging.py
* Remove leftover imports of Twisted Logger, using instead our shim. Closes #2404 
* Change NuCypher Logger behavior to always escape curly braces. The rationale is that it's unclear how to justify the previous behavior with some edge cases like ``{{}``, which was processed to ``{}``.
> Use NuCypher Logger instead of Twisted Logger. Closes #2404

- newsfragments/2406.bugfix.rst
- newsfragments/2421.bugfix.rst
- newsfragments/2425.feature.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/token.py
- nucypher/cli/commands/stake.py
- nucypher/cli/options.py
- nucypher/cli/types.py
- nucypher/utilities/gas_strategies.py
- tests/acceptance/cli/ursula/test_local_keystore_integration.py
- tests/integration/cli/test_stake_cli_functionality.py
- tests/integration/conftest.py
- tests/mock/agents.py
- tests/unit/test_gas_strategies.py
- tests/utils/ursula.py
- In the Worker's commitment tracker, the logic to check for what's the current period should happen before the logic to track pending transactions. Otherwise, it's possible to try to fire a replacement transaction in the context of a different period. Closes #2406
- Now ``BlockchainInterface.gas_strategy`` always has a value; previously it was possible to pass ``None`` via the constructor (e.g. if the config file had an explicit ``"null"`` value). Closes #2421 
- Added support for a user-provided gas price to the ``nucypher stake`` command, using ``--gas-price GWEI``.
> More work tracker improvements. Adds --gas-price option to nucypher stake

- docs/source/release_notes/releases.rst
I tried to add entries for prior PRs/issues - so that we don't have "No significant changes" 😅 . The releases only go as far back as v4.0.0 (Mainnet Launch version).
For the respective assignees associated with those PRs/Issues feel free to make suggestions to update corresponding entries, or to create PRs into this PR for more significant updates to the `releases.rst` file. For each section (`Features`, `Bugfixes` etc.) the pr/issue number is supposed to be sorted.
Seems reasonable to eventually merge without a newsfragment for this PR (i.e. failed GH action check)...but if desired I can add one.
> Retro-actively update release notes for prior nucypher versions - starting with mainnet launch

- newsfragments/2346.doc.rst
Just realized that #2346 was from some time ago and wasn't rebased before getting merged. Therefore, it didn't include a newsfragment for the release notes.
> Add newsfragment for PR #2346.

- newsfragments/2451.misc.rst
- nucypher/blockchain/eth/signers/base.py
- nucypher/blockchain/eth/signers/software.py
- tests/integration/blockchain/test_keystore_signer_filesystem_integration.py
Gives CLI users an `AccessDenied` exception instead of `MACMismatch` on incorrect password
> Improve handling of incorrect password via software signer

- deploy/ansible/worker/backup_remote_workers.yml
- deploy/ansible/worker/include/backup_ursula_data.yml
- deploy/ansible/worker/include/check_running_ursula.yml
- deploy/ansible/worker/include/print_ursula_log.yml
- deploy/ansible/worker/include/run_ursula.yml
- deploy/ansible/worker/include/stop_containers.yml
- deploy/ansible/worker/restore_ursula_from_backup.yml
- deploy/ansible/worker/setup_remote_workers.yml
- deploy/ansible/worker/update_remote_workers.yml
- docs/source/guides/network_node/nucypher_host_management_cli.rst
- newsfragments/2365.feature.rst
- nucypher/cli/commands/cloudworkers.py
- nucypher/utilities/clouddeploy.py
- nucypher/utilities/templates/cloud_deploy_ansible_inventory.mako
* up | Creates and deploys hosts for all active local stakers
* create | Creates and deploys the given number of hosts independent of stakes
* add | Add an existing host to be managed by cloudworkers CLI tools
* add_for_stake | Add an existing host to be managed for a specified local staker address
* deploy | Install and run Ursula on existing managed hosts.
* update | Update or manage existing installed Ursula.
* destroy | Shut down and cleanup resources deployed on AWS or Digital Ocean
* status | Prints a formatted status of selected managed hosts.
* logs | Download and display the accumulated stdout logs of selected hosts
* backup | Download local copies of critical data from selected installed Ursulas
* restore | Reconstitute and deploy an operating Ursula from backed up data
* …
> We don't need no stinking stakers

- newsfragments/2416.bugfix.rst
- nucypher/policy/policies.py
* in `FederatedPolicy.sample_essential()`, check that handpicked Ursulas are known too before returning
* in `BlockchainPolicy.sample_essential()`, don't block for the whole timeout waiting for the first batch of nodes to be discovered; wait a little and draw more from the reservoir instead. Probably fixes #2201.
To solve:
* What's the best default `drawing_step`? Currently it's just 5 (for no reason whatsoever). Since we can only check `drawing_step * timeout / learner_timeout` nodes in total, perhaps it should depend on `self.n` instead.
> Less stubborn sampling

- .github/PULL_REQUEST_TEMPLATE.md
- newsfragments/2476.misc.rst
This PR introduces a simple GH template for pull requests, with the goal that all PRs from now on have some common information. 
None
We need a way to harmonize the description of the PRs, especially, to facilitate the reviewers' work, and hopefully, improve efficiency of the review process.
**Does this PR address a `nucypher/productdev` issue?**  No
* The "Why it's needed" section is a way to link the PR description with high-level team-wide goals that can help justify why this PR (and reviewing this PR) is necessary.
* The "required reviews" part is just a personal idea. My thought here is that this is an aspect self-assessed by the PR author, as in practice …
> Pull Request template

- nucypher/characters/lawful.py
- nucypher/crypto/kits.py
- tests/integration/characters/test_bob_handles_frags.py
- tests/integration/network/test_treasure_map_integration.py
Since PR #2063 (parallel `retrieve()`) is currently blocked by LMDB issues, this PR is created to at least make some progress on the parts of #2063 that simplify the logic flow in `retrieve()` and prepare it to be split into independent worker processes.
> Simplify Bob.retrieve()

- .circleci/config.yml
- docs/source/conf.py
- newsfragments/2489.bugfix.rst
- scripts/solidity_doc/generate_doc.py
Nucypher package has no contracts and generate_doc script. RTD build uses not editable installation so imported constants point to empty dirs. Fix changes constants to relative paths. 
Fix docs build
> Fix rtd build

- .circleci/config.yml
- Pipfile
- Pipfile.lock
- deploy/docker/Dockerfile
- dev-requirements.txt
- dev/docker/Dockerfile
- newsfragments/2440.misc.rst
- requirements.txt
- scripts/installation/relock_dependencies.sh
* Relocks dependencies, using latest pipenv. Note how this time pipenv is much more opinionated in the version specifiers.
* In particular, cryptography >= 3.2 (due to security issues, see https://github.com/nucypher/nucypher/pull/2409) and web3py <= 5.12.3 (for some reason, 5.13 fails for us)
* Updates the relocking script to remove automatic headers to requirements files.
* Forces usage of pip==20.2.4 in CI to avoid problem with pip resolver (https://github.com/pypa/pip/issues/9180). Waiting for pip 20.3.4 (see #2493)
* Changes Python version of docker images to 3.8
> Relock dependencies

- Pipfile
- Pipfile.lock
- deploy/docker/Dockerfile
- dev-requirements.txt
- dev/docker/Dockerfile
- requirements.txt
Removes upper limit for `lmdb` version and updates it to the current 1.0.0
Fixes #2324
> Remove lmdb<=0.99 requirement and relock

- docs-requirements.txt
- newsfragments/2496.misc.rst
Fixes the failing readthedocs build. As part of the relock of dependencies, the docs-requirements.txt dependencies need to be update as well. Long term we need to make this process better - the docs-requirements.txt should be updated as part of the relock dependencies script.
> - Fixes #...
Related to #2440, #2498
Follow-up issue filed https://github.com/nucypher/nucypher/issues/2495.
Failing RTD build - …
> Update requirements for documentation build to fix failing RTD build

- newsfragments/2507.removal.rst
- nucypher/cli/commands/ursula.py
- nucypher/cli/processes.py
- tests/acceptance/cli/ursula/test_ursula_command.py
Deprecates CLI commands for manually committing to next period.
Configurable maximum gas price for workers provides a mitigation that supersedes the ability to manually commit.  While it has served it's purpose, Exposing `commit_to_next_period` as a CLI command is a proverbial "foot gun" that allows users to damage the health of the network. It's removal is part of guiding the codebase and node operators to use other tactics to manage gas costs while still providing a high level of grant availability.
Tangentially related to project https://github.com/nucypher/nucypher/projects/13
> Deprecates manual worker commitment via CLI

- Makefile
- Pipfile.lock
- dev-requirements.txt
- docs-requirements.txt
- newsfragments/2510.misc.rst
- requirements.txt
- scripts/dependencies/docs/Pipfile
- scripts/dependencies/relock_dependencies.sh
Relock `doc-requirements.txt` as part of the `relock_dependencies.sh` script
> - Fixes #...
Fixes #2495 
Prevent RTD build failures (eg. https://readthedocs.org/projects/nucypher/builds/12688734/) due to mismatched dependency versions in docs-requirements.txt, when `requirements.txt` and `dev-requirements.txt` dependencies are updated.
> Is there a …
> Include relock of docs-requirements.txt in the relock_dependencies script

- .gitignore
- nucypher/blockchain/eth/actors.py
- nucypher/cli/commands/deploy.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/literature.py
- nucypher/cli/painting/deployment.py
- tests/acceptance/blockchain/actors/test_deployer.py
- tests/acceptance/cli/deploy/test_deploy_cli.py
- tests/acceptance/cli/deploy/test_deploy_cli_commands.py
- tests/acceptance/cli/test_cli_config.py
- tests/acceptance/cli/test_contacts.py
- tests/conftest.py
- tests/metrics/estimate_gas.py
- tests/utils/blockchain.py
Required reviews: 1
Extricated from #2348 
**What this does**
Removes the CLI command to deploy all of the nucypher contracts at once in a single command, while preserving the deployment staging UX.
> Deprecation: Automated deployment series by ContractAdministrator

- MANIFEST.in
- deploy/ansible/worker/include/run_ursula.yml
- docs/source/guides/network_node/nucypher_host_management_cli.rst
- newsfragments/2494.bugfix.rst
- nucypher/cli/commands/cloudworkers.py
- nucypher/utilities/clouddeploy.py
- nucypher/utilities/templates/cloud_deploy_ansible_inventory.mako
* Fixes a couple of bugs discovered by @arjunhassard 
* adds `nucypher cloudworkers stop` feature
* handle change from envvar to cli args for --max-gas-price and generally make cli arg handling more flexible
* improve performance when no seed node present in node inventory
* small UX improvements
* Some basic functionality (ability to set gas price and update nodes in certain contexts) is currently broken... this fixes it.
> Some Updates to worker management 

- newsfragments/2486.bugfix.rst
- nucypher/blockchain/eth/interfaces.py
Running `nucypher worklock refund` fails with "no refund availble" if a pending refund transaction is present in the mempool.
During gas estimation, the pending refund transaction is effectively assumed to have already completed thus causing the attempted refund transaction to fail when estimating gas.
This PR explicitly estimates gas with block identifier set to "latest" which ignores the pending transactions for purposes of gas estimation.
The PR also fixes failed transaction exception handling, where the resulting ValueError had a third unexpected "data" member causing the unpack and assign to two variables statement to fail and throw.
This PR is a bug fix and fairly small in scope - review should hopefully be easy and straightforward.
> Estimate gas with block identifier 'latest'

- newsfragments/2515.bugfix.rst
- nucypher/network/nodes.py
- nucypher/network/server.py
Allows for a gentler handling of UnsignedStamps only when in the context of reading known nodes while rendering ursula's /status endpoint
Resolves https://sentry.io/organizations/nucypher/issues/2134995939/?project=1480080&query=is%3Aunresolved
Fixes the /status?json=1 which is currently broken network wide.
This will not affect https://github.com/nucypher/nucypher/issues/1698 or any of the related issues as it only will change anything when called from /status
I have already tested this on several NuCo nodes over the period of 2021-01-01 to 2021-01-10 or so
> When rendering /status, don't fail, but log on StampNotSigned

- newsfragments/2521.bugfix.rst
- nucypher/blockchain/eth/interfaces.py
Bugfix
1
Fix a bug introduced in #2486. [Example of a failed CI](https://app.circleci.com/pipelines/github/nucypher/nucypher/6922/workflows/86ddb3fc-8793-4899-89e2-7890ee71708c/jobs/118136)
Basically, the code in `_handle_failed_transaction()`
```
try:
code = int(response['code'])
message = response['message']
except (KeyError, ValueError):
```
May result in a `TypeError` if `response` is not subscriptable. As a result, `TypeError` is raised instead of `exception`, which results in multiple tests failing. 
The PR introduces two changes: 
- Let `response = exception.args[0]` fail naturally. If we're replacing the exception, we may as well know what exactly failed there.
- Catch all `Exception`s in the block above instead of …
> Fix CI build

- .circleci/config.yml
I think the problem is that last time we saved the result of the `build_docker` job to cache, we were using the previous CI docker images, which changed in this commit https://github.com/nucypher/nucypher/commit/9d95ce81fe54c2abf5cf7724f753dc7d3447cce1
The problem is that we didn't changed the cache key, and probably the images have changed internally. I verified that simply bumping the cache key works, both for saving and restoring the cache. 
Also added the architecture ID to the cache key, as suggested in https://support.circleci.com/hc/en-us/articles/360004250693-Restoring-cache-fails-with-Permission-Denied-
> Fix failing build_docker job

- .circleci/config.yml
- setup.py
Removes the docs pip extra to allow prevent distributing `jsonschema2rst`
Closes #2524
> Remove docs pip extra from setup.py

- docs/source/guides/contribution_guide.rst
- docs/source/guides/ethereum_node.rst
- newsfragments/2484.bugfix.rst
- newsfragments/2533.bugfix.rst
- nucypher/blockchain/eth/clients.py
- tests/mock/interfaces.py
- tests/unit/test_card.py
- tests/unit/test_web3_clients.py
- tests/utils/blockchain.py
A small PR with some assorted bugfixes and changes.
- Fixes #2484: We were incorrectly using `net_version` to identify the Ethereum chain in some places. This was found in the short period where geth deprecated said endpoint. In any case, we now use `eth_chainId`.
- Fixes #2531: The MockBlockchain was compiling solidity sources, which is not correct and was making unit tests very slow.
- Unskips card tests
- Adds some minor clarifications to the docs.
Maintenance.
Nothing.
> Fixes to unit tests. Fix for #2484

- newsfragments/2534.bugfix.rst
- nucypher/network/nodes.py
- tests/metrics/grant_availability.py
Exit while loop when blocking until number nodes exceeds requirement. This caused an infinite loop while timing out when learning - exhibited for Alice.
Side fix for invalid import in grant_availability script which was used for testing when bug was discovered.
> - Fixes #...
Closes #2487 
> Is there a particular commit/function/section of your PR …
> Fixed blocking call waiting for number of known nodes which could infinite loop

- newsfragments/2543.bugfix.rst
- nucypher/blockchain/eth/interfaces.py
This is in the same line as #2366 - probably introduced by someone using an old `web3` version.
Reported on Discord; traceback:
```
Unhandled error during work tracking (#2): 'Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
self.mainLoop()
File "/usr/local/lib/python3.8/site-packages/twisted/internet/base.py", line 1292, in mainLoop
self.runUntilCurrent()
File "/usr/local/lib/python3.8/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
call.func(*call.args, **call.kw)
File "/usr/local/lib/python3.8/site-packages/twisted/internet/task.py", line 239, in __call__
d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
File …
```
> Use an explicit keyword argument in estimateGas

- newsfragments/2546.misc.rst
- nucypher/utilities/prometheus/metrics.py
> - Fixes #...
Fixes #2545 - change applied for all testnets, not just Lynx.
WorkLock prometheus metrics are only meaningful on mainnet.
WorkLock metrics are only collected on mainnet. Is there any reason to collect them on testnet i.e. Ibex?
> Don't collect prometheus WorkLock metrics when on testnet

- newsfragments/2544.feature.rst
- nucypher/blockchain/eth/sol/source/contracts/staking_contracts/PoolingStakingContractV2.sol
- tests/contracts/main/staking_contracts/test_pooling_contract_v2.py
New preferable base pooling contract
`WorkLockPoolingContract` is good candidate but `WorkLock` part is not needed for new pools
No new lines in copy of `WorkLockPoolingContract`, only deleted
> Modification of WorkLockPoolingContract (without worklock part)

- newsfragments/2550.bugfix.rst
- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/config/keyring.py
- tests/conftest.py
- tests/integration/learning/test_discovery_phases.py
**What this does**
- Support lazy remote web3 provider connection, inside `Chatacter.__init__`.
- Use the default keyring root for `NucypherKeyring` generation.
- Skip/Workaround for failing test on CI #2552 
Follow up for #2463 - Only one reviewer required for this one.
> Bugfixes: Lazy provider connection and Default keyring root

- docs/source/application_development/getting_started.rst
- docs/source/staking/best_practices.rst
- newsfragments/2554.doc.rst
- Includes missing `rate` parameter from `Alice.grant` in docs.
- Expands example granting script for Alice using the python API.
- Consistently use a single ethereum address in documentation code samples.
Help application developers get on-board and integrate more easily.
> Example granting script for python API docs

- newsfragments/2555.bugfix.rst
- nucypher/characters/lawful.py
Bugfix
1
Provides a handle for `Alice` signers to be used while sharing a blockchain connection with other character in-scope.
> Cache Alice's transacting power for later activation

- newsfragments/2562.feature.rst
- nucypher/network/server.py
500s will not be raised in response to HTTP requests.
Also, 400s all have sensible messages.
Better http behavior.
> raise 403 instead of 500 on invalid Alice Signature on kfrag

- newsfragments/2557.bugfix.rst
- nucypher/policy/policies.py
- nucypher/utilities/concurrency.py
- tests/acceptance/utilities/test_concurrency.py
- Bugfix
- 2
Currently if the main thread stops before `TreasureMapPublisher` finishes distributing treasure maps (e.g. in a CLI granting situation), the process hangs indefinitely. It happens because if `WorkerPool.join()` is never called, the thread pool is still active and waiting for workers to be enqueued. 
In this PR, we stop the thread pool explicitly when all the worker results are processed, so it is guaranteed to be empty and to not receive any more `callInThread()` calls. 
It also makes the logic more strict:
- disallows races in `_threadpool.stop()`
- makes sure `join()` waits for all threads to finish for all callers, not just for the first one
- in case of an unexpected error in the producer thread, raises the error …
> Stop the threadpool when all the worker results are processed

- CONTRIBUTING.rst
- README.md
This commit fixes the symlink to the Contributing file. It also
fixes the broken/stale link to the contributing docs on the
README.
This commit fixes the symlink to the Contributing file. It also
fixes the broken/stale link to the contributing docs on the
README.
> fix: broken link to contributing docs

- deploy/ansible/worker/include/check_running_ursula.yml
- newsfragments/2352.misc.rst
- nucypher/acumen/nicknames.py
- nucypher/acumen/perception.py
- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/cli/painting/nodes.py
- nucypher/cli/processes.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- nucypher/network/templates/basic_status.mako
- nucypher/network/trackers.py
- nucypher/utilities/prometheus/collector.py
- tests/acceptance/characters/test_ursula_web_status.py
- tests/acceptance/network/test_network_actors.py
- tests/fixtures.py
- tests/integration/characters/test_ursula_startup.py
- tests/integration/learning/test_domains.py
- tests/integration/learning/test_firstula_circumstances.py
- tests/integration/learning/test_fleet_state.py
- tests/integration/network/test_failure_modes.py
- tests/mock/performance_mocks.py
- tests/unit/test_external_ip_utilities.py
The goal of this PR is to make interactions with `FleetSensor` consistent and avoid exposing implementation details, or carrying around ad-hoc states (`fleet_state_*` attributes). More specifically:
* `FleetState` is made into a real class. It encapsulates incremental updates and collection-like interface to iterate over the state's nodes. It is exposed from `FleetSensor` as `current_state`. 
* `FleetSensor` itself manages the buffers with new/deleted nodes and a list of previous states.
* Previous states are kept as simple `ArchivedFleetState` instances that do not retain references to actual nodes (since we don't use them anyway), only checksum/nickname/population. 
* The user (meaning the higher levels of the codebase) must call `record_fleet_state()` in order for the state to get …
> Fleet sensor refactor

- docs/source/index.rst
- docs/source/references/cli_reference.rst
- docs/source/references/network_events.rst
- docs/source/staking/stake_management.rst
- newsfragments/2573.feature.rst
- nucypher/cli/commands/stake.py
- nucypher/cli/commands/status.py
- nucypher/cli/literature.py
- nucypher/cli/utils.py
- nucypher/utilities/events.py
- tests/acceptance/cli/test_status.py
`nucypher status events` command can now:
* output to csv file using `--csv` or `--csv-file`
* accept 1 or more event filters in the form `--event-filter name=value`, for example you can filter by staker address.
> - Fixes #...
Related to #2548 , #2561 .
This allows for ease of accounting based on events emitted by smart contracts.
For example
```
$ nucypher status events --contract-name StakingEscrow …
```
> Improve 'nucypher status events' to allow event filtering

- newsfragments/2589.bugfix.rst
- nucypher/utilities/prometheus/collector.py
- nucypher/utilities/prometheus/metrics.py
Issue observed in v4.7.0.
```
Mar  2 22:24:12 m2-nucypher01 nucypher[31355]: Working ~ Keep Ursula Online!
Mar  2 22:25:42 m2-nucypher01 nucypher[31355]: Unhandled error in Deferred:
Mar  2 22:25:42 m2-nucypher01 nucypher[31355]: Traceback (most recent call last):
Mar  2 22:25:42 m2-nucypher01 nucypher[31355]:   File "/home/nucypher/.local/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
Mar  2 22:25:42 m2-nucypher01 nucypher[31355]:     self.mainLoop()
Mar  2 22:25:42 m2-nucypher01 nucypher[31355]:   File "/home/nucypher/.local/lib/python3.7/site-packages/twisted/internet/base.py …
```
> [Hotfix] Fix Ursulas not starting up when prometheus is enabled

- newsfragments/2574.misc.rst
- nucypher/acumen/nicknames.py
- nucypher/acumen/perception.py
- nucypher/characters/lawful.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- nucypher/network/templates/basic_status.mako
- tests/acceptance/characters/test_ursula_web_status.py
- tests/fixtures.py
- Other
- 2
Some adjustments and bugfixes for node and fleet state metadata to help `nucypher-monitor`:
- `FleetSensor.record_fleet_state()` now returns `None` if the fleet state was not updated and the new `ArchivedFleetState` otherwise.
- `Nickname.to_json()` now has an `icon` field (a little redundant, but it is needed often).
- `status_info()` is now a method of `Ursula` instead of `Teacher`. It is used to get the status of the local node. It returns a `LocalUrsulaStatus` object (a namedtuple with a `to_json()` method).
- `FleetSensor.status_info(checksum_or_node)` is used for remote nodes (those from `FleetSensor` itself) and returns a `RemoteUrsulaStatus` object.
- Removed `Learner.last_seen` and keeping track of it in …
> Help nucypher-monitor get the info it needs

- nucypher/characters/lawful.py
Reconfiguration
3
Worker nodes perform a worker commitment in the middle of service startup.
Improves UX when restarting a node with a pending commitment close to period advancement.
A disadvantage here is that the nodes services have not fully started, and the transaction is extremely eager.  This may encourage bad behaviors by essentially introducing a CLI command for "manual commitments".
> Enable eager worker commitment during startup

- newsfragments/2607.feature.rst
- nucypher/blockchain/eth/token.py
Feature
1
Handles an edge case in `WorkTracker` during period extension migration.
Prepares nodes for graceful transition to an extended period duration.
**Notes for reviewers**
This PR is a cherry-pick from #2594
> Handle period migration in work tracker.

- newsfragments/2611.bugfix.rst
- nucypher/characters/lawful.py
- Bugfix
- 1
Returns back some local Ursula status info that was accidentally removed in #2352. Sorry @vepkenez !
> Bring back a few bits of blockchain node status that were accidentally removed

- newsfragments/2615.bugfix.rst
- nucypher/cli/actions/select.py
Bugfix
1
> Fixes `Not ETH accounts found` when using `--signer` and `--provider` flags together.
> [Hotfix] Fixes account selection with ambiguous source.

- .dockerignore
- deploy/ansible/worker/include/update_existing_ursula.yml
- deploy/ansible/worker/update_remote_workers.yml
- newsfragments/2618.bugfix.rst
Cloudworker configured nodes were still having their disks filled up by logs and old docker images. This PR more forcefully cleans up old junk with no side effects.
> cloudworkers: clean disk space more thoroughly, stop containers first

- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- tests/contracts/migration/test_staking_escrow.py
Fix small bug when inactive sub-stake become active for current period only after migration. It leads to lock tokens (without reward) when it should not
> Fix bug with merged sub-stake and migration (when last period is 1)

- examples/run_demo_ursula_fleet.py
- newsfragments/2538.misc.rst
- newsfragments/2629.misc.rst
- nucypher/cli/commands/felix.py
- nucypher/config/characters.py
- nucypher/network/protocols.py
- nucypher/utilities/networking.py
- scripts/local_fleet/run_single_ursula.py
- tests/acceptance/cli/ursula/test_run_ursula.py
- tests/acceptance/cli/ursula/test_stakeholder_and_ursula.py
- tests/unit/test_web3_clients.py
- Replaces occurrences of `127.0.0.1` with a `LOOPBACK_ADDRESS` constant.
- Fixes #2538 
- [One occurrence](https://github.com/nucypher/nucypher/blob/main/scripts/local_fleet/run_local_ursula_fleet.py#L33) of `127.0.0.1` was ignored because it's a script without dependency on the codebase.
> Use constant for loopback address

- newsfragments/2628.misc.rst
- nucypher/policy/identity.py
- tests/unit/test_card.py
Other
1
- Changes nickname delimiter in card filename from colon `:` to dot `.`.
- Adds a test for a QR code output.
- Fixes #2471 
- It could break compatibility for existing card files.
> Change nickname delimiter in card filename

- deploy/ansible/worker/geth_inventory.yml
- deploy/ansible/worker/include/init_worker.yml
- deploy/ansible/worker/include/install_geth.yml
- deploy/ansible/worker/include/run_external_geth.yml
- deploy/ansible/worker/setup_remote_workers.yml
- deploy/ansible/worker/setup_standalone_geth_node.yml
- newsfragments/2624.feature.rst
- nucypher/acumen/perception.py
* Tweaks some existing ansible playbooks for re-usability.
* Creates setup_standalone_geth_node.yml for one line deployment of latest geth on existing VPS.
* fixes https://sentry.io/organizations/nucypher/issues/2269874410
* Our current Ethereum infrastructure relies on copying and pasting from history of existing node. This formally declares our spec and makes for a simple and reliable way to create new Ethereum nodes.
> acumen bug fix, ansible geth node playbook

- nucypher/policy/identity.py
- Previously, when restoring cards we would pick the first matching filename
- Now, we throw an error if the given nickname was ambiguous
Example:
```bash
$ ls ~/.local/share/nucypher/cards 
test-nickname.0x8fe7f7811e.card
test-nickname.0xb9d0b18089.card
$ nucypher alice grant --bob test-nickname
$ nucypher alice grant --bob test-nickname
ValueError: Ambiguous card nickname: test-nickname. Try using ID instead.
$ nucypher alice grant --bob 0xb9d0b18089
```
- Fixes: #2464
> Is …
> Handle ambiguous card nickname in lookup

- docs/source/architecture/staking_contracts.rst
- docs/source/architecture/upgradeable_proxy_contracts.rst
- docs/source/index.rst
- newsfragments/2597.doc.rst
- scripts/solidity_doc/generate_doc.py
Based over #2596. Document base Staking contract and `PoolingStakingContractV2`.
> - Fixes #...
Related to #2596 .
Closes #2202
> Staking Pool Docs

- .github/workflows/pr_release_note_entry.yml
- [] 3
Our existing github action doesn't handle multiple PR newsfragments for the same PR (eg. feature, and bugfix). This is seen in #2617 .
Since the github action is mostly internal, I won't add a newsfragment for this PR i.e. the action will fail for this PR (oh the irony!)
Sometimes a PR solves multiple types of issues and necessitates multiple newsfragments of different types.
--
Adding here for posterity. When testing GitHub Actions, use the `act` command from  'act' command by installing https://github.com/nektos/act.
For PR testing use the following steps:
1. Run Docker Desktop
2. Get any previous PR data - `curl -X GET https://api.github.com/repos/nucypher/nucypher/pulls/PR_NUMBER > OUTPUT_FILE`
3. …
> Release note github action should handle multiple newsfragment files.

- examples/finnegans_wake_demo/finnegans-wake-demo-testnet.py
- newsfragments/2626.bugfix.rst
- nucypher/characters/base.py
- nucypher/characters/lawful.py
Bugfix
1
Fixes `ValueError: Provider URI is required to init a decentralized character.` thrown on `Bob()` and `Alice()` constructors.
> Fix missing provider_uri

- newsfragments/2637.bugfix.rst
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/interfaces.py
Feature
1
Use a 25% gas estimation multiplier for mint.
Related to #2337
Avoids intermittent insufficient gas estimation for mint transactions.
> Use an estimation multiplier for mint.

- newsfragments/2646.bugfix.rst
- nucypher/cli/commands/status.py
- nucypher/utilities/prometheus/collector.py
Bugfix
1
The value at index 0 within staking parameters is the `genesis_seconds_per_period` (60 * 60 * 24). This caused the estimation of block number of a period to be incorrect causing weird behaviour for both `nucypher status events`, and prometheus metrics collection (`CommitmentMade` event).
Fixes #2641 
Also encountered similar error as #2641 when running `nucypher status events`:
```bash
$ nucypher status events --contract-name StakingEscrow --event-name CommitmentMade --event-filter staker=<staker_address> --provider <provider> --network mainnet
...
File "/Users/derek/.local/share/virtualenvs/nucypher-z-zdnWw9/lib/python3.7/site-packages/web3/manager.py", line 158, in request_blocking
raise …
```
> Fix incorrect use of `genesis_seconds_per_period` instead of `seconds_per_period`

- nucypher/characters/lawful.py
- nucypher/cli/painting/nodes.py
- nucypher/datastore/datastore.py
- nucypher/datastore/queries.py
- nucypher/utilities/prometheus/collector.py
- tests/acceptance/characters/test_freerider_attacks.py
Refactors queries previously expressed as `Datastore.query_by` into a separate file
- Fixes: #2153
Some `Datastore.query_by` queries were left without change - I felt they were better expressed in their original form, being used in `test_*.py` files
> Refactor queries into a separate file

- newsfragments/2660.bugfix.rst
- nucypher/config/base.py
No need to use modifiers when updating since the configuration file already exists, and it will be overwritten.
No reason to care about modifiers when updating a configuration file.
Fixes #2659
> Improve logic for updating configuration file

- newsfragments/2672.feature.rst
- nucypher/policy/identity.py
- tests/unit/test_card.py
- When saving a character card, `--nickname My Nickname` will result in `My_Nickname` character nickname.
- Fixes #2465
- It's a missing piece of nickname validation.
- May break existing character cards of relationship between nickname and card filenames.
> Implicitly remove whitespaces from character nicknames

- newsfragments/2657.feature.rst
- nucypher/characters/lawful.py
- nucypher/network/middleware.py
- nucypher/network/nodes.py
- nucypher/utilities/networking.py
- tests/fixtures.py
- tests/integration/learning/test_domains.py
- tests/metrics/grant_availability.py
- tests/unit/test_external_ip_utilities.py
- tests/utils/middleware.py
- Adds `https://closest-seed.nucypher.network` and `https://mainnet.nucypher.network:9151` nodes to `TEACHER_NODES`
- Moves `TEACHER_NODES` from `RestMiddleware` to `nodes.py`
- Adds some tests to confirm the correctness of using `TEACHER_NODES` as a fallback when local node storage is empty. 
- Fixes #2481 
> Fallback chain of teacher nodes

- newsfragments/2680.feature.rst
- nucypher/blockchain/eth/events.py
- nucypher/utilities/events.py
- tests/acceptance/cli/test_status.py
- Adds  timestamp and date columns to csv output of "nucypher status events" command
- Fixes #2652
- Originally marked as a bug, but IMHO it's an addition to an existing feature.
- Example output:
```
event_name,block_number,unix_timestamp,date,staker,period,value
Minted,8494719,1619655297,2021-04-29T00:14:57Z,0xf2C45287139C6839215F0FfC0759777FFE734fAa,9372,593704596220612940690
```
> Add timestamp column to csv output

- nucypher/characters/lawful.py
- Fixes second exception thrown when killing the node with CTRL+C
- Refers #2608
- It only partly fixes #2608, but it's something
- IMHO not worthy of newsfragment
> Fix ReactorNotRestartable exception after receiving SIGINT

- newsfragments/2662.misc.rst
- nucypher/cli/actions/auth.py
- nucypher/cli/commands/alice.py
- nucypher/cli/commands/bob.py
- nucypher/cli/commands/felix.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/literature.py
- nucypher/cli/painting/help.py
- nucypher/cli/utils.py
- tests/integration/cli/actions/test_auth_actions.py
Feature
2
Prompts the user with some additional info an detailed suggestions during password collection.
Helps to install an accurate sense of keystore diligence in anticipation of keyring portability.
> Improve keyring creation prompts and warnings

- newsfragments/2673.bugfix.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- tests/acceptance/blockchain/actors/test_staker.py
- tests/integration/cli/test_stake_cli_functionality.py
- Updates token allowance when needed for `depositAndIncrease()` transaction
- Raises error if token allowance is not 0 prior to `approve()` and `approveAndCall()` tranasctions
- Fixes #2636 
> Check allowance value before transactions

- examples/run_demo_ursula_fleet.py
- newsfragments/2681.bugfix.rst
- Removed reactor.run in the demo fleet script because it was stealing console input from the user
- cleaned up the temp db files
- Fixes #2232
This is just a simple db clean up for the fleet demo in the example scripts
Removed `reactor.run` because it steals console input from the user
> Cleaned up each DB on shutdown, and removed reactor.run to give user console control

- nucypher/cli/painting/help.py
- Fixes a failing test, introduced by [this change](https://github.com/nucypher/nucypher/commit/5575c2c1358ffce4cba9bf4a3a41b2dbf68924ca#diff-fcfc8064edaf99ec15716f2b8442c9fb87175511312cffd8bed5aa5752f1684dR61-R63)
- Is it ok for the keyring to **not** be attached at this point? This is underlying cause of the error
> Fix failing CI test

- nucypher/utilities/prometheus/collector.py
- tests/acceptance/utilities/test_prometheus_collectors.py
- tests/unit/test_prometheus.py
Prometheus unit and acceptance tests are only run when prometheus is installed.
Unit test / acceptance test suite fails if `prometheus_client` dependency is not installed. Seems like tests are run on circle ci.
Is this the best strategy?
> Fix prometheus tests that should not be run unless prometheus is installed - it is an optional dependency

- newsfragments/2709.bugfix.rst
- nucypher/acumen/perception.py
- nucypher/network/nodes.py
- Bugfix
- 1
Removes a `mature()` call that was introduced in https://github.com/nucypher/nucypher/pull/2574/commits/50da675692fba33ab76ece5c4a5da86fd7549ce6 for the purposes of `nucypher-monitor`. The only thing it needs that a sprout doesn't have is `rest_url`, and we can provide that.
Additional changes were necessary to allow some tests to pass, since they now got a mix of `Ursula` and `NodeSprout` objects:
- `NodeSprout.__eq__` added (identical to `Character.__eq__`, comparing stamps)
- `NodeSprout.__hash__` was changed to conform to `__eq__` (and to `Character.__hash__`), that is taking the hash of a stamp.
> Provide required info for nucypher-monitor without unnecessarily maturing sprouts

- nucypher/cli/commands/alice.py
- nucypher/cli/commands/bob.py
- nucypher/cli/commands/enrico.py
- nucypher/cli/commands/porter.py
- nucypher/cli/literature.py
- nucypher/cli/options.py
- nucypher/control/controllers.py
- nucypher/utilities/porter/porter.py
- tests/acceptance/cli/test_porter.py
Based over #2717 (which should be reviewed first).
`--tls-key-filepath` and `--certificate-filepath` options can now be provided to `nucypher porter run ... ` for Porter to be launched with TLS i.e. https.
For testing you can create a tls key and certificate for the localhost using the openssl command:
```bash
openssl req -x509 -out fullchain.pem -keyout key.pem \
-newkey rsa:2048 -nodes -sha256 \
-subj '/CN=localhost' -extensions EXT -config <( \
printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```
> Allow Porter to launch with TLS

- .circleci/config.yml
- deploy/docker/porter/Dockerfile
- deploy/docker/porter/docker-compose.yml
- nucypher/cli/commands/porter.py
- nucypher/cli/literature.py
- nucypher/utilities/porter/porter.py
- setup.py
- tests/acceptance/cli/test_porter.py
- tests/acceptance/porter/control/conftest.py
- tests/acceptance/porter/control/test_porter_web_control_blockchain.py
- tests/fixtures.py
- tests/integration/porter/control/conftest.py
- tests/integration/porter/control/test_porter_web_control_federated.py
Based over #2724 .
Allows Porter to facilitate Basic Authentication over HTTPS based on a provided `htpasswd` file via `--basic-auth-filepath`. Updated Docker/docker-compose files accordingly.
Fixes #2706  - does it fully "fix" it? perhaps for now unless users decide they want something more robust. However, this is a good starting point.
User authentication in some form will be needed if Porter is to be used as a public service.
> Basic Authentication for Porter

- deploy/ansible/worker/include/init_ursula.yml
- deploy/ansible/worker/include/stop_containers.yml
- newsfragments/2728.bugfix.rst
When running various Ansible flows that involved stopping Ursulas, errors encountered during the stop command would cause full failure for that node even if there was no Ursula running.  It should just keep going.
> Cloudworkers: ignore errors on stopping of ursula containers

- newsfragments/2744.misc.rst
- nucypher/utilities/concurrency.py
- tests/acceptance/utilities/test_concurrency.py
- Other
- 1
Before if there were some worker errors, and the required number of successes was not reached, the resulting `WorkerPool` error didn't give any context:
```
...
elif result == PRODUCER_STOPPED:
>           raise self.OutOfValues()
E           nucypher.utilities.concurrency.WorkerPool.OutOfValues
```
With this PR it is more informative:
```
...
elif result == PRODUCER_STOPPED:
>           raise self.OutOfValues(format_failures(self.get_failures()))
E           nucypher.utilities.concurrency.WorkerPool.OutOfValues: 7 total failures recorded;
E           for example, for the value (Ursula)⇀DarkMagenta Yankee DarkSeaGreen Mike↽ (0x5A83529ff76Ac5723A87008c4D9B436AD4CA7d28):
E             File …
```
> More informative `WorkerPool` errors

- newsfragments/2748.bugfix.rst
- nucypher/network/nodes.py
- Bugfix
- 2
Makes the `stamp` attribute of `NodeSprout` a typed `SignatureStamp` instead of plain bytes. This eliminates the bugs like https://app.circleci.com/pipelines/github/nucypher/nucypher/8166/workflows/09c311e0-3772-47e1-984e-25efdb1e1d52/jobs/138296 where node metadata is created with a repr-of-bytestring name, because `__generate_metadata_filepath()` wasn't applying `hex()` if it just got the stamp as bytes. 
We could just add a check in `__generate_metadata_filepath()` instead, but it is better to make that attribute typed to avoid future similar problems.
> Make `NodeSprout.stamp` be of type `SignatureStamp` and not `bytes`

- newsfragments/2753.bugfix.rst
- nucypher/utilities/gas_strategies.py
Problem observed where transactions are failing because of an invalid "gasPrice" field:
```
TypeError: Transaction had invalid fields: {'gasPrice': 19316500000.0}
```
The value provided was not an int hence the failure. By default, when determining the gas price, 3 different data feeds are used and the median value is used. The median value of 3 values is one of the values which is an int. However, if one of the feeds goes down (which occurred in this case), then two values remain and the median of 2 values is the average, and yields a non-integer value thereby causing the …
> Ensure that gas price used for transactions is an int

- newsfragments/2762.bugfix.rst
- nucypher/network/nodes.py
Attempting to write bytes to the log file causes exceptions to be thrown. The exceptions don't seem to affect operation, but are unsightly. Related to #2412 
This is observed in the status monitor.
```
crawler_1   | Traceback (most recent call last):
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/monitor/crawler.py", line 292, in learn_from_teacher_node
crawler_1   |     new_nodes = super().learn_from_teacher_node(*args, **kwargs)
crawler_1   |   File "/usr/local/lib/python3.7/site-packages/nucypher/network/nodes.py", line 797, in learn_from_teacher_node
crawler_1   |     self.log.warn(f"Teacher {str(current_teacher)} is invalid: {bytes(current_teacher)}:{e}.")
crawler_1   |   File …
```
> Don't put bytes directly into log - instead write as hex

- .circleci/config.yml
@KPrasch testing out this quick fix.
Fix dependency issues randomly observed on CircleCI regarding `appdirs` library. 
https://app.circleci.com/pipelines/github/nucypher/nucypher/8193/workflows/15b6c3b6-bf70-40e2-ae77-18a2d02796e1/jobs/138713
```
ImportError while loading conftest '/home/circleci/nucypher/tests/conftest.py'.
tests/conftest.py:24: in <module>
from nucypher.characters.control.emitters import WebEmitter
nucypher/characters/control/emitters.py:27: in <module>
from nucypher.utilities.logging import Logger
nucypher/utilities/logging.py:33: in <module>
from nucypher.config.constants import (
nucypher/config/constants.py:23: in <module>
from appdirs import AppDirs
E   ModuleNotFoundError: No module named 'appdirs'
```
> Increment cache version to force rebuild of dependencies.

- deploy/ansible/worker/include/run_external_geth.yml
- newsfragments/2766.bugfix.rst
Fixes ansible geth deployment to force pull stable image even if a version of it is downloaded already.
If the node already had an image tagged `stable` it was not pulling the latest.
> force pull latest tagged image on external geth deployment

- newsfragments/2764.bugfix.rst
- nucypher/blockchain/eth/agents.py
Ignores stakers with expired stakes.
Fixes #2760 .
Including stakers with expired stakes causes an overstating of the number of inactive stakers on the network i.e. stakers who haven't committed to the current period.
> Don't include stakers with expired stakes in the `missing_stakers` results for `StakingEscrowAgent.partition_stakers_by_activity()`

- newsfragments/2769.bugfix.rst
- nucypher/utilities/gas_strategies.py
- tests/unit/test_datafeeds.py
Ignores etherchain gas feed for now since it caused issues due to EIP-1559:
```
File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/datafeeds.py", line 115, in _parse_gas_prices
self.gas_prices = {self.get_canonical_speed(k): int(Web3.toWei(v, \'gwei\')) for k, v in self._raw_data.items()}
File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/datafeeds.py", line 115, in <dictcomp>
self.gas_prices = {self.get_canonical_speed(k): int(Web3.toWei(v, \'gwei\')) for k, v in self._raw_data.items()}
File "/usr/local/lib/python3.8/site-packages/nucypher/utilities/datafeeds.py", line 97, in get_canonical_speed
raise LookupError(message)
builtins.LookupError: \'currentBaseFee\' is not a valid speed name.'
```
> [Hotfix] Remove problematic gas feed for now, and make gas feeds more robust against errors.

- newsfragments/2742.feature.rst
- nucypher/cli/commands/alice.py
- nucypher/cli/commands/bob.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/options.py
- nucypher/config/base.py
- nucypher/crypto/keystore.py
- tests/unit/crypto/test_keystore.py
Feature
2
- Introduces `Keystore.import_secure` method for user-supplied entropy blobs for usage as keystore secrets.
- Introduces `nucypher ursula|alice|bob init --key-material xxx` to accept a user-supplied hex entropy blob to import.
- Fixes #2655 
- Allow additional flexibility and portability of keystores.
**Notes for reviewers**
- Is supporting the import of the secret key material enough portability for browser wallet interoperability or do we also need to support importing keys for individual powers?
> Bring your own key material

- newsfragments/2786.bugfix.rst
- nucypher/cli/commands/stake.py
- nucypher/cli/commands/status.py
- nucypher/utilities/events.py
Related to #2692.
Fixes missed spot for `Path` use instead of `str`.
```
File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/cli/options.py", line 172, in wrapper
return func(**kwargs)
File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/cli/commands/status.py", line 238, in events
csv_output_file=csv_output_file)
File "/Users/derek/Documents/Github/repos/forks/derek/nucypher/nucypher/cli/utils.py", line 269, in retrieve_events
if csv_output_file.exists():
AttributeError: 'str' object has no attribute 'exists'
```
> Fix creation of filepath for output of events to csv file

- newsfragments/2800.bugfix.rst
- nucypher/crypto/keystore.py
> Correct missing call to .public_key() when generating keystore ID.

- deploy/ansible/monitor/include/run_monitor.yml
- deploy/ansible/monitor/setup_monitor.yml
- deploy/ansible/worker/include/setup_docker.yml
- newsfragments/2801.feature.rst
Adds an automated build workflow for an existing ssh accessible cloud ubuntu host to deploy and fully configure a working nucypher-monitor instance.
Having standardized configs for our Ursulas, Eth nodes and now the monitor is nice.
> build and deploy monitor with ansible

- newsfragments/2767.feature.rst
- nucypher/network/retrieval.py
- nucypher/network/server.py
- nucypher/policy/kits.py
- nucypher/policy/maps.py
- nucypher/policy/policies.py
- nucypher/policy/revocation.py
- nucypher/utilities/versioning.py
- tests/acceptance/porter/control/test_porter_web_control_blockchain.py
- tests/integration/characters/test_federated_grant_and_revoke.py
- tests/integration/characters/test_specifications.py
- tests/integration/network/test_failure_modes.py
- tests/integration/porter/control/test_porter_web_control_federated.py
- tests/unit/test_porter.py
- tests/unit/test_versioning.py
Feature
2
The goal of this PR is to gently introduce a unified version and branding scheme for the following entities (alphabetical):
| Entity         | Prefix       | V | Header |
|----------------|--------------|----|-----------|
| `Arrangement` | `b'AR'` | 1.0 | ` b'AR\x00\x01\x00\x00'` |
| `AuthorizedFrag` | `b'KF'` | 1.0 | ` b'KF\x00\x01\x00\x00'` |
| `EncryptedTreasureMap` | `b'EM'` | 1.0 | ` b'EM\x00\x01\x00\x00'` |
| `MessageKit` | `b'MK'` | 1.0 | ` b'MK\x00\x01\x00\x00'` |
| `RetrievalKit` | `b'RK'` | 1.0 | ` b'RK\x00\x01\x00\x00'` |
| `ReencryptionRequest` | `b'RQ'` | 1.0 | ` b'RQ\x00\x01\x00\x00'` |
| `ReencryptionResponse` | `b'RR'` | 1.0 | ` b'RR\x00\x01\x00\x00'` |
| `RevocationOrder` | `b'RV'` | 1.0 | ` …
> Versioning of bytes serializable protocol entities

- newsfragments/2805.feature.rst
- nucypher/network/retrieval.py
- nucypher/policy/kits.py
- nucypher/policy/maps.py
- nucypher/policy/policies.py
- nucypher/policy/revocation.py
- nucypher/utilities/versioning.py
- tests/integration/characters/test_specifications.py
- tests/unit/test_versioning.py
- Feature
- 2
- Extend the brand size in `Versioned` to 4 bytes to make it easier to resolve name clashes in the future.
- Allow all regexp `\w` characters in brands.
The exact values for new 4-byte brands are open for suggestions.
> Wider lanes

- .circleci/config.yml
- deploy/docker/porter/docker-compose.yml
- deploy/docker/porter/nginx/Dockerfile
- deploy/docker/porter/nginx/docker-compose.yml
- deploy/docker/porter/nginx/porter.local_location
- docs/source/application_development/porter.rst
- newsfragments/2807.bugfix.rst
- newsfragments/2807.feature.rst
- nucypher/cli/commands/porter.py
- nucypher/cli/literature.py
- nucypher/control/controllers.py
- nucypher/utilities/porter/porter.py
- setup.py
- tests/acceptance/cli/test_porter.py
- Add CORS support to Porter directly
- Support use of Nginx reverse proxy for Porter
- TLS support via nginx
- CORS support via nginx
> - Fixes #...
Side note: Fixes bug with TLS cert/key filepaths introduced via #2692 , where `Path` object cannot be passed to Hendrix.
```
File "/usr/local/lib/python3.8/site-packages/OpenSSL/SSL.py", line 843, in use_certificate_file
certfile = _path_string(certfile)
File "/usr/local/lib/python3.8/site-packages/OpenSSL/_util.py", line 111, in path_string
raise TypeError("Path must be represented as bytes or unicode string")
TypeError: Path must be represented as bytes or unicode string
```
Running Porter on infrastructure will need CORS support - …
> Porter: Nginx, CORS support

- newsfragments/2815.bugfix.rst
- nucypher/network/nodes.py
- Bugfix
- 1
Fixes the error handling to catch any problems with seed nodes without crashing the learning loop. 
**For reviewers:**
Would it be useful to print the traceback in the log messages? (see TODOs)
> Remove the remnants of the old metadata versioning scheme

- newsfragments/2819.bugfix.rst
- nucypher/characters/lawful.py
- Bugfix
- 1
Make `Ursula.timestamp` available regardless of whether `metadata()` has been called before or not.
> Generate metadata if the timestamp is requested

- .bumpversion.cfg
- docs/source/conf.py
- docs/source/release_notes/releases.rst
- newsfragments/2820.bugfix.rst
- nucypher/__about__.py
- nucypher/acumen/perception.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- tests/acceptance/characters/test_freerider_attacks.py
- tests/acceptance/learning/test_fault_tolerance.py
- tests/acceptance/network/test_network_actors.py
- Bugfix
- 2
- Scraps `suspicious_activities_witnessed` from Ursula. We're not doing anything with it (until #567 is implemented), and it's clogging the memory over time. It is still logged, and I modified the corresponding tests to check the logs instead.
- Limits the number of retained fleet states (to 5, which is what the status page needs). Older states are discarded as the new ones are pushed.
> Fix a memory leak in Ursula

- docs/NuCypher_Beachhead.ipynb
- newsfragments/2829.bugfix.rst
- nucypher/cli/actions/collect.py
- nucypher/cli/actions/confirm.py
- Bugfix
- 1
Fixes a bug reported on Discord, where an old name for the `shares` parameter is used.
> Fix some remaining occurrences of `n` instead of `shares`

- newsfragments/2831.feature.rst
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- tests/contracts/contracts/StakingEscrowTestSet.sol
- tests/contracts/main/staking_escrow/test_staking_escrow_additional.py
- Feature
- 1
To remove staker power in DAO
> Removes snapshots logic from `StakingEscrow`

- .circleci/config.yml
- .circleci/docker/Dockerfile
- .circleci/docker/README.md
- Makefile
- setup.py
Ops
1
- Includes Dockerfile for building rust-python container for use on CI
- Encapsulate path management and permissions in circle config
- Use `python3 -m <module>` everywhere possible
- Reintroduce `[docs]` pip extra in `setup.py`
Accommodate unreleased development installation nucypher with rust dependencies (including bindings) for execution on CI or developer workflows.
> rust-python execution environment for CI

- nucypher/config/base.py
- nucypher/crypto/keystore.py
- tests/unit/crypto/test_keystore.py
> I've added a field report_mnemonic that is by default False, so as to not affect any other tests.  When set to True, when interactive is set to False, generate method returns both keystore and mnemonic.   
> When interactive is True and report_mnemonic is also True, a ValueError is raised.
> Users who are using a function that calls Keystore.generate are not able to ever see their mnemonic and cannot store.
> For example, when a website calls a wrapper around nucypher code to generate a keystore, the user of that website can never see their mnemonic words the way code is currently structured.  With code change, wrapper code can call generate and return mnemonic __words to end user.
> …
> Keystore.generate can return optional mnemonic words

- newsfragments/2851.feature.rst
- nucypher/blockchain/eth/sol/source/contracts/SimplePREApplication.sol
- nucypher/blockchain/eth/sol/source/contracts/StakingEscrow.sol
- nucypher/blockchain/eth/sol/source/threshold/IStaking.sol
- tests/contracts/contracts/PREApplicationTestSet.sol
- tests/contracts/contracts/StakingEscrowTestSet.sol
- tests/contracts/main/application/test_operator.py
- tests/contracts/main/application/test_worker.py
- tests/contracts/main/staking_escrow/test_staking_escrow.py
- Feature
- 2
Renames operator to staking provider and worker to operator
See threshold-network/solidity-contracts#66 and threshold-network/solidity-contracts#67
> Renames operator to staking provider and worker to operator

- .circleci/config.yml
- deploy/docker/Dockerfile
- dev/docker/Dockerfile
- scripts/demos/run_finnegans_wake_demo.sh
- scripts/demos/run_finnegans_wake_demo_docker.sh
Ops
1
- Use nucypher-hosted rust/python docker images for CI and deployments.
- Fixes missed renaming of examples script
- Follow-up for #2835 #2809
- Examples CI compatibility with locally-built nucypher-core
**Notes for Reviewers**
- The two demo failures on CI are expected and will be fixed in a follow-up PR.  This one is only for pointing configs at the nucypher docker repo instead of my personal one.
> Use nucypher/rust-python

- newsfragments/2877.bugfix.rst
- nucypher/acumen/perception.py
- Bugfix
- 1
Not sure how it worked before, but there hasn't been `bytes(node)` for a while. `metadata()` needs to be called explicitly.
> Fix obtaining metadata from a node

- docs/source/architecture/character.rst
- docs/source/index.rst
- newsfragments/2882.doc.rst
Embed Threshold Network intro video in the index page (home page), and embedThreshold PRE Characters video in the architecture/character.html ("Character Concepts") page.
See:
* https://157434-100446516-gh.circle-artifacts.com/0/docs/build/html/index.html
* https://157434-100446516-gh.circle-artifacts.com/0/docs/build/html/architecture/character.html
Based over #2878 .
> Embed videos within docs

- Pipfile
- Pipfile.lock
- dev-requirements.txt
- docs-requirements.txt
- newsfragments/2883.feature.rst
- nucypher/characters/lawful.py
- nucypher/characters/unlawful.py
- nucypher/config/storages.py
- nucypher/crypto/tls.py
- nucypher/network/middleware.py
- nucypher/network/nodes.py
- nucypher/policy/revocation.py
- requirements.txt
- tests/integration/config/test_keystore_integration.py
- tests/mock/performance_mocks.py
- tests/unit/test_external_ip_utilities.py
- Feature
- 1
The following API changes in nucypher-core 0.1 accounted for:
- `staker_address` was renamed to `staking_provider_address`
- `decentralized_identity_evidence` was renamed to `operator_signature`
- `certificate_bytes` was renamed to `certificate_der`
- also, the usage of PEM-encoded certificates was changed to DER (to reviewers: check that I didn't miss anything here)
- `nucypher-core` bumped to 0.1 and dependencies relocked
> Update the usage of nucypher-core with the changes planned for 0.1

- docs-requirements.txt
- scripts/dependencies/docs/Pipfile
Fixes bug in the git url of dependancy `jsonschema2rst`.
The cause of the issue is described [here](https://teknotopnews.com/otomotif-https-github.blog/2021-09-01-improving-git-protocol-security-github/) and [here](https://teknotopnews.com/a/70663683).
This bug was expected from Jan. 11th, 2022.
Docs cannot be built by circleci because it cannot install the dependancies, as seen here https://app.circleci.com/pipelines/github/nucypher/nucypher/9307/workflows/e680a4ca-71cb-4cbf-9106-29e50e9e2b10/jobs/157929
> Fix bug in git url of docs dependancy `jsonschema2rst`

- newsfragments/2886.bugfix.rst
- newsfragments/2886.feature.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/token.py
- nucypher/characters/lawful.py
- nucypher/cli/actions/configure.py
- nucypher/network/trackers.py
- nucypher/utilities/networking.py
- nucypher/utilities/task.py
- tests/unit/test_operator_bonded_tracker.py
- tests/unit/test_work_tracker_error_handling.py
Builds on the `airship` PR ( #2873 ), and fixes / addresses some issues observed during testing.
* Fixes large number of web3 requests made due to the continued running of WorkTracker - the repurposed task used to make sure the operator confirmed transaction is performed on startup. On the first run of Ursula, the WorkTracker is started and tries to confirm the operator, but once it does, the node continues running but the task never shuts down i.e. once the operator is confirmed the WorkTracker isn't proactively stopped. If Ursula is subsequently restarted then all is fine because the operator was already confirmed and the WorkTracker is not needed and is never started.
* Whenever an Ursula's operator address is no longer bonded …
> Fix additional issues from Airship

- newsfragments/2888.bugfix.rst
- nucypher/utilities/porter/porter.py
Updates to Porter
#. Properly ensure that Ursula is reachable during sampling.
Noticed on Porter IBEX that a node that was returned from sampling, was down (my laptop node 😅  when it wasn't running)
> Porter should properly check that Ursula is reachable when sampling

- docs/source/support/contribution.rst
Documentation
2
Adds a detailed explanation of the new release cycle and versioning practices for nucypher.
The legacy versioning scheme had several weaknesses making it difficult to to track issues, compatibility, and coordinate infrastructure deployments.
This is a minimal formality and change to our conventional practices.
> Release Cycle and Versioning Docs

- .circleci/config.yml
> Fixes #2903 - Corrects the circleCI context name for porter publication.

- newsfragments/2929.misc.rst
- nucypher/cli/commands/ursula.py
- tests/acceptance/cli/ursula/test_run_ursula.py
Disable the use of the`--prometheus` flag when running Ursula. 
Fixes #2905 .
Follow-up issue #2928 .
Underlying functionality for which metrics were collected has significantly changed due to merge to Threshold.
> Raise error when prometheus CLI option used for now until functionality can be updated/revamped.

- Pipfile
- Pipfile.lock
- dev-requirements.txt
- docs-requirements.txt
- newsfragments/2927.misc.rst
- requirements.txt
- Other
- 1
Updates `nucypher-core` to 0.2 to make use of the changed structure of HRACs as soon as possible.
> Bump nucypher-core to 0.2 and relock dependencies

- newsfragments/2934.bugfix.rst
- nucypher/blockchain/eth/agents.py
- nucypher/cli/commands/status.py
- nucypher/cli/options.py
- Properly support events from the PREApplication. Currently SimplePREApplication uses the PREApplicationAgent, which is special use. usually the agent's name is the application name with "Agent" appended the end. There is no "SimplePREApplicationAgent", so a special case for the mapping must be added.
- SuscriptionManager needs more work to be supported because it exists in a separate registry.  Support for event retrieval of SubscriptionManager events was therefore always faulty, and is current removed. Support can be added in a follow-up issue/PR (#2935 ).
- Allow NuCypherToken events to be supported.
Fixes #2931 .
> Explain how this PR fits in the greater context of the NuCypher …
> Fix status events

- docs/source/pre_application/cloud_node_management.rst
- docs/source/pre_application/overview.rst
- docs/source/pre_application/testnet.rst
- newsfragments/2916.doc.rst
Documentation
2
- Adapt the nucypher ops tutorial (originally by @theref) for usage on maainnet
- Relocate some portions of the tutorial to a separate page about testnets
- Additional instructions to clarify nucypher-ops usage on mainnet and testnets
- Emphasize superior deployment methods
- Improves on-boarding experience for new node operators
- more...
> Adapt nucypher-ops tutorial for mainnet

- newsfragments/2917.bugfix.rst
- nucypher/blockchain/eth/networks.py
- nucypher/cli/actions/select.py
- nucypher/cli/commands/bond.py
- nucypher/cli/commands/ursula.py
- nucypher/config/base.py
- tests/acceptance/cli/test_mixed_configurations.py
- tests/acceptance/cli/ursula/test_local_keystore_integration.py
- tests/acceptance/cli/ursula/test_run_ursula.py
- tests/constants.py
- tests/integration/cli/actions/test_select_network.py
> Improve handling of network selection in ursula init

- newsfragments/2942.removal.rst
- setup.py
Deprecate the use of `setuptools-markdown` (https://pypi.org/project/setuptools-markdown/) because:
- It depends on `pypandoc` whose latest release, v1.8 on May 10th, deprecated the `convert` function - https://pypi.org/project/pypandoc/1.8/ - but `setuptools-markdown` continues to attempt to use it.
- Fixes the resulting build failure which also affects prior release tags builds:
```
#7 13.95   error: subprocess-exited-with-error
#7 13.95
#7 13.95   × Preparing metadata (pyproject.toml) did not run successfully.
#7 13.95   │ exit code: 1
#7 13.95   ╰─> [32 lines of output]
#7 13.95       long_description_markdown_filename: dist = <setuptools.dist.Distribution object at 0x7f730e355100>; attr = 'long_description_markdown_filename'; …
```
> Remove `setuptools-markdown` dependency

- newsfragments/2946.bugfix.rst
- nucypher/network/templates/basic_status.mako
- Bugfix
- 1
Turns
into
This has been bothering me for a while, and since it was originally my fault...
> Show fleet state checksums as hex instead of an escaped bytestring

- newsfragments/2943.bugfix.rst
- nucypher/blockchain/eth/interfaces.py
Fixes the KeyError occurring on Ropsten/Oryx when node attempts to confirm worker address
> work around for failure to estimate gas occuring on Ropsten

- newsfragments/2952.bugfix.rst
- newsfragments/2952.misc.rst
- nucypher/blockchain/eth/networks.py
- nucypher/cli/types.py
- nucypher/config/constants.py
- tests/acceptance/cli/lifecycle.py
- tests/acceptance/cli/test_mixed_configurations.py
- tests/acceptance/cli/test_porter.py
- tests/mock/interfaces.py
Related to Discord discussion here - https://discord.com/channels/866378471868727316/870383642751430666/987067366699565056.
Values provided via the `--network` parameter were not correctly validated - it allowed payment network values to be specified.
Additionally tests were failing because we are now past the previous probation period - so extended the probation period to August 31, 2022.
> Correctly validate domain/network value provided via `--network` in the CLI

- docs/source/application_development/web_development.rst
- nucypher/control/specifications/fields/base.py
- nucypher/utilities/porter/control/interfaces.py
- nucypher/utilities/porter/control/specifications/porter_schema.py
- nucypher/utilities/porter/porter.py
- tests/acceptance/blockchain/conditions/conftest.py
- tests/acceptance/blockchain/interfaces/test_testerchain.py
- tests/acceptance/porter/control/test_porter_rpc_control_blockchain.py
- tests/acceptance/porter/control/test_porter_web_control_blockchain.py
- tests/acceptance/porter/test_decentralized_porter.py
- tests/fixtures.py
- tests/integration/porter/conftest.py
- tests/integration/porter/control/test_porter_rpc_control_federated.py
- tests/integration/porter/control/test_porter_web_control_federated.py
- tests/integration/porter/test_federated_porter.py
- tests/integration/porter/test_porter_specifications.py
- tests/unit/conditions/conftest.py
- tests/unit/test_control.py
- tests/utils/policy.py
Based over #2961 .
Related to https://github.com/nucypher/nucypher-ts/pull/82.
Related to https://github.com/nucypher/tdec/issues/39.
Allows an optional `context` parameter to be provided as part of the retrieval flow.
`Context` is needed to provide the necessary information to determine whether the recipient satisfies the relevant conditions for getting data re-encrypted/decrypted.
CI tests will continue to fail until an updated version of `nucypher-core` is used.
> Allow Porter to provide `context` for re-encryption conditions

- nucypher/network/server.py
- nucypher/policy/conditions/base.py
- nucypher/policy/conditions/evm.py
- tests/acceptance/blockchain/conditions/conftest.py
- tests/acceptance/blockchain/conditions/test_conditions.py
- tests/acceptance/blockchain/interfaces/test_testerchain.py
- tests/acceptance/characters/test_ursula_web_status.py
- tests/data/test_conditions.json
- tests/unit/conditions/conftest.py
- tests/unit/conditions/test_evm_condition_serializers.py
Handle injection of context variable value into condition. Initially starting with `:userAddress` without any signature validation - simply obtain the address from the information provided in the `context`.
Related to https://github.com/nucypher/tdec/issues/39.
Allows for simple evaluation of conditions that use the `:userAddress` context variable, and require the user address to be provided dynamically i.e. as part of the `context`.
> Initial context variable work (No validation)

- nucypher/characters/lawful.py
- nucypher/network/retrieval.py
- nucypher/network/server.py
- nucypher/policy/conditions/context.py
- nucypher/utilities/porter/control/interfaces.py
- nucypher/utilities/porter/control/specifications/fields/retrieve.py
- nucypher/utilities/porter/control/specifications/porter_schema.py
- nucypher/utilities/porter/porter.py
- tests/acceptance/porter/control/test_porter_web_control_blockchain.py
- tests/integration/porter/control/test_porter_web_control_federated.py
- tests/integration/porter/test_porter_specifications.py
- tests/utils/policy.py
Initial schema for communicating errors that occur during `/retrieve_cfrags` back to the caller.
Fixes https://github.com/nucypher/tdec/issues/57
Fixes https://github.com/nucypher/nucypher/issues/2789
Porter needs to provide better feedback on errors that occur during retrieval.
Initial version looks like:
```json
"result": {
"retrieval_results": [
{
"cfrags": {
// ...
},
"errors": {
"<ursula_address>": "<error_message>",
// category I - network is down, ursulas are wrong, everything is falling apart
"<ursula>": "Internal Server Error",
// sir, stop breaking the porter plz
"<ursula>": "Something wrong with your parameters buddy: ciphertext is undefined",
// condition verification on …
```
> Porter Error Handling for `/retrieve_cfrags` endpoint

- nucypher/policy/conditions/lingo.py
- tests/unit/conditions/conftest.py
- tests/unit/conditions/test_condition_lingo.py
- tests/unit/conditions/test_return_value.py
A small fix that reduces the risk of dangerous input that exploit our use of `eval()`, although this PR doesn't remove `eval()` completely.
To solve this once and for all I'd prefer using a different approach, which affects how we define compound conditions (see https://github.com/nucypher/tdec/issues/59)
> - Fixes #...
> Is there a particular …
> eval is evil 

- .github/workflows/contract_tests.yml
- .github/workflows/python_tests.yml
- setup.py
- tests/conftest.py
- tests/contracts/main/staking_escrow/test_staking_escrow_additional.py
- tests/fixtures.py
Packaging & Removal
1
- Adds `pytest11` entrypoints (allows nucypher to be used as a pytest plugin `pytest-nucypher`)
- Removes unused fixtures relating to deprecated `stakeholder` and allocations
**Why**
- Porter's tests depend on pytest fixtures inside nucypher.  This PR allows porter to use those fixtures by configuring the pytest-nucypher plugin.
> [WIP] Export reusable pytest fixtures and cleanup

- .github/workflows/contract_tests.yml
- .github/workflows/python_tests.yml
- .github/workflows/run_demo.yml
Ops
1
Specified action types for the `pull_request` trigger to include `opened`, `edited`, and `ready_for_review`
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
Actions are not running when pushing new commits to an existing pull request.
> Update github action triggers for pull requests

- .github/workflows/python_tests.yml
- pytest.ini
Code coverage seems to be misreporting. Fix the discrepancy
- Use `coverage` directly instead of via `pytest-cov`
- Improve efficiency by only running coverage on python 3.10, and don't run coverage otherwise
- Only upload coverage reports after all tests have passed
One possible reason is that when using pytest-cov, code coverage is started after functions are defined and have already been loaded instead of before. See https://coverage.readthedocs.io/en/stable/faq.html#q-why-do-the-bodies-of-functions-show-as-executed-but-the-def-lines-do-not
> Code coverage refinement

- newsfragments/README.md
- pyproject.toml
Related to #3022 - don't hide dev newsfragments (not possible with towncrier), but instead just keep it in its own section - tucked away for people who care to look for it. No use including with other release notes section since mostly internal changes eg. gh actions, builds etc.
This is how it look:
```
...
Misc
~~~~
...
Internal Development Tasks
~~~~~~~~~~~~~~~~~~~~~~~~~~
-  (`#3022 <https://github.com/nucypher/nucypher/issues/3022>`__, `#3024 <https://github.com/nucypher/nucypher/issues/3024>`__)
```
> Dev newsfragments will show up in release notes but under its own section

- tests/acceptance/cli/ursula/test_federated_ursula.py
- tests/contracts/main/application/conftest.py
- tests/fixtures.py
- tests/integration/config/test_storages.py
- tests/integration/conftest.py
- tests/utils/config.py
- tests/utils/ursula.py
Bugfix (tests)
1
**Notes**
This error is still occurring occasionally, even with the changes in this PR:
```
tests/acceptance/cli/ursula/test_run_ursula.py .....F
...
twisted.internet.error.CannotListenError: Couldn't listen on any:60998: [Errno 98] Address already in use.
```
> Prevent network port reuse in tests

- Pipfile
- Pipfile.lock
- dev-requirements.txt
- docs-requirements.txt
- docs/source/index.rst
- readthedocs.yml
- requirements.txt
Docs builds are failing - https://readthedocs.org/projects/nucypher/builds/
> Fix failing docs build by relocking dependencies appropriately for jinja2

- .github/workflows/darker.yml
- .pre-commit-config.yaml
Update version of darker from 1.4.2 to a specific unreleased sha commit to resolve the issue. Related to https://github.com/akaihola/darker/issues/403 and https://github.com/akaihola/darker/pull/404.
Also added a python version to the darker gh action, because it fails when running locally without it.
Once the unreleased code is included in a release we can revert back to using release versions.
Failed darker gh action.
```
Run akaihola/darker@[1](https://github.com/nucypher/nucypher/actions/runs/3659069522/jobs/6185481806#step:4:1).4.2
Run akaihola/darker/.github/actions/commit-range@1.4.2
Run if [ "${GITHUB_EVENT_NAME}" == "push" ]
COMMIT_RANGE = 91bb4a4ce39d370b90b4dff4b9db04c1f05c1e34...5[6](https://github.com/nucypher/nucypher/actions/runs/365906 …
```
> Fix issue with darker during failed darker gh action

- newsfragments/3032.bugfix.rst
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/lingo.py
- tests/acceptance/blockchain/conditions/test_conditions.py
- tests/data/test_conditions.json
- tests/unit/conditions/test_return_value.py
> Restrict return value `index` (previously `key`) to only be an integer

- newsfragments/3042.bugfix.rst
- nucypher/network/middleware.py
- nucypher/network/nodes.py
- nucypher/policy/conditions/utils.py
- tests/integration/characters/test_conditional_reencryption.py
- tests/integration/network/test_middleware.py
We were using raw content from HTTP responses which is in bytes. Instead, use the decoded text.
Fixes #3041 . 
Need to update ursula nodes and porter (relock deps) on testnet once merged.
> Fix weird python chars in exception messages/logging/REST responses

- .github/workflows/darker.yml
- .pre-commit-config.yaml
Use latest release of darker that include fix from https://github.com/akaihola/darker/pull/404
Closes #3038 .
> Update darker version that fixes incompatibility with `black` library

- codecov.yml
Related to https://github.com/nucypher/nucypher/pull/3046#issuecomment-1375285804.
I think code coverage needs to be configured to focus on files in `nucypher` subfolder.
> Fix code coverage to only focus on files in `nucypher` subfolder

- nucypher/blockchain/eth/contract_registry/oryx/contract_registry.json
Oryx contract registry not pointing to the correct contract address (it points to `tapir`'s).
> Configure oryx contract registry to point to the correct contract address.

- Pipfile
- examples/heartbeat_demo/alicia.py
- examples/heartbeat_demo/doctor.py
- examples/heartbeat_demo/doctor_keys.py
- newsfragments/3049.feature.rst
- nucypher/characters/base.py
- nucypher/characters/lawful.py
- nucypher/characters/unlawful.py
- nucypher/cli/types.py
- nucypher/crypto/keypairs.py
- nucypher/crypto/keystore.py
- nucypher/crypto/powers.py
- nucypher/crypto/signing.py
- nucypher/crypto/tls.py
- nucypher/crypto/utils.py
- requirements.txt
- tests/contracts/lib/test_signature_verifier.py
- tests/contracts/lib/test_umbral_deserializer.py
- tests/metrics/grant_availability.py
- tests/mock/performance_mocks.py
- tests/unit/crypto/test_keypairs.py
- tests/unit/crypto/test_keystore.py
- tests/unit/test_external_ip_utilities.py
- Feature
- 2
Bumps `nucypher-core` to 0.6 and adjusts the API usage.
In particular, the `nucypher-core` changes are:
- Protocol versions bumped due to some changes in how `umbral-pre` serializes things.
- Public keys are (de)serialized as `to_compressed_bytes()`/`from_compressed_bytes()` instead of `bytes()`/`from_bytes()`
- Signatures are (de)serialized as `to_be_bytes()`/`from_be_bytes()` (the format is r,s pair as 32 bytes + 32 bytes) instead of `bytes()`/`from_bytes()`
- Secret keys are serialized as (de)serialized as `to_be_bytes()`/`from_be_bytes()` instead of `to_secret_bytes()`/`from_secret_bytes()`
- `NodeMetadataPayload.operator_signature` has type `RecoverableSignature` instead of `Optional[bytes]`. 
- Secret seed for …
> Updates for nucypher-core 0.6 and umbral 0.9

- nucypher/cli/actions/select.py
- nucypher/config/base.py
- nucypher/config/characters.py
Bugfix
1
- fixes two bugs introduced in #3030 by:
- bumps the configuration version to follow-up #3030 's changed to ursula config
- use the operator address to identify and name ursula config files (not the "checksum address")
**Note**
- Staged on lynx testnet @ 1b277651a1cdff2fc0d4c6032cbf98b0d6cc7cf9
> Unfederate Configurations

- Pipfile
- Pipfile.lock
- dev-requirements.txt
- docs-requirements.txt
- requirements.txt
- Other
- 2
Nucypher code is intended to use v6 of web3 dependency. So this should be a dependency requirement.
relock_dependencies script has been run.
> Pin web3 version to >= 6.0.0

- .github/workflows/python_tests.yml
- deploy/docker/Dockerfile
The Dockerfile no longer needs to overwrite installations for `nucypher-core` and `ferveo`. The requirements.txt file will take care of this - either by using released versions or git refs.
> Update Ursula Docker build

- .github/workflows/python_tests.yml
- Pipfile.lock
- dev-requirements.txt
- docs-requirements.txt
- requirements.txt
- scripts/dependencies/relock_dependencies.sh
- setup.py
Existing dependencies in `tdec` EPIC do not work for python 3.8, 3.9.
Relocking dependencies using python 3.8. Tested that `pip install -e .[dev]` works and sanity tested with unit tests and a the `test/integration/blockchain` integration test. The virtual env worked with 3.8, 3.9, 3.10 but not 3.11, failing with the following during pip install.
```
ERROR: Could not find a version that satisfies the requirement eth-ape==0.6.8; extra == "dev" (from nucypher[dev]) (from versions: 0.0.0a0, 0.1.0a0, 0.1.0a1, 0.1.0a2)
ERROR: No matching distribution found for eth-ape==0.6.8; extra == "dev"
```
Also:
- Updated github action for python tests to use python 3.8 instead of 3.7. 
- Updated pypi classifiers to not include python 3.6 and 3.7
- Updated relock deps script to specifically use python 3.8 …
> Dependency Hell 🔥 

- Pipfile
- newsfragments/3121.dev.rst
- nucypher/blockchain/eth/agents.py
- nucypher/characters/lawful.py
- nucypher/crypto/ferveo/dkg.py
- requirements.txt
- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/agents/test_coordinator_agent.py
- tests/fixtures.py
- tests/integration/blockchain/test_dkg_ritual.py
- tests/mock/coordinator.py
- tests/unit/test_coordinator.py
Update ferveo version to 0.1.11 which serializes/deserializes DkgPublicKey to/from 48 bytes instead of 56 bytes. 
Related to:
- https://github.com/nucypher/ferveo/pull/109
- https://github.com/nucypher/ferveo/pull/110
Fixes #3120 .
Side note: not the same numbers but reminds me of this song - https://www.youtube.com/watch?v=wNxNwvjzGM0&ab_channel=TootsandTheMaytals-Topic
> Update code to handle DkgPublicKey now being 48 bytes instead of 56 bytes

- Pipfile
- examples/tdec/simple_tdec.py
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/characters/lawful.py
- nucypher/crypto/ferveo/dkg.py
- nucypher/crypto/keypairs.py
- nucypher/crypto/keystore.py
- nucypher/crypto/powers.py
- nucypher/datastore/dkg.py
- nucypher/network/nodes.py
- nucypher/network/server.py
- requirements.txt
- scripts/hooks/nucypher_dkg.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/fixtures.py
- tests/integration/blockchain/test_dkg_ritual.py
- tests/integration/config/test_keystore_integration.py
- tests/mock/coordinator.py
- tests/unit/conftest.py
- tests/unit/test_external_ip_utilities.py
- Feature
- 2
- Integrates pre-release version of `nucypher-core` with `nucypher`
- Replaces `ferveo_py` with Ferveo module exposed from `nucypher.ferveo` 
- Based on changes in https://github.com/nucypher/nucypher-core/pull/53 
- ...
- To remove dependency on `ferveo_py` module
- To iron out any issues with `nucypher-core` and `ferveo` before releasing their new versions
- **Please don't merge**
- Are there any other changes that should go into this PR?
- This is a multi-repository effort. Please consider reviewing PRs in other repos:
- https://github.com/nucypher/ferveo/pull/125
- https://github.com/nucypher/ferveo/pull/119
- …
> Integrate `ferveo` through bindings exposed in `nucypher-core`

- examples/tdec/simple_tdec.py
- newsfragments/3145.feature.rst
- nucypher/policy/conditions/base.py
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/types.py
- nucypher/policy/conditions/utils.py
- scripts/hooks/nucypher_dkg.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/cli/test_ursula_init.py
- tests/acceptance/conditions/test_conditions.py
- tests/fixtures.py
- tests/integration/blockchain/test_dkg_ritual.py
- tests/integration/characters/test_conditional_reencryption.py
- tests/integration/config/test_keystore_integration.py
- tests/unit/conditions/test_condition_lingo.py
- tests/unit/conditions/test_evm_condition_serializers.py
- tests/unit/conditions/test_utils.py
Review #3140  first.
Based over #3140.
Adds a version entry to the condition lingo json. `ConditionLingo` now look like:
```json
{
"version": "x.y.z",
"condition": {
...
}
}
```
"condition" entry is any kind of condition, TimeCondition, ContractCondition, RPCCondition, CompoundCondition(and/or logical combination of all types of conditions).
For example:
```json
{
"version":"1.0.0",
"condition":{
"returnValueTest":{
"value":"0",
"comparator":">"
},
"method":"blocktime",
"chain":131277322940537
}
}
```
OR a more ridiculous case:
```json
{
"version":"1.0.0",
"condition":{
"operator":"or",
"operands":[
{
"chain":131277322940537,
"method":"ownerOf",
"parameters":[
5954
],
"returnValueTest":{
"value":":userAddress",
"comparator":"==" …
```
> Versioned Condition Lingo

- newsfragments/3153.feature.rst
- nucypher/network/decryption.py
- nucypher/network/middleware.py
This is a stop gap measure until we fully address timeouts post 7.0.0. Timeouts could be better configured: 
- An additional Porter request parameter to specify timeouts
- Python API allows timeout to be specified as part of `PRERetrievalClient`. Ideally the `PRERetrievalClient` would use concurrency (i.e. the `WorkerPool` which it currently does not) and an overall timeout used. The `ThresholdDecryptionClient` does this for the cbd `/decrypt` operation.
To prevent scope creep into v7.0.0, we will temporarily solve this problem by extending the hardcoded reencrypt request timeout from middleware.
For the most part, Masterfile has been the only entity encountering this problem and they have been able to work around it, but not lumping many retrieval kits into one `retrieve_cfrags` Porter …
> Stop gap measure for limiting operational timeouts

- Pipfile
- nucypher/blockchain/eth/actors.py
- nucypher/characters/lawful.py
- nucypher/crypto/ferveo/dkg.py
- nucypher/crypto/powers.py
- nucypher/datastore/dkg.py
- requirements.txt
- tests/fixtures.py
- tests/integration/blockchain/test_dkg_ritual.py
- Other
-  2
- Removes dependency on `DkgPublicParams` which is now replaced with a default value
- Introduces `ValidatorMessage` type where necessary
- To implement downstream changes from https://github.com/nucypher/nucypher-core/issues/62
- Uses an [unreleased `ferveo` version](https://github.com/nucypher/ferveo/pull/127/commits/0d4e973e007b16cff34d649ae107608c809349af)
> Remove dependency on deprecated `DkgPublicParams`

- nucypher/acumen/perception.py
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/decorators.py
- nucypher/blockchain/eth/events.py
- nucypher/blockchain/eth/trackers/dkg.py
- nucypher/characters/lawful.py
- nucypher/network/middleware.py
- nucypher/network/nodes.py
- nucypher/network/retrieval.py
- nucypher/network/trackers.py
- nucypher/policy/payment.py
- nucypher/policy/policies.py
- nucypher/types.py
- nucypher/utilities/prometheus/collector.py
- nucypher/utilities/prometheus/metrics.py
- tests/mock/agents.py
[Because:
- Not doing so causes F821 linting errors
https://peps.python.org/pep-0484/#forward-references
https://www.flake8rules.com/rules/F821.html
Removes all but 5 F821 linting errors. Those are genuine undefined name errors rather than type hint issues.
- The relevant section of the PEP484 doc is where it shows an example from Django of using module level imports to avoid circular import problems. I've used that technique several times in this PR.
- To see the remaining F821 issues using [ruff](https://github.com/astral-sh/ruff):
```bash
>>> ruff check --select F821 nucypher
nucypher/blockchain/eth/interfaces.py:523:23: F821 Undefined name `JSONRPCStdoutEmitter`
nucypher/cli/actions/select.py:98:22: …
```
> Make the use of string literal type hints compatible with PEP 484

- scripts/hooks/nucypher_dkg.py
Update `nucypher_dkg` script to use `click` instead of exec args.
Successfully created rituals # 14 and # 15 on `lynx` using the script.
```
$ python ./scripts/hooks/nucypher_dkg.py --eth-provider <> --coordinator-provider <> --ritual-id -1 --signer keystore://<>
...
--------- Initiating Ritual ---------
Using account 0xfDd99d58a7D5696c4f757fAFcAc401d5c9AB87A3 to initiate DKG Ritual
Enter your keystore password:
Commencing DKG Ritual on mumbai using 0xfDd99d58a7D5696c4f757fAFcAc401d5c9AB87A3
Using staking providers for DKG: ['0x210eeAC07542F815ebB6FD6689637D8cA2689392', '0xb15d5A4e2be34f4bE154A1b08a94Ab920FfD8A41']
Broadcasting INITIATERITUAL Legacy Transaction (0.00022690050453801 ETH @ 1.50000003 gwei)
TXHASH …
```
> Update dkg script to use `click` options - exec args were getting complex

- newsfragments/3178.bugfix.rst
- nucypher/crypto/powers.py
Ritual id was not being used correctly as a seed when generating a key for dkg decryption sessions.
Fixes #3175 .
> Use ritual_id properly as a seed

- newsfragments/3174.feature.rst
- nucypher/characters/chaotic.py
- nucypher/characters/lawful.py
- nucypher/crypto/powers.py
Until we get better logic for handling any failures during `precomputed` variant, the `simple` variant should be our default.
Related to #3143 .
> Set default ferveo variant to `simple` instead of `precomputed`

- examples/tdec/simple_tdec_local.py
- newsfragments/3174.feature.rst
- nucypher/blockchain/eth/actors.py
- nucypher/characters/chaotic.py
- nucypher/characters/lawful.py
- nucypher/crypto/powers.py
- tests/integration/characters/test_dkg_and_testnet_bypass.py
Removes the ThresholdDecryptionRequest being returned by Enrico.
Based over #3174 .
Related to #3143 
Threshold Decryption Requests should not be returned by Enrico. It is really a decryption object that Bob populates because it contains `variant` and the `context` dictionary (think Bob signing to prove ownership of a wallet). Therefore, the TDR should only be constructed by Bob and not Enrico.
> Simplify simplified tooling - remove return of TDR when encrypting

- newsfragments/3183.misc.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/trackers/dkg.py
- nucypher/characters/chaotic.py
- nucypher/datastore/dkg.py
- nucypher/utilities/events.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/actors/test_ritual_tracker.py
- tests/integration/blockchain/test_ritual_tracker.py
- tests/mock/coordinator.py
- tests/unit/test_ritualist.py
Ideally, the handling of Ritual events during ritual initiation to be more robust:
- Properly ignore/filter away ritual events for rituals not relevant to the node
- Easily rectify/continue its participation in rituals in case it restarts while a ritual it is participating in is still going on
- Use Coordinator events to gleam node's participation in ritual, and what the node has/has not done already for a ritual.
- If unsure of state, use the Coordinator contract to update what its view of its state is.
- Don't block waiting for a tx to post transcript/aggregated transcript to be fully completed before being able to continue processing events - use `fire_and_forget`, store the tx hash, and keep it moving. 
- If the node already …
> Node DKG Ritual event handling robustness

- newsfragments/3191.misc.rst
- nucypher/blockchain/eth/trackers/dkg.py
- nucypher/utilities/cache.py
- tests/acceptance/actors/test_ritual_tracker.py
- tests/integration/blockchain/test_ritual_tracker.py
- tests/unit/test_ttl_cache.py
Builds on #3183  (based over it).
One concern during a walkthrough with @KPrasch was that the `ParticipationState` dictionary is linearly increasing as rituals are initiated, and never cleared. This can be a very slow memory leak.
This PR uses a time-to-live cache utility for storing participation states and is periodically purged once entries are expired. ParticipationStates are cached for a little longer than the ritual timeout (an additional buffer (1hr in this PR)) just to be sure that we don't potentially get a repeated event right after purging. Remember that the EventScanner goes back some blocks when scanning in case there is a blockchain reorg, so we can get repeated events.
The overall goal here is to ensure that the …
> Use a time-to-live cache for participation states to remove stale ritual participation state information

- newsfragments/3193.misc.rst
- nucypher/characters/lawful.py
- nucypher/crypto/ferveo/dkg.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/integration/blockchain/test_dkg_ritual.py
- tests/integration/config/test_keystore_integration.py
Remove FerveoVariant parameter from public python API for threshold decryption.
Fixes #3181 .
> Don't expose Ferveo variant in python Bob public API

- Pipfile
- requirements.txt
- Other
- 1
- Follow-up to https://github.com/nucypher/nucypher/pull/3171
> Replace git dependency with `nucypher-core@0.11.0` package

- newsfragments/3199.bugfix.rst
- nucypher/utilities/prometheus/collector.py
- nucypher/utilities/prometheus/metrics.py
When running Ursula with --prometheus flag, the execution crash after a while:
```
File "/Users/manumonti/.pyenv/versions/3.10.11/envs/nucypher-ursula/lib/python3.10/site-packages/twisted/internet/defer.py", line 206, in maybeDeferred
result = f(*args, **kwargs)
File "/Users/manumonti/nucypher/nucypher/utilities/prometheus/metrics.py", line 119, in collect_prometheus_metrics
collector.collect()
File "/Users/manumonti/nucypher/nucypher/utilities/prometheus/collector.py", line 62, in collect
self._collect_internal()
File "/Users/manumonti/nucypher/nucypher/utilities/prometheus/collector.py", line 178, in _collect_internal
application_agent = ContractAgency.get_agent(
builtins.TypeError: ContractAgency.get_agent() missing 1 required …
```
> Fix staking metrics in Prometheus exporter

- tests/integration/utilities/test_prometheus_collectors.py
> Commit fb32b081 made eth_provider_uri argument mandatory when creating a StakingProviderMetricsCollector object. This change was not reflected in test_prometheus_collectors.py, causing the test to fail.
> Fix Prometheus staking provider metrics test

- newsfragments/3201.feature.rst
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/time.py
- nucypher/policy/conditions/types.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/conditions/test_conditions.py
- tests/data/test_conditions.json
- tests/fixtures.py
- tests/integration/blockchain/test_dkg_ritual.py
- tests/integration/characters/test_conditional_reencryption.py
- tests/integration/characters/test_dkg_and_testnet_bypass.py
- tests/integration/config/test_keystore_integration.py
- tests/integration/utilities/test_prometheus_collectors.py
- tests/unit/conditions/test_condition_lingo.py
- Feature
- 2
- Adds a mandatory `condition_type` field to condition schemas
- Handles downstream changes from https://github.com/nucypher/nucypher-ts/pull/267
> - Fixes #...
- Provides a concrete condition type to avoid relying on duck-typing across different libraries/languages.
- The tests didn't catch any issues, but are there any other relevant places where this change could have gone unnoticed?
> Add `condition_type` to condition schemas

- newsfragments/3202.bugfix.rst
- nucypher/characters/lawful.py
- tests/integration/utilities/test_prometheus_collectors.py
**Please, don't merge until #3203  is merged**
Commit a4de8a88 introduced amazing changes and solved linting errors like F821. To achieve it, this change introduced the import of PrometheusMetricsConfig in lawful.py, which is dependent on prometheus-client package.
Ursula imports prometheus-client, so no problem with this. But Porter does not. So an import error is raised when Porter is run.
Also, a remaining TODO comment has been cleaned. This TODO is part of a larger comment and was introduced in commit 424e373a and solved afterwards.
> Fix Prometheus import error when running Porter

- newsfragments/3205.feature.rst
- nucypher/network/server.py
- tests/acceptance/conditions/test_multichain_evaluation.py
- tests/acceptance/conftest.py
- tests/integration/conftest.py
- tests/integration/network/test_condition_blockchain_broadcast.py
- tests/utils/ursula.py
Feature
2
- Defines a new JSON endpoint (GET @ `/condition_chains`) that returns a list of all chain IDs Ursula is connected to.
```python
{"version": 1.0, "evm": [1, 5, 80001]}
```
- Multichain fixture and utilities cleanup
- Assistance in evaluating network health and node operator compliance with multichain connection requirements
- The response is versioned so we can expand the number fields in a non-evm future feature
- Co-Authored by @theref
> Multichain connection broadcasting endpoint for Ursula

- newsfragments/3207.feature.rst
- nucypher/blockchain/eth/networks.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/literature.py
- nucypher/config/migrations/__init__.py
- nucypher/config/migrations/_template.py
- nucypher/config/migrations/common.py
- nucypher/config/migrations/configuration_v1_to_v2.py
- nucypher/config/migrations/configuration_v3_to_v4.py
- nucypher/config/migrations/configuration_v4_to_v5.py
- nucypher/config/migrations/configuration_v4_to_v6.py
- nucypher/config/migrations/configuration_v5_to_v6.py
- scripts/migrations/configuration_v1_to_v2.py
- scripts/migrations/configuration_v3_to_v4.py
- scripts/migrations/configuration_v4_to_v5.py
- scripts/migrations/configuration_v5_to_v6.py
Feature 
2
- Introduces new CLI command (`nucypher ursula config migrate`) to migrate ursula configuration files
- Automatically updates configurations to the latest version
- Relocates core migrations functions from `/scripts` -> `nucypher.config.migrations`
- Encapsulates common migration functionality for better code reuse (`nucypher.config.migratons.common`)
- Improves failed migration handling by rolling back the original filename upon failure
- Nodes need an easy way to migrate to the latest version of nucypher
- Prerequisite change for nucypher-ops automation supporting multichain configuration updates 
- Follow-up for #3185 
**Notes for Reviewers**
- Most of the changes are code reorg and relocation …
> Automated Configuration Migrations

- nucypher/utilities/prometheus/collector.py
PR #3199 added provider_uri as an argument to ContractAgency.get_agent() function. This fixed an error, but the name of the argument was not correct.
This commit fixes the bug caused by the use of an incorrect argument name.
The error appears when activating Prometheus in Ursula `nucypher ursula run --prometheus --metrics-port 9090`
```
File "/Users/manumonti/.pyenv/versions/3.10.11/envs/nucypher/lib/python3.10/site-packages/twisted/internet/defer.py", line 206, in maybeDeferred
result = f(*args, **kwargs)
File "/Users/manumonti/Projects/nucypher/nucypher/nucypher/utilities/prometheus/metrics.py", line 119, in collect_prometheus_metrics
collector.collect()
File "/Users/manumonti/Projects/nucypher/nucypher/nucypher/utilities/prometh …
```
> Fix Prometheus collector when using get_agent func

- Pipfile
- requirements.txt
- Other
- 1
- Replaces GH repository in project dependencies with a released `nucypher-core` package
> Use released `nucypher-core@0.12.0` package

- .gitignore
Ruff linter generates a cache folder when it runs pre-commit checks. This folder is ignored since it has its own .gitignore file inside the folder. But for homogeneity purposes, this should be added to .gitignore file.
Also, adding to the general .gitignore file makes this folder have a different treatment by IDEs.
> Add .ruff_cache folder to .gitignore file

- Pipfile
- nucypher/policy/conditions/context.py
- tests/acceptance/conditions/conftest.py
- tests/acceptance/conditions/test_conditions.py
Removes the reliance on `eip712_structs` library and pave the way for a relock of dependencies without `pysha3`.
The `tests/acceptance/conditions` tests, which test validation of userAddress context variable, pass for me locally.
I tried relocking which worked with some tweaks, but the latest version of eth-ape seems to have some changes that are causing acceptance test issues. Therefore such a change will be bigger than expected. cc @jMyles 
> - Fixes #...
Related to https://github.com/nucypher/nucypher/issues/3184. 
**Notes for …
> Remove `eip712_structs` dependency

- .bandit
Bandit seems to have been removed in commit 1209a2dc1c. So .bandit config file is no longer necessary.
> Remove bandit conf file

- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/ape-config.yaml
- tests/acceptance/conditions/conftest.py
- tests/acceptance/conditions/test_conditions.py
- tests/acceptance/conftest.py
- tests/constants.py
As part of #3222 , the version of ape used was updated. Newer versions of ape specifically modify the chain id to no longer be the eth-tester chain id (131277322940537) but instead set it to the geth dev chain id (1337) even though eth-tester is still used. This means that the provider and the testerchain return two different chain ids, which cause our acceptance tests to fail. 
As a fix/workaround, we updated our acceptance tests to use the APE default chain id via commit https://github.com/nucypher/nucypher/commit/f9b3babd69d9d1a93290ef53a4438e424a75d297.
However, after [chatting with APE folks](https://discord.com/channels/922917176040640612/938897808147247186/1151549751318298654), there is a better workaround that can be done …
> Remove Ape chain ID workarounds for acceptance tests

- tests/integration/blockchain/test_block_confirmations.py
- tests/integration/blockchain/test_dkg_ritual.py
- tests/integration/utilities/test_concurrency.py
This reformats the code of the following tests to meet Ruff and Darker code style guides.
This is a necessary step for PR #3238 . The mentioned PR consists of a renaming of these tests, so Ruff and Darker checks are executed in CI, resulting in failed tests since currently, these tests don't meet the mentioned code style guidelines.
> Format tests code to meet Ruff and Darker code style 

- nucypher/blockchain/eth/signers/__init__.py
- nucypher/blockchain/eth/signers/software.py
- scripts/hooks/nucypher_dkg.py
- tests/unit/test_memory_signer.py
Other
2
- Introduces `InMemorySigner` with tests
- Updates DKG script to account for enrico authorization.
- DKG scripting had fallen out of compatibility with the alpha 13 contract suite, this PR restores compatibility
- After redeploying Lynx with Alpha 13, new rituals and threshold decryption live testing is needed
- Related to #3242 .
- We've successfully initiated ritual id `#1`, authorized the default Enrico ('0x070a85eD1Ddb44ecD07e746235bE0B959ff5b30A') to use it, and can encrypt/decrypt data using the ritual.
- You can observe Coordinator txs here - https://mumbai.polygonscan.com/address/0x8e49989f9d3ad89c8ab0de21fba2e00c67ca872f
- You can run the script yourself to test …
> Update DKG dev script to work on Lynx (`dkg-dev-13`)

- nucypher/utilities/prometheus/metrics.py
By default, prometheus exports 'process', 'gc' and 'platform' collector metrics. This information is not useful in our case and introduces some noise to the metrics, so they have been disabled.
By default, prometheus exports 'process', 'gc' and 'platform' collector metrics. This information is not useful in our case and introduces some noise to the metrics, so they have been disabled.
Example of default metrics:
```
python_gc_objects_collected_total{generation="0"} 10717.0
python_gc_objects_collected_total{generation="1"} 3776.0
python_gc_objects_collected_total{generation="2"} 75.0
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0 …
```
> Disable default collector metrics

- tests/acceptance/ape-config.yaml
Ensures that ape configuration points to `nucypher-contracts:main`  for acceptance tests instead of a fork.
> - Fixes #...
Related to https://github.com/nucypher/nucypher-contracts/pull/119.
> Reset nucypher-contracts dependency to be main repos and not a fork

- .github/workflows/python_tests.yml
- docs/source/references/installation.rst
- readthedocs.yml
- setup.py
1
- Indicates compatibility with python 3.11 in package metadata
- Bumps the upper limit bookend python version on CI to python 3.11
- Run Codecov alongside 3.11 test execution
> Bump CI's Maximum Python Version to 3.11

- examples/testnet_compound_multichain_taco.py
- examples/testnet_simple_taco.py
- newsfragments/3279.feature.rst
- nucypher/network/server.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/integration/blockchain/test_integration_dkg_ritual.py
Expired rituals should not be allowed by nodes.
Technically this was implemented at the smart contract level for defining duration, but the nodes never enforced it. It's a bug from a testnet perspective, but a feature for 7.0.0 that wasn't completed previously, hence the newsfragment is a "feature" and not "bug".
> - Fixes #...
Otherwise, what's the point of paying for longer periods of time 😅 .
> Nodes should reject decryption requests for expired rituals

- newsfragments/3282.bugfix.rst
- nucypher/config/base.py
When creating an `UrsulaConfiguration` object, there is a call to connect to the provided endpoints as part of prior work. This is a problem if the endpoint is faulty because it means that the connection can't be established, which raises an exception and prevents the configuration object from being created, which means that the configuration file can't be updated to change the faulty endpoint. 
For example, running `nucypher ursula config` fails, and this is the mechanism to update existing configuration values eg. `nucypher ursula config --eth-endpoint <>` to update the `eth_endpoint` value in the configuration file. Therefore, the only recourse is to update the configuration file manually.
Instead, connections to endpoints …
> UrsulaConfiguration logic was too eager to connect to provided endpoints

- newsfragments/3285.misc.rst
- nucypher/blockchain/eth/clients.py
- tests/unit/test_ethereum_client.py
- 2 Blockchain calls were being made whenever chain id received was an integer instead of hex; this is unnecessary. Simply get the returned result of the blockchain call, then determine if it is hex or int.
- Cache chain id value once obtained for the lifetime of the `EthereumClient` since it will not change - no need to continuously make the call every time.
> - Fixes #...
Related to #3281 , #3283 from a more general efficiency perspective.
> Is there a particular …
> Reduce blockchain calls to get chain id

- nucypher/cli/commands/ursula.py
- nucypher/cli/literature.py
- tests/integration/cli/test_ursula_config_cli.py
Running the command `ursula config ip-address` results in error:
`"ip-address" is not a valid command`.
```
% nucypher ursula config ip-address                                                                                     ✹
Defaulting to Ursula configuration file: '/Users/manumonti/Library/Application Support/nucypher/ursula.json'
Detected IPv4 address (xx.yy.zz.aa) - Is this the public-facing address of Ursula? [y/N]: y
"ip-address" is not a valid command.
Aborted!
```
This is because, after checking the line `if action == "migrate"`, there
is an `elif` keyword. So, when the action is not "migrate", the decision
branch runs the `elif action:` section.
Also, a new test has been added to detect errors like this.
> Fix nucypher CLI: ursula config ip-address

- .bumpversion.cfg
- .github/workflows/docker.yml
Properly allow gh action to specify a commit hash for bumpversion.
> - Fixes #...
> Update bumpversion to allow commit hashes as a suffix

- newsfragments/3303.bugfix.rst
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/time.py
- nucypher/policy/conditions/validation.py
- scripts/hooks/nucypher_dkg.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/conditions/test_conditions.py
- tests/acceptance/conditions/test_multichain_evaluation.py
- tests/data/test_conditions.json
- tests/fixtures.py
- tests/integration/blockchain/test_integration_dkg_ritual.py
- tests/integration/config/test_keystore_integration.py
- tests/unit/conditions/test_condition_lingo.py
- tests/unit/conditions/test_contract_conditions.py
- tests/unit/conditions/test_return_value.py
- Bugfix
- Rework
3
- ReturnValueTest comparator values can't be bytes (since it must be JSON serializable) and therefore will be hex, but it needs to be compared to a contract call result which is in bytes. The bytes returned needs to be converted to hex to compare with the comparator value.
- Prevent `ReturnValueTest` from accepting values that aren't JSON serializable. Try to modify the type to be serializable i.e. tuple/set -> list, bytes -> hex, but otherwise raise exception
- Use ABI types to ensure that return value comparator type and output type of a contract call are congruent. This can be done on condition creation. However, there can be context variables whose value is unknown at creation time, and can only be verified …
> Condition type alignment and enforcement

- newsfragments/3223.feature.rst
- nucypher/cli/commands/ursula.py
- nucypher/utilities/prometheus/metrics.py
- tests/fixtures.py
- tests/integration/cli/test_ursula_cli_prometheus.py
- tests/integration/utilities/test_prometheus_collectors.py
- tests/unit/test_prometheus.py
Prometheus metrics are going to be a necessary part of the Threshold network. Through them, the network can know if the PRE nodes are meeting the node's requirements. This can be useful, for instance, to calculate the staking rewards.
So, the export of these metrics must be mandatory and not an option that the user can enable or disable using command flags.
> Make Prometheus exporter always run with Ursula

- nucypher/blockchain/eth/actors.py
- nucypher/characters/lawful.py
- nucypher/network/server.py
Bugfix
3
- Fixes #3299 
- Catch errors while requesting tdec from nodes (during `derive_decryption_share`) and return them as an HTTP response.
- Ensures that an HTTP response is always produced even in the case of unexpected errors
- Improves the ability to create effective unit tests of core business logic
- Nodes are not explicitly handling decryption errors which makes them noisy and feedback less useful.
- It's too difficult to unit test logic that must be executed inside a running flask server
> Decouples Decryption from Server Logic

- nucypher/blockchain/eth/agents.py
PR https://github.com/nucypher/nucypher-contracts/pull/171 made two changes that affected `nucypher`:
- The data returned from `TACoApplication.getActiveStakingProviders` changed format
- `StakingProviderInfo` struct in `TACoChildApplication` changed
This PR makes the appropriate updates.
**NOTE: ** Once changes from this PR are merged, `nucypher` will no longer be able to do python sampling on old contracts.
> - Fixes #...
> Is there a particular commit/function/section of …
> Update `nucypher` based on latest changes from `nucypher-contracts` #171

- newsfragments/3341.feature.rst
- nucypher/blockchain/eth/agents.py
- nucypher/policy/reservoir.py
- scripts/hooks/nucypher_dkg.py
- tests/acceptance/agents/test_taco_application_agent.py
- tests/acceptance/agents/test_taco_child_application_agent.py
Until we have better syncing between root and child applications, `TACoChildApplication` has the most up-to-date information for stakers , and so should be used for sampling nodes instead.
Related to `nucypher-contracts` PR - https://github.com/nucypher/nucypher-contracts/pull/171
Associated PR in `Porter` - https://github.com/nucypher/nucypher-porter/pull/55.
**NOTE:** once these child sampling PRs merged, TACo contracts need to be redeployed on testnet to the latest in `nucypher-contracts`; ideally only `lynx` to start, since redeployment implies new rituals need to be created because Coordinator was not previously updateable.
> - Fixes #...
> Explain how this PR fits in the greater …
> Perform node sampling using `TACoChildApplication` instead of `TACoApplication`

- .pre-commit-config.yaml
- newsfragments/3337.feature.rst
- nucypher/characters/chaotic.py
- nucypher/characters/lawful.py
- nucypher/network/client.py
- nucypher/network/decryption.py
- nucypher/network/middleware.py
- nucypher/network/retrieval.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/ape-config.yaml
- tests/integration/blockchain/test_integration_dkg_ritual.py
- tests/integration/network/test_middleware.py
- tests/utils/middleware.py
Allows timeouts to be programmatically specified for TACo operations when connecting to nodes i.e. `threshold_decrypt` / `retrieve_and_decrypt` (PRE).
It would allow the ability for Porter to accept timeout parameters in requests that go through Porter - so then apps can potentially use their own timeout (note: for apps to do that `nucypher-ts` (`taco-api`) may need to be modified.
> - Fixes #...
Related to:
- #3153 
- https://github.com/nucypher/nucypher-porter/issues/49
Fixes #3155 .
> What should reviewers …
> Configurable Node Operational Timeouts

- newsfragments/3366.bugfix.rst
- nucypher/blockchain/eth/actors.py
- tests/acceptance/conftest.py
Issue found by @cygnusv :
```
I restarted my node and noticed that it spend 2 minutes in some intermediary step
```
Related to https://github.com/nucypher/nucypher/pull/3364.
Now that the `poll_rate` is longer, this bug is more evident. There is no reason to `sleep` during `block_until_ready` if already node is already bonded and funded. 
> - Fixes #...
> Only sleep during `block_until_ready` on startup when not (bonded and funded)

- newsfragments/3388.feature.rst
- nucypher/acumen/perception.py
- nucypher/cli/commands/ursula.py
- nucypher/utilities/prometheus/collector.py
- nucypher/utilities/prometheus/metrics.py
- tests/acceptance/cli/test_ursula_run.py
- tests/integration/cli/test_ursula_cli_prometheus.py
- tests/integration/utilities/test_prometheus_collectors.py
- tests/unit/test_prometheus.py
Allow metrics-port to be specified via cli option.
- Make prometheus optional via `--prometheus` CLI flag (undoes requirement from #3294)
- Allow `--metrics-port` to be specified via cli option.
- Allow `--metrics-interval` to be specified via cli option (with default value of 90s)
- Rename `app_version` to `version`
- Remove `_gauge` suffix from metric names
- Collect `operator_confirmed` on Polygon (Child) instead of Ethereum (Root)
- Collect operator metric for MATIC balance (fixes #3380, related to #3236)
> - Fixes #...
**Notes for …
> Prometheus Update

- examples/testnet_compound_multichain_taco.py
- examples/testnet_simple_taco.py
- newsfragments/3390.bugfix.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/trackers/dkg.py
- tests/fixtures.py
- tests/integration/blockchain/test_integration_dkg_ritual.py
- tests/mock/coordinator.py
- tests/unit/test_ritualist.py
Nodes should not block learning about nodes to obtain ferveo public keys - these can be obtained from the Coordinator contract/CoordinatorAgent.
1. Increasing multiplier for post aggregation transaction
2. Add random stagger to nodes when submitting aggregated transcript to Coordinator 
> - Fixes #...
Fixes #3389 
> Node freeze fix

- newsfragments/3396.bugfix.rst
- nucypher/config/constants.py
- Bugfix
- 1
- Increases `MAX_UPLOAD_CONTENT_LENGTH` to 250kb
- In TACo, as the threshold increases, so does the number of decryption requests. Those requests are sent in bulk to Porter, who's currently rejecting any request larger than 50kb. So for any threshold larger than ~12, this will result in HTTP `413 Request Entity Too Large`.
- Setting `MAX_UPLOAD_CONTENT_LENGTH` to 250kb should accommodate thresholds up to about 50 
(I eyeballed this one)
- Is 250kb too big/small? Could we increase it to, for example, 500kb? I don't think we're going to run rituals larger than 50-of-M anytime soon?
> set MAX_UPLOAD_CONTENT_LENGTH to 250kb

- nucypher/policy/policies.py
- nucypher/policy/reservoir.py
- tests/unit/test_staking_providers_reservoir.py
In the interest of code freezing,  this PR is set to be merged into `v7.1.0`
Raise appropriate exception when the reservoir to sample from does not have enough values at creation to be able to sample for enough successes.
Related to https://github.com/nucypher/nucypher-porter/issues/50, although Porter can solve this problem on it's own.
> - Fixes #...
> Improve Reservoir Logic for Sampling

- newsfragments/3393.dev.rst
- nucypher/blockchain/eth/registry.py
- nucypher/network/decryption.py
- nucypher/network/nodes.py
- nucypher/utilities/concurrency.py
Currently, TDec is taking roughly 15 to 20 seconds on mainnet, which is very slow. After evaluation what's happening on the 
WorkerPool, I can see that during decryption requests, the WorkerPool was not properly used causing to behave both too impatiently and too patiently at the same time. Let me explain:
* The WorkerPool creates TDec request threads in batches. Current code creates batches of `threshold` size (which is a bit tight since some of them may fail), but immediately creates a new batch since the previous batch didn't succeed right away. This was effectively firing requests to all nodes in the cohort. That's why I'm saying it's too impatient for some things. Ideally, we should wait a reasonable amount of time for each batch.
* At the same time, we were waiting for all threads …
> Optimize use of decryption request WorkerPool

- newsfragments/3397.feature.rst
- nucypher/blockchain/eth/trackers/dkg.py
- nucypher/blockchain/eth/trackers/prometheus.py
- nucypher/characters/lawful.py
- nucypher/network/server.py
- nucypher/utilities/prometheus/collector.py
- nucypher/utilities/prometheus/metrics.py
- nucypher/utilities/task.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/characters/test_start_prometheus_exporter.py
- tests/fixtures.py
- tests/integration/conftest.py
- tests/integration/utilities/test_prometheus_collectors.py
- tests/unit/test_operator_bonded_tracker.py
- tests/unit/test_prometheus_metrics_tracker.py
- Add metrics for decryption requests: total, successes, failures.
- `threshold_decryption_num_successes_total`
- `threshold_decryption_num_failures_total`
- `decryption_request_processing_count`
- `decryption_request_processing_sum`
- Add metric for ritual events last scanned block number:
- `ritual_events_last_scanned_block_number` 
- Update `active_stake` value to be denominated in "ether" instead of "wei".
Fixes #3236 
> - Fixes #...
> Is there a particular …
> Decryption requests metrics

- nucypher/network/decryption.py
- tests/acceptance/actors/test_dkg_ritual.py
- Fix test since the number of successful decryption requests can vary because of concurrency, and how the threshold decryption client executes the requests in parallel (thread pool size etc.)
- Round up the value of batch size and thread pool size which are both decimal factors of the threshold (1.25 and 1.5 respectively); without rounding up small threshold values (eg.  2-of-3 or 3-of-4) can experience slower decryption executions for associated ritual.
> - Fixes #...
> Is …
> Fix failing test and Threshold Rounding

- newsfragments/3368.bugfix.rst
- nucypher/blockchain/eth/interfaces.py
Gas strategies are meant only for legacy transactions (pre-EIP1559). See https://web3py.readthedocs.io/en/stable/gas_price.html
Just by using a gas strategy, web3py understands we're switching to legacy mode. See how TX defaults change after we configure the gas strategy: 
```
(Pdb) fill_transaction_defaults(self.w3, {})
{'value': 0, 'data': b'', 'gas': 53000, 'maxFeePerGas': 1694505782, 'maxPriorityFeePerGas': 1694505750, 'chainId': 80001}
(Pdb) n
--Return--
> /root/gh/nucypher/nucypher/blockchain/eth/interfaces.py(264)attach_middleware()->None
-> self.configure_gas_strategy()
(Pdb) fill_transaction_defaults(self.w3, {})
{'value': 0, 'data': b'', 'gas': 53000, 'gasPrice': 1694505766, 'chainId': 80001}
```
> High-level idea of the …
> Don't use gas strategies

- newsfragments/3416.misc.rst
- nucypher/blockchain/eth/trackers/dkg.py
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/X-yIEMduRXk/0.jpg)](https://www.youtube.com/watch?v=X-yIEMduRXk)
Set interval of `ActiveRitualTracker` to 120s for scanning instead of 20s. O
Fixes #3403 .
See "Notes for reviewers" section.
> - Fixes #...
120s is a suggestion - open to other ideas. On the surface this will make ritual initialization less performant.
It's a balance between how performant we want nodes to be once rituals are requested, and that ritual inititations may be more spread out.
> Reduce the eagerness of the ActiveRitualTracker

- scripts/hooks/nucypher_dkg.py
Two providers on lynx don't have running nodes - not naming any names ... *cough*... @cygnusv ...*cough* j/k 😜 ; don't bother using them for sampling in the `nucypher_dkg` script.
We ignore them for now, but we should probably look into how they can be excluded from being considered "active" by the TACoChildApplication.
> - Fixes #...
> Ignore lynx delinquents

- newsfragments/3428.misc.rst
- nucypher/blockchain/eth/actors.py
- nucypher/crypto/powers.py
- nucypher/datastore/dkg.py
- nucypher/network/server.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/integration/blockchain/test_integration_dkg_ritual.py
Based over #3419 (either review after 3419 is merged. or only review the commits added on top of 3419).
Improve caching/use of:
- Validators and their ferveo keys for a specific ritual - this was `n` rpc calls every time. This benefits round 2 and threshold decryption operations.
- Active Ritual object - without caching we would still get the ritual object from coordinator contract for things like `shares`, `threshold` etc. So we might as well cache the active ritual. Note: only active rituals are cached (not rituals that have not completed). Also the ritual is still checked for being active before returning from the cache as part of the `_resolve_ritual()` call - this benefits only threshold decryption operations.
**Issues …
> Improve cache effectiveness for dkg protocol / threshold decryption

- newsfragments/3432.feature.rst
- nucypher/cli/actions/migrate.py
- nucypher/cli/actions/select.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/literature.py
- nucypher/config/base.py
- tests/integration/cli/actions/test_select_config_file.py
After an upgrade that included changing the configuration file, lynx nodes were failing:
```
No Ursula configurations found. Run 'nucypher ursula init' then try again.
Ignoring configuration file '/root/.local/share/nucypher/ursula.json' - version is too old,
Run `nucypher ursula config migrate --config-file '/root/.local/share/nucypher/ursula.json'` to update it.
No Ursula configurations found. Run 'nucypher ursula init' then try again.
Aborted!
```
The original configuration file for lynx nodes used an old version, and the node would not startup until the configuration file was manually migrated using `nucypher ursula config migrate...`. Instead the node should detect that it has an outdated config file, and automatically …
> Auto migration of outdated configuration files

- .github/workflows/pypi.yml
- MANIFEST.in
- Makefile
- newsfragments/3433.feature.rst
- pyproject.toml
- setup.py
When a release is published, this workflow will be triggered to build `nucypher` and push to https://pypi.org/project/nucypher/
> Build and push package to pypi whenever a release is published

- newsfragments/3434.misc.rst
- nucypher/blockchain/eth/trackers/dkg.py
- tests/unit/test_event_scanner.py
- Move chunk, reorg window settings to ActiveRitualTracker - more applicable there since it has context for the chain being scanned etc. 
- Increase reorg window to 20 since we've noticed that Polygon block reorgs can be that large (sometimes larger) - https://polygonscan.com/blocks_forked
- Increase min chunk size to 60 - 60 blocks @ 2s / block = 120s of events. Using 10 was seemingly too small given Polygon's shorter block time.
- Update test to re-inforce the view that increasing min chunk size reduces rpc calls.
> - Fixes #... …
> Update EventScanner Min chunk for Polygon scans

- newsfragments/3435.bugfix.rst
- nucypher/utilities/events.py
- nucypher/utilities/task.py
- tests/unit/test_event_scanner.py
Noticed the following in logs:
```
"128.199.24.70" - - [07/Feb/2024:21:29:25 +0000] "POST /node_metadata HTTP/1.1" 200 82 "-" "python-requests/2.31.0"
(0x890069) Scanning events in block range 45666360 - 45666408
Scanned total of 0 events, in 2.137392044067383 seconds, total 2 chunk scans performed
...
(0x890069) Scanning events in block range 45666388 - 45666436
Scanned total of 0 events, in 2.069166898727417 seconds, total 2 chunk scans performed
"128.199.24.70" - - [07/Feb/2024:21:30:30 +0000] "GET /ping HTTP/1.1" 200 13 "-" "python-requests/2.31.0"
```
Two things stand out:
1. The scanner is scanning in 1-minute intervals instead of 2-minute intervals
2. 45666436 - 45666388 = 48 blocks yet with a min chunk size of 60 there …
> Fix use of SimpleTask class level INTERVAL value and start chunk size

- newsfragments/3436.dev.rst
- nucypher/blockchain/eth/interfaces.py
* Cache certain RPC calls using web3.py's `simple_cache_middleware` 
* Fixes #3286 
Currently, TACo nodes exhibit a relatively high RPC requests consumption (see #3370). This is just a small improvement, mainly reducing repeated calls to `eth_chainId`. For some reason, with v7.1.0 I've seen ~5,000 of these per day.
We had to temporarily remove `simple_cache_middleware` when @KPrasch and I detected that it shared state between multiple Web3 instances (see https://github.com/ethereum/web3.py/issues/2977 ). This was fixed by https://github.com/ethereum/web3.py/pull/2979, and released in v6.5.0 (https://web3py.readthedocs.io/en/stable/releases.html#web3-py-v6-5-0-20 …
> The return of simple_cache_middleware

- newsfragments/3440.bugfix.rst
- nucypher/network/nodes.py
- nucypher/utilities/certs.py
- tests/acceptance/characters/test_handling_ursula_tls_certs.py
- tests/unit/test_memory_certs.py
Related to #3307 .
There were some certificate issues on Lynx after running the latest 7.2.x code.
Whenever a node, A, learns about node B, it caches B's certificate in an in memory cache. However, if B is restarted, it creates a new certificate. Since A already cached B's prior certificate, it first tries to use that certificate when connecting to B again. However the old certificate is invalid and the request fails. However, requests get retried, but for each retry even though the cached certificate is refreshed to be B's updated certificate, the SSL context used by the underlying connection does not get updated to use the updated CA data. It seems that CA data cannot be updated, and A never ends up connecting to B again, unless …
> Fix Certificate Invalidation issues on Lynx

- newsfragments/3444.misc.rst
- nucypher/blockchain/eth/trackers/dkg.py
- nucypher/utilities/events.py
- tests/unit/test_event_scanner.py
Closes #3443 
Previously we were call eth_getLogs individually for each event type: StartRitual, StartAggregationRound, EndRitual - https://github.com/nucypher/nucypher/blob/v7.2.x/nucypher/utilities/events.py#L239 . 
Instead we can make one eth_getLogs call for all 3 event types. Our volume of rpc calls should now be 1/3 of what it was previously.
> - Fixes #...
> Repetitive calls - get events for multiple event types in one getLogs call

- .github/workflows/lynx.yml
- examples/testnet_compound_multichain_taco.py
- examples/testnet_simple_taco.py
- newsfragments/3468.misc.rst
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/contract_registry/lynx.json
- nucypher/blockchain/eth/contract_registry/tapir.json
- nucypher/blockchain/eth/domains.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/policy/conditions/evm.py
- tests/unit/registry/test_registry_sources.py
- tests/unit/registry/test_registry_soures.py
- tests/unit/test_taco_domains.py
Tapir and Lynx nodes are already running this code (although based over v7.2.0 for simplicity since 7.3.x hasn't really been tested as yet and has changes based on newer non-deployed versions of contracts).
> - Fixes #...
Related to https://github.com/nucypher/nucypher-contracts/pull/251.
Polygon Mumbai is being deprecated and Polygon Amoy should be used moving forward - …
> Migration from Polygon Mumbai to Polygon Amoy

- newsfragments/3478.bugfix.rst
- nucypher/characters/lawful.py
- nucypher/cli/commands/ursula.py
- tests/integration/cli/test_ursula_cli_prometheus.py
It enables a CLI option to specify which of the IP network interfaces available in the machine will be used to expose the metrics (Prometheus exporter).
Fixes #3451.
> Add --metrics-listen-address CLI Prometheus option

- README.md
- newsfragments/3479.misc.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/agents.py
- nucypher/blockchain/eth/contract_registry/lynx.json
- nucypher/blockchain/eth/contract_registry/mainnet.json
- tests/acceptance/conditions/test_conditions.py
Based over #3476 .
> - Fixes #...
Fixes #3466 
Related to https://github.com/nucypher/nucypher-contracts/pull/256
- Only retrieve struct values from contracts based on a number of expected fields in the matching Python struct. This better maintains compatibility whenever the struct in the contract adds fields. This manifests as #3466 .
- Remove old and no longer used code associated with operator information.
- Update the embedded registry based on the updated contract registry from `nucypher-contracts`. This was missed in the last update, **BUT** the …
> Node/Contract Compatibility

- .github/workflows/docker.yml
Seems like our docker job can't log in - https://github.com/nucypher/nucypher/actions/runs/8753164835. I suspect it may have to do with the use of an old version of the gh job, so updating the version. If that is still problematic I'll reset the docker secrets used.
> - Fixes #...
> GH Action Docker login

- newsfragments/3483.bugfix.rst
- newsfragments/3483.feature.rst
- nucypher/blockchain/eth/interfaces.py
- nucypher/cli/config.py
- nucypher/utilities/emitters.py
- nucypher/utilities/logging.py
- tests/unit/test_logging.py
Addresses various issues with logging:
- Console logging now uses a correct logging format
- Logging Levels are now properly adhered to
- When stopping logging, incorrect instances are used for removing observers; track the instances so they can be appropriately removed
- Text file logging and json file logging should not be controlled by the same flag, and should be separated from each other. Also, json file logging should be disabled by default. Users can explicitly enable it using `--json-logs`.
- The StdoutEmitter did not integrate with the underlying logger properly; 
- calls to `message(...)` are now passed to the logger based on verbosity (`info` or `debug`)
- calls to `echo(...)` are *NOT* passed to the logger since these …
> Much Ado About Logging

- newsfragments/3487.misc.rst
- nucypher/network/nodes.py
- nucypher/utilities/logging.py
- tests/unit/test_logging.py
If a separate library, say `ATxM` (which actually does this), creates their own TwistedLogger then that logger does not filter by log level, so the individual observers need to filter by log level themselves.
As a result, each global observer used by `nucypher` is now wrapped to ensure that messages are filtered by log level.
> - Fixes #...
Related to #3483 
Fixes #1712 
> What …
> One more thing: Individual logging observers need to adhere to log levels

- newsfragments/3489.misc.rst
- nucypher/blockchain/eth/actors.py
- tests/acceptance/actors/test_ursula_operator_dkg_rounds.py
- tests/unit/test_ritualist.py
Based over #3487 .
The `on_broadcast_failure` callback gets called from ATxM because of one of 2 scenarios:
1. recoverable error occurred 3 times
2. non-recoverable error
but the tx is not removed from the atxm queue and is continuously retried until a timeout, which means that this problematic ritual tx can cause starvation for other ritual txs in the queue waiting to be executed. (shout out to @KPrasch for thinking about this).
Instead when `on_broadcast_failure` is called for a specific ritual tx, have it remove the tx from the queue, and queue a fresh tx.
> - Fixes #... …
> Ritual tx starvation protection

- nucypher/policy/conditions/context.py
Stop using the deprecated method `encode_structured_data` and instead use `encode_typed_data` to verify EIP-712 signatures used for the `:userAddress` context variable.
> - Fixes #...
> Update user address verification

- .github/workflows/ruff.yaml
- .pre-commit-config.yaml
- nucypher/blockchain/eth/token.py
- nucypher/utilities/certs.py
- pyproject.toml
Seems like the last run of bumpversion (7.3.0 -> 7.4.0) did not update the version in the pyproject.toml file - https://github.com/nucypher/nucypher/commit/f8b2bbba9abeda6e71854d0f5f685a96d76beddd.
That seems to be causing issues with our lynx docker build CI job - https://github.com/nucypher/nucypher/actions/runs/9221829751/job/25371693885.
There are some warnings from ruff about deprecated command/options, fixed those as well - https://github.com/nucypher/nucypher/actions/runs/9269043626/job/25499013103
> - Fixes #...
**Notes for …
> Fix version in pyproject.toml & deprecated ruff command/options

- newsfragments/3508.feature.rst
- nucypher/policy/conditions/auth.py
- nucypher/policy/conditions/context.py
- tests/acceptance/conditions/test_conditions.py
- tests/fixtures.py
- tests/unit/conditions/test_auth.py
- tests/unit/conditions/test_context.py
- Add directives for `:userAddressEIP712` and `:userAddressEIP4361` as user address context variables that will be verified based on the relevant scheme
- `:userAddress` will default to using the EIP712 authentication scheme
- Don't do the additional _2 hour from "issued-at" stale check_ when `not-before` is used in SIWE message (#3506)
- Fixes #3506; somewhat related although not the main focus - really a remnant from #3502.
- Follow-up from #3502 .
> Is there a particular …
> SIWE (EIP4361) Authentication Part 2

- newsfragments/3496.feature.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/constants.py
- nucypher/blockchain/eth/interfaces.py
- nucypher/blockchain/eth/utils.py
- nucypher/policy/conditions/evm.py
- tests/conftest.py
- tests/integration/characters/test_grant_and_revoke.py
- tests/unit/test_rpc_healthcheck.py
Feature
2
Introduces default red-only RPC endpoints at node startup for use with condition evaluation only.  Performs rudimentary health checks for each endpoint.
- #3493 
- Increases the availability and robustness of TACo node's ability to deliver on service requests that involve on-chain reads.
I'm unsure if this PR needs more work.  Running testnet experiments now.
> Default RPC endpoints for Condition Evaluation

- newsfragments/3513.feature.rst
- nucypher/policy/conditions/context.py
- tests/unit/conditions/test_context.py
Add capability for node to process SIWE passthrough messages/signatures that are provided via the `:userAddressExternalEIP4361` context variable.
Related to https://github.com/nucypher/taco-web/pull/529.
> - Fixes #...
> Accept/Process EIP-4361 passthrough context variable used for single sign-on capabilities

- .github/workflows/python_tests.yml
- nucypher/policy/conditions/context.py
- tests/fixtures.py
- tests/unit/conditions/test_context.py
- tests/unit/conditions/test_evm_auth.py
Removes `:userAddressEIP4361` and `:userAddressEIP712` which are superfluous and no longer needed. They were only local to the v7.4.x branch so there are no compatibility concerns with their removal. 
We only need `:userAddress` and `:userAddressExternalEIP4361`.
Some testing updates to split EIP4361 and EIP712 test messages, so that in the future, removal of support for EIP712 will be easier.
> - Fixes #...
> Is there a particular commit/function/section of your PR that …
> Remove unnecessary context variables `:userAddressEIP4361` and `:userAddressEIP712`

- newsfragments/3531.bugfix.rst
- nucypher/blockchain/eth/clients.py
- nucypher/blockchain/eth/interfaces.py
- tests/unit/test_ethereum_client.py
- tests/unit/test_web3_clients.py
The web3 variable on ATxM instance was being set directly, to update it, but this update did not propagate to underlying strategies. 
The ATxM instance should only be created once the properly configured web3 instance is available in the BlockchainInterface.connect() function.
This does not solve the POA issues we've been observing, but it was discovered during investigation.
> - Fixes #...
> Is there a particular commit/function/section of your PR that requires more attention …
> Fix ATxM use of web3 instance provided by `nucypher`

- nucypher/policy/conditions/auth/evm.py
- tests/unit/conditions/test_evm_auth.py
Removes additional `not_before` check added in https://github.com/nucypher/nucypher/pull/3508.
Basically, we don't care about `not_before` in the SIWE message as it pertains to our own check for freshness. Freshness will always be enforced based on the `issued_at` value in the SIWE message irrespective of whether `not_before` is present or not.
> - Fixes #...
Closes #3506.
In the current 7.4.x code, you can circumvent the 2-hour window check by always specifying a `not-before` property at any time in the past. This PR fixes that. …
> EIP4361 freshness check ignores `not-before` value in SIWE message for freshness check; only `issued-at` is used

- newsfragments/3529.feature.rst
- nucypher/blockchain/eth/actors.py
- nucypher/characters/lawful.py
- nucypher/crypto/ferveo/exceptions.py
- nucypher/utilities/warnings.py
- tests/acceptance/actors/test_dkg_failures.py
- tests/acceptance/cli/test_ursula_run.py
- tests/fixtures.py
- tests/integration/actors/test_integration_operator.py
- tests/integration/blockchain/test_integration_dkg_ritual.py
- prevents nodes from starting up of there is a local vs. onchain ferveo public key mismatch
- intentionally crashes nodes participating in DKG ceremonies if there is a local vs. onchain ferveo public key mismatch
- renders a detailed warning for node operators with a ferveo key mismatch
- exposes ferveo public key hex in JSON node status endpoint
- reproduces `InvalidTranscriptAggregate` as observed on mainnet in an automated test due to ferveo key mismatch
- introduces automated testing/mocking for startup and DKG prevention in the case of key mismatch
- removes "precomputed" ferveo variant test cases
Ferveo private keys are expected to be secured by node operators following the documented protocol. 
Without …
> Local/Onchain Ferveo Key Mismatch Mitigations

- newsfragments/3524.bugfix.rst
- nucypher/blockchain/eth/actors.py
- tests/unit/test_ritualist.py
Required Reviews
2
**What this does**
Do not attempt to retry transcript generation if a cryptographic error bubbles up from ferveo itself.  This is a unrecoverable situation so there is no point in retrying.  Currently, nodes re-attempt transcript generation even in unrecoverable circumstances which temporarily blocks the node from participating in other DKG ceremonies.
> Do not retry unrecoverable ferveo errors

- newsfragments/3533.feature.rst
- nucypher/blockchain/eth/actors.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/config.py
- nucypher/cli/literature.py
- nucypher/cli/painting/help.py
- nucypher/config/base.py
- nucypher/config/characters.py
- nucypher/crypto/keystore.py
- nucypher/utilities/warnings.py
- tests/acceptance/cli/test_ursula_run.py
- tests/fixtures.py
- tests/integration/characters/test_bob_handles_frags.py
- tests/integration/characters/test_bob_joins_policy_and_retrieves.py
- tests/integration/characters/test_conditional_reencryption.py
- tests/integration/cli/actions/test_select_config_file.py
- tests/integration/cli/test_ursula_cli_ip_detection.py
- tests/integration/conftest.py
- tests/mock/agents.py
- tests/unit/crypto/test_keystore.py
Feature
2
- Refines the operator experience for creating new nodes
- Blocks new node initialization on hosts with pre-existing local private keys or configurations
- Blocks new node initialization if operator account has already published a ferveo public key
- Expands communications regarding seed phrase security and responsibility while using the `init` CLI
- Alters console presentation of seed phrase to discourage copy/paste confirmation
- Begin to deprecate support for multiple configurations on a single host
- Handle testing and mocking side-effects of these changes
- Prevent tests from writing to production filepaths
Assists #3527 
Closes #3528 
Closes https://github.com/nucypher/sprints/issues/37 …
> Improves comms and key mismatch prevention while using the `init` CLI

- .pre-commit-config.yaml
- newsfragments/3538.feature.rst
- nucypher/cli/actions/auth.py
- nucypher/cli/actions/configure.py
- nucypher/cli/commands/ursula.py
- nucypher/cli/painting/help.py
- nucypher/config/base.py
- nucypher/config/constants.py
- nucypher/crypto/keystore.py
- tests/integration/cli/test_ursula_audit_cli.py
- tests/integration/cli/test_ursula_public_keys_cli.py
- tests/integration/cli/test_ursula_recover_cli.py
Feature
2
- Introduces new CLI commands:
- `nucypher ursula public-keys [--from-mnemonic|--keystore-fiepath <path>]`
- View local public keys from keystores or mnemonic phrases
- `nucypher ursula audit [--view-mnemonic]`
- Verify that a keystore password can decrypt local keys
- Verify that a mnemonic phrase matches a local keystore file
- View mnemonic phrase
- Expands `nucypher ursula recover [--keystore-filepath]`
- automatically updates pre-existing ursula configuration file with recovered key filepath from mnemonic or keystore
- Expands `nucypher ursula init ... --with-mnemonic`
- for node host relocation: creates a new configuration importing keys from the mnemonic
- Fixes #3536 
- Closes …
> Key Recovery and Auditing Tools

- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/offchain.py
- tests/unit/conditions/test_json_api_condition.py
A condition execution result that is an unquoted string and will be used for return value test comparison will raise an exception. Any string that is passed to `ast.literal_eval()` must be quoted.
This affects `JsonApiCondition` in particular because JSON strings are not usually quoted. For example, see test in PR here - https://github.com/nucypher/nucypher/pull/3553/files#diff-f13d425b7bdc36d0f95ef2a4f4d356124fb4af34f11f0194302522cb881c25e3R126-R153. 
Since the book title is what is retrieved using the jsonpath query, which is "Test Title" or "Title", if you pass these to ast.literal_eval(...) it will raise an exception:
```python
In [2]: ast.literal_eval(str("Test Title"))
Traceback (most recent call last):
File …
```
> Condition result that is a string needs to be quoted

- tests/acceptance/agents/test_coordinator_agent.py
- tests/utils/dkg.py
Upstream effect of https://github.com/nucypher/nucypher-contracts/pull/334. The transcript size is now verified by the `Coordinator` contract.
Our acceptance tests were fast and loose when creating fake transcripts. We need to ensure that the fake transcripts are of the correct size.
> - Fixes #...
> Use correct transcript/aggregated transcript size during acceptance tests now that transcript size is checked

- newsfragments/3500.feature.rst
- nucypher/policy/conditions/base.py
- nucypher/policy/conditions/context.py
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/exceptions.py
- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/offchain.py
- nucypher/policy/conditions/time.py
- nucypher/policy/conditions/types.py
- nucypher/policy/conditions/validation.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/acceptance/conditions/conftest.py
- tests/acceptance/conditions/test_conditions.py
- tests/acceptance/conditions/test_multichain_evaluation.py
- tests/acceptance/conftest.py
- tests/unit/conditions/conftest.py
- tests/unit/conditions/test_compound_condition.py
- tests/unit/conditions/test_condition_lingo.py
- tests/unit/conditions/test_context.py
- tests/unit/conditions/test_contract_condition.py
- tests/unit/conditions/test_json_api_condition.py
- tests/unit/conditions/test_sequential_condition.py
- tests/unit/conditions/test_time_condition.py
**Very early and unfinished draft - still not sure if this is the direction we want to go**
Current grammar for sequential conditions:
```python
CONDITION_VARIABLE = {
"varName": STR,
"condition": {
CONDITION
}
}
SEQUENTIAL_CONDITION = {
"name": ...  (Optional),
"conditionType": "sequential",
"conditionVariables": [CONDITION_VARIABLE*]
}
```
1. Execution a list of conditions in order
2. Allow results of one condition to be passed to any subsequent condition(s).
3. If any condition fails (execution or return value check) then the entire condition fails.
4. All conditions return two values from `verify(...)`:
- `condition_successful` - True/False i.e. whether the condition passed or not
- `execution_value` - the value used for …
> Sequential Conditions

- examples/testnet_compound_multichain_taco.py
- examples/testnet_simple_taco.py
This change will update the ritual ID used in the examples. Note that thess examples are used on CI. This is needed because the Lynx ritual #0 has expired, so a new ritual has been initiated (id #`27`).
> Update ritual ID used in Lynx examples

- nucypher/policy/conditions/base.py
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/offchain.py
- nucypher/policy/conditions/time.py
- nucypher/policy/conditions/utils.py
- nucypher/policy/conditions/validation.py
- tests/unit/conditions/test_compound_condition.py
- tests/unit/conditions/test_contract_condition.py
- tests/unit/conditions/test_json_api_condition.py
- tests/unit/conditions/test_rpc_condition.py
- tests/unit/conditions/test_sequential_condition.py
- tests/unit/conditions/test_time_condition.py
Simplify condition validation via inheritance.
To validate initialization values provided during Condition initialization we use a combination of variable checks in the python constructor `__init__()`, and condition schema validation via marshmallow. 
These checks are typically done using separate functions/methods. The reason being that there is a Python API for conditions (i.e. condition objects instantiated directly via constructor), and a condition lingo received from web apps (i.e. objects instantiated from json strings) which go through the marshmallow schema mechanism.
Since this validation is duplicated, all checks performed by schemas needed to be done via python objects - but that wasn't fully the case. Since there are …
> Clean up/Simplify condition validation

- newsfragments/3560.feature.rst
- nucypher/policy/conditions/context.py
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/offchain.py
- tests/unit/conditions/test_condition_lingo.py
- tests/unit/conditions/test_context.py
- tests/unit/conditions/test_contract_condition.py
- tests/unit/conditions/test_json_api_condition.py
- tests/unit/conditions/test_return_value.py
- Allow "authorizationToken" to optionally be provided via the `JsonApiCondition`. The token should always be provided as a context variable since hardcoding it doesn't make much sense:
- It would expose a token in plaintext
- Tokens have expiry dates
- Tokens are associated with specific users, so the use of the hardcoded token would be associated with a specific user and not the requester
Instead, the token should be provided at decryption time. How the token is obtained (OAuth dance or JWT) is up to the application and not `taco-web`.
- The value for the "authorizationToken" context variable can either be OAuth or JWT tokens.
- Example lingo:
```json
{
"conditionType":"json-api",
"endpoint":"https://api.example.com/data", …
```
> JSON API Authorized Requests (OAuth and JWT Support)

- newsfragments/3562.feature.rst
- nucypher/characters/lawful.py
- nucypher/network/decryption.py
- nucypher/network/nodes.py
- nucypher/utilities/latency.py
- tests/acceptance/actors/test_dkg_ritual.py
- tests/unit/test_node_latency_collector.py
Updates a `Learner` to track average node connection latency and then uses it to order threshold decryption requests. Only the `/node_metadata` endpoint for all nodes is used for collecting stats. This is called whenever the Learner learns about other nodes from a node (teacher).
The list of ursulas representing the ritual cohort is ordered from smallest average latency to largest, and that list is used for sending decryption requests via the `ThresholdDecryptionRequestFactory`.
Porter uses the same code and will directly benefit from this change. Porter can use this code before an official `nucypher/nucypher` by simply using a github dependency. Consequently, we can release an updated Porter as soon as we like.
**Issues …
> Learner node latency tracking

- newsfragments/3569.feature.rst
- nucypher/blockchain/eth/actors.py
- nucypher/blockchain/eth/constants.py
- nucypher/blockchain/eth/decorators.py
- nucypher/blockchain/eth/domains.py
- nucypher/blockchain/eth/utils.py
- nucypher/crypto/tls.py
- nucypher/policy/conditions/evm.py
- nucypher/utilities/events.py
- tests/acceptance/conftest.py
- tests/conftest.py
- tests/constants.py
- tests/integration/conftest.py
- tests/integration/learning/test_domains.py
- tests/unit/conditions/test_rpc_condition.py
- tests/unit/conditions/test_time_condition.py
- tests/unit/test_condition_chains.py
- tests/unit/test_event_scanner.py
- tests/unit/test_rpc_healthcheck.py
- tests/unit/test_taco_domains.py
- tests/utils/ursula.py
Very rough initial work as a POC for `lynx` to support any EVM chain for EVM (RPC, Contract, Time) conditions.
A barebones version as of [d414553](https://github.com/nucypher/nucypher/pull/3569/commits/d414553e5306f4de6b4789a7c734a75caa98c52c) is actually running on `lynx` currently via the `nucypher/nucypher:experimental` docker image.
Some outstanding questions/discussion points:
**A: We obtain default rpc endpoints for supported chains based on domain. Each domain has their own rpc endpoint mapping in https://github.com/nucypher/chainlist**
**A: We will use https://github.com/nucypher/chainlist (github solution) for now.**
**A: public RPC endpoints are obtained on startup from https://github.com/nucypher/chainlist. Health …
> EVM Condition on "Any" (Major) EVM Chain (only `lynx` for now)

- newsfragments/3576.feature.rst
- nucypher/blockchain/eth/actors.py
- nucypher/network/server.py
- nucypher/policy/conditions/auth/evm.py
- nucypher/policy/conditions/context.py
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/exceptions.py
- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/types.py
- nucypher/policy/conditions/utils.py
- tests/acceptance/conditions/conftest.py
- tests/acceptance/conditions/test_conditions.py
- tests/acceptance/conditions/test_multichain_evaluation.py
- tests/acceptance/conftest.py
- tests/acceptance/contracts/SmartContractWallet.sol
- tests/integration/network/test_condition_blockchain_broadcast.py
- tests/unit/conditions/test_contract_condition.py
- tests/unit/conditions/test_evm_auth.py
- tests/unit/conditions/test_if_then_else_condition.py
- tests/unit/conditions/test_sequential_condition.py
- tests/unit/conditions/test_utils.py
- tests/utils/ursula.py
- Support for [EIP-1271](https://ethereum.org/en/developers/tutorials/eip-1271-smart-contract-signatures/)
- Will require a corresponding `AuthProvider` implementation in `taco-web` - https://github.com/nucypher/taco-web/pull/617
- Allows EIP1271 auth signature to be used with the `:userAddress` context variable. This way either EIP4361 (for EOA wallets) or EIP1271 (for smart contract wallets) can be used with the `:userAddress` context variable. *(The initial implementation in this PR created a `:userAddressEIP1271` context variable but this was not correct, it would mean that only EIP1271 wallets could be used for condition, which doesn't really make sense - this was fixed and rebased over)*.
> - Fixes …
> EIP1271 Support

- tests/acceptance/conftest.py
`nucypher` acceptance tests are failing due to `nucypher-contracts` changes made in https://github.com/nucypher/nucypher-contracts/pull/345. The TACoApplication contract no longer accepts commitment duration parameters.
> - Fixes #...
> TACoApplication contract no longer accepts commitment duration

- newsfragments/3585.feature.rst
- nucypher/policy/conditions/context.py
- nucypher/policy/conditions/evm.py
- nucypher/policy/conditions/json/rpc.py
- nucypher/policy/conditions/lingo.py
- nucypher/policy/conditions/utils.py
- tests/acceptance/conditions/test_conditions.py
- tests/constants.py
- tests/unit/conditions/test_condition_lingo.py
- tests/unit/conditions/test_context.py
- tests/unit/conditions/test_contract_condition.py
- tests/unit/conditions/test_utils.py
Based over #3586 .
Original issue - https://github.com/nucypher/taco-web/issues/634.
`taco-web` does not handle large numbers, and as such must use `BigInt`. However `BigInt` cannot be serialized to a number in JSON, so instead it is passed as a string `"12312312....1231233132n"` (format established in https://github.com/nucypher/taco-web/pull/637), and as such nodes must handle receiving a number like that. Python does not have the same issue, but must accomodate numbers received from `taco-web` in that format.
Moving forward we have to be careful about any conditions that accept integer values that …
> Handle BigInts provided in JSON from `taco-web`

- nucypher/policy/conditions/utils.py
- tests/acceptance/conftest.py
Fix BigInt string regex warning - the code worked but Python was providing a warning I didn't notice:
```
conditions/utils.py:232: SyntaxWarning: invalid escape sequence '\d'
if re.fullmatch("^-?\d+n$", value):
```
Initial code change in #3585 .
Also fixes acceptance tests to utilize latest fee model role in Coordinator.
> - Fixes #...
> Fix BigInt Regex Warning
